### PR TITLE
Issue 6199 - wrong search query during certificate based authentication

### LINKED ISSUE #6199: LDAP unprotected search query during certificate based authentication
**Issue Description**

During certificate based client authentication, certmap may be configured to use the user cert's subjectDN to look for a match. The SubjectDN is however not escaped and may provides unexpected search result.

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch
 - Browser: N/A

**Steps to Reproduce**
See https://issues.redhat.com/browse/IDMDS-3959

### PR DESCRIPTION
**Pull request by progier389**
Problems:
   SubjectDN extracted from the certificate is not escaped when used by certmap.conf
   Other extracted value are wrongly escaped and quoted when added in filter
   
   Solution: Ensure that proper escape function is used in these two cases.
     Values in filter should not be quoted but * should be escaped.
     
   Note: I considered to reuse the ldap_bv2escaped_filter_value function but it needless realloc the returned data
     so I ended up to rewrite something the escape function (which is quite straightforward anyway).

Issue: #6199 

Reviewed by: @droideck

### CODE REVIEW

File: lib/ldaputil/certmap.c [hunk 1]
```diff
@@ -757,23 +829,29 @@ ldapu_cert_searchfn_default(void *cert, LDAP *ld, void *certmap_info_in, const c
...
             return rv;
         }
-        len = strlen(certmap_info->searchAttr) + strlen(subjectDN) +
-              strlen("=") + 1;
-        certFilter = (char *)ldapu_malloc(len * sizeof(char));
+        size_t subjectDN_len = strlen(subjectDN);
+        size_t eqout_len = 3 * subjectDN_len + 1; /* big enough for worst case (and final \0) */
+        size_t searchAttr_len = strlen(certmap_info->searchAttr);
+        size_t len = searchAttr_len + 1 + eqout_len;
+        char *certFilter = (char *)ldapu_malloc(len * sizeof(char));
```
Comment (droideck) [inline lib/ldaputil/certmap.c:841]: It's not about your code, but still, we can fix it here;- shouldn't the check be `if (!(*certFilter)) {`?
As we need to check if the value at the address `certFilter` points to is NULL (i.e., if the allocation failed).

File: lib/ldaputil/certmap.c [hunk 2]
```diff
@@ -757,23 +829,29 @@ ldapu_cert_searchfn_default(void *cert, LDAP *ld, void *certmap_info_in, const c
...
             free(subjectDN);
             return LDAPU_ERR_OUT_OF_MEMORY;
         }
-        sprintf(certFilter, "%s=%s", certmap_info->searchAttr, subjectDN);
+        strcpy(certFilter, certmap_info->searchAttr);
+        certFilter[searchAttr_len] = '=';
+        rv = value2filter(certFilter+searchAttr_len+1, eqout_len, subjectDN, subjectDN_len);
         free(subjectDN);
+        len = strlen(certFilter);
+        if (rv != LDAPU_SUCCESS || len <= 0) {
```
Comment (droideck) [inline lib/ldaputil/certmap.c:851]: I think we need to free `certFilter` if we fail here.

File: lib/ldaputil/certmap.c [hunk 3]
```diff
@@ -964,14 +1042,22 @@ AddAVAToBuf(char *buf, int size, int *len, const char *tagName, CERTAVA *ava)
...
 
-    rv = CERT_RFC1485_EscapeAndQuote(buf + taglen,
-                                     size - taglen,
-                                     (char *)ava->value.data + lenLen,
-                                     ava->value.len - lenLen);
-
-    *len += strlen(buf);
-
-    return (rv == SECSuccess ? LDAPU_SUCCESS : LDAPU_FAILED);
+    if (is_filter != 0) {
```
Comment (droideck) [inline lib/ldaputil/certmap.c:1046]: Not a nitpick but curiosity. :)
Why `if (is_filter != 0) {` instead of `if (is_filter) {`?

File: dirsrvtests/tests/suites/sasl/regression_test.py [hunk 4]
```diff
@@ -172,6 +178,174 @@ def test_openldap_no_nss_crypto(topology_m2):
...
+        raise e
+
+
+def test_bind_certifcate_with_unescaped_subject(topology_m2, request):
+    """Test close connection on failed bind with a failed cert mapping
+
+    :id: 7545ad30-21dc-11ef-a27e-482ae39447e5
+    :setup: Replication with two suppliers
+            (Only one instance is used but it is better to reuse the
+             same topology than the other tests in this module)
```
Comment (droideck) [inline dirsrvtests/tests/suites/sasl/regression_test.py]: Validate CI failed here:

```

test_bind_certifcate_with_unescaped_subject:243
-----------------------------------------------

* Docstring has RST parsing issues. RST parser messages:

  * Unexpected indentation.

      :setup: Replication with two suppliers
              (Only one instance is used but it is better to reuse the
    >          same topology than the other tests in this module)
      :steps:
```

**Review by droideck — CHANGES_REQUESTED** [review]

File: lib/ldaputil/certmap.c (hunk 1 above)
Comment (progier389) [reply lib/ldaputil/certmap.c:841]: HIMO you should look again. The above line declare certFilter as a pointer on char and initialize it
BTW *certFilter is an uninitialized random value as malloc does not initialize the buffer data

File: lib/ldaputil/certmap.c (hunk 3 above)
Comment (progier389) [reply lib/ldaputil/certmap.c:1046]: It is explicitly mentioned in the "Secure coding practice" 

https://cyber.gouv.fr/sites/default/files/2022/04/anssi-guide-rules_for_secure_c_language_software_development-v1.4.pdf
10.6 Implicit comparison with 0 prohibited

**Comment by progier389** [comment]
Fixed the extra space that cause "Validate tests" to fail 
Fixed the missing free(certFilter)

File: lib/ldaputil/certmap.c (hunk 1 above)
Comment (droideck) [reply lib/ldaputil/certmap.c:841]: Okay, I think I got a bit confused here... All good!

**Review by droideck — APPROVED** [review]
I think it'll be better to wait for CI to be fixed so we can check the PR against tests, but the code looks good to me!

**Comment by progier389** [comment]
I agree about waiting for the CI tests

**Comment by tbordaz** [comment]
Sorry to come late to this thread. Just a question regarding value2filter_sizes.
should not we also escape chars: ',' (comma), '=' (equal), '&' (and), '|' (or), '!'

**Comment by progier389** [comment]
According to https://datatracker.ietf.org/doc/html/rfc4515:
```
The <valueencoding> rule ensures that the entire filter string is a
   valid UTF-8 string and provides that the octets that represent the
   ASCII characters "*" (ASCII 0x2a), "(" (ASCII 0x28), ")" (ASCII
   0x29), "\" (ASCII 0x5c), and NUL (ASCII 0x00) are represented as a
   backslash "\" (ASCII 0x5c) followed by the two hexadecimal digits
   representing the value of the encoded octet.
```
   So the answer is no.
