### PR TITLE
Issue 6623 - UI - Generic updates

### LINKED ISSUE #6623: UI - Generic updates
**Issue Description**

- Missing dot in warning alert when changing suffix backend state.
- No success alert upon deleting local password policy.
- Tooltips for part of Syntax Settings for local password policies do not show.

**Package Version and Platform:**
 - Package and version: main branch

**Steps to Reproduce**

- See tickets below for more detail.

**Additional context**
https://issues.redhat.com/browse/DIRSRV-233
https://issues.redhat.com/browse/DIRSRV-234
https://issues.redhat.com/browse/DIRSRV-249

### PR DESCRIPTION
**Pull request by jchapma**
Bug description:
Missing dot in warning alert when changing suffix backend state. 
No success alert upon deleting local password policy. 
Tooltips for part of Syntax Settings for local password policies do not show.

Fixes: https://github.com/389ds/389-ds-base/issues/6623

Reviewed by:

### CODE REVIEW

File: src/cockpit/389-console/src/lib/database/localPwp.jsx [hunk 1]
```diff
@@ -702,10 +702,10 @@ class CreatePolicy extends React.Component {
                                             isDisabled={!this.props.passwordchecksyntax}
                                         />
                                     </GridItem>
-                                    <GridItem className="ds-label" offset={5} span={3} title={_("The maximum number of times the same character can sequentially appear in a password (passwordMaxRepeats).")}>
+                                    <GridItem className="ds-label" offset={5} span={3}>
                                         {_("Max Sequence Sets")}
                                     </GridItem>
-                                    <GridItem span={1}>
+                                    <GridItem span={1} title={_("The maximum number of times the same character can sequentially appear in a password (passwordMaxRepeats).")}>
```
Comment (mreynolds389) [inline src/cockpit/389-console/src/lib/database/localPwp.jsx:708]: All of these "title" updates need to also be reflected in "ja.po" file.  Otherwise the language translation will fail

Comment (mreynolds389) [reply src/cockpit/389-console/src/lib/database/localPwp.jsx:708]: > All of these "title" updates need to also be reflected in "ja.po" file. Otherwise the language translation will fail

Nevermind, I thought you were changing the text.  Instead you are just moving the existing text around

File: src/cockpit/389-console/src/lib/database/localPwp.jsx [hunk 2]
```diff
@@ -1855,7 +1855,12 @@ export class LocalPwPolicy extends React.Component {
                 .spawn(cmd, { superuser: true, err: "message" })
                 .done(content => {
                     this.handleLoadPolicies();
+                    this.props.addNotification(
+                        "success",
+                        _("Successfully deleted password policy")
```
Comment (mreynolds389) [inline src/cockpit/389-console/src/lib/database/localPwp.jsx]: This text does not exist in our PO files, so there is no need to encapsulate it in:   _("")

Comment (jchapma) [reply src/cockpit/389-console/src/lib/database/localPwp.jsx]: Thanks Mark, I didn't realise the _ was an i18n function :(

**Review by mreynolds389 — APPROVED** [review]
