### PR TITLE
Issue 6429 - UI - clicking on a database suffix under the Monitor tab crashes UI

### LINKED ISSUE #6429: UI - clicking on a database suffix under the Monitor tab crashes UI
**Issue Description**

Crash happens on mdb instance as "dn cache" does not exist.

To reproduce click on:   Monitor -> Database -> SUFFIX

```
suffixMonitor.jsx:170 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Function.<anonymous> (suffixMonitor.jsx:170:50)
    at process_queue (cockpit.js:1311:37)
    at cockpit.js:1324:35
    at later_drain (cockpit.js:1205:13)


monitor/suffixMonitor.jsx:

    const dnratio = config.attrs.dncachehitratio[0];

```

### PR DESCRIPTION
**Pull request by jchapma**
Bug description:
Clicking on a db suffix under the Monitor tab causes the UI to crash when the instance is configured with the mdb db engine.

Fix description:
Introduced separate database and suffix monitor classes tailored for mdb. Parent class detects the configured db engine and calls the appropriate monitor class.

Fixes: https://github.com/389ds/389-ds-base/issues/6429

Reviewed by:

### CODE REVIEW

**Comment by mreynolds389** [comment]
@jchapma can you rebase main so I can test this?  Thanks!

File: src/cockpit/389-console/src/lib/database/databaseConfig.jsx [hunk 1]
```diff
@@ -1253,20 +1253,10 @@ export class GlobalDatabaseConfigMDB extends React.Component {
...
         }
-
-        // Check if have any errors on our attributes
-        for (const config_attr of check_attrs) {
-            if (config_attr in this.state.error && this.state.error[config_attr]) {
-                saveBtnDisabled = true;
-                break;
-            }
-        }
-
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/database/databaseConfig.jsx]: Why remove the code? The removal is not mentioned in the commit message and, IIUC, the code has a purpose.

File: src/cockpit/389-console/src/monitor.jsx [hunk 2]
```diff
@@ -580,6 +589,25 @@ export class Monitor extends React.Component {
...
+                    const config = JSON.parse(content);
+                    const attrs = config.attrs;
+                    if ('nsslapd-backend-implement' in attrs) {
+                        this.setState({
+                            dbEngine: attrs['nsslapd-backend-implement'][0],
+                        });
+                    }
+                });
+    }
+
```
Comment (droideck) [inline src/cockpit/389-console/src/monitor.jsx]: If this function fails, I think, we need to report an error in a `.fail(error` section.

**Review by droideck — CHANGES_REQUESTED** [review]
Couple of issues, otherwise, looks good!

File: src/cockpit/389-console/src/lib/database/databaseConfig.jsx (hunk 1 above)
Comment (jchapma) [reply src/cockpit/389-console/src/lib/database/databaseConfig.jsx]: This section was removed in the rebase,I will add it back.

**Review by droideck — APPROVED** [review]
LGTM!
