### PR TITLE
Issue 5408: lmdb import is slow

### LINKED ISSUE #5408: LMDB import is very slow
**Issue Description**

Import becomes very slow when attempt to import very large LDIF (20 million).  By around 150k entries processed performance drops to 11 entries per second.  

Even from the start of the import it is very  slow:

```
[09/Aug/2022:05:34:28.768671280 -0400] - INFO - dbmdb_import_monitor_threads - import userroot: Processed 2592 entries -- average rate 129.6/sec, recent rate 129.6/sec, 
...
...
[09/Aug/2022:10:01:55.376274042 -0400] - INFO - dbmdb_import_monitor_threads - import userroot: Processed 170586 entries -- average rate 11.1/sec, recent rate 10.0/sec,
```
 
Stack trace:

```
Thread 27 (Thread 0x7f01659be640 (LWP 2355461) "ns-slapd"):
#0  0x00007f06eb41c07b in fdatasync () at /lib64/libc.so.6
#1  0x00007f06e765bddd in mdb_env_sync () at /lib64/liblmdb.so.0.0.0
#2  0x00007f06e7664f17 in mdb_txn_commit () at /lib64/liblmdb.so.0.0.0
#3  0x00007f06e7927bdd in dbmdb_import_writer (param=0x55b828cb7cd0) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:3288
#4  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#5  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#6  0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 26 (Thread 0x7f01661bf640 (LWP 2355460) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb37a1b2 in pthread_mutex_lock@@GLIBC_2.2.5 () at /lib64/libc.so.6
#2  0x00007f06e793027a in rdncache_rdn_lookup (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32190, parentid=parentid@entry=0, nrdn=0x7f010415e960 "dc=example,dc=com") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:502
#3  0x00007f06e7930bcf in process_entryrdn (wqelmnt=0x55b828d32190, ep=0x7f0104181e20) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2333
#4  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#5  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#6  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#7  0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 25 (Thread 0x7f01669c0640 (LWP 2355459) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb37a1b2 in pthread_mutex_lock@@GLIBC_2.2.5 () at /lib64/libc.so.6
#2  0x00007f06e793027a in rdncache_rdn_lookup (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32238, parentid=parentid@entry=0, nrdn=0x7f00f401c350 "dc=example,dc=com") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:502
#3  0x00007f06e7930bcf in process_entryrdn (wqelmnt=0x55b828d32238, ep=0x7f00f417e650) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2333
#4  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#5  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#6  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#7  0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 24 (Thread 0x7f01671c1640 (LWP 2355458) "ns-slapd"):
#0  0x00007f06eb379daf in __pthread_mutex_lock_full () at /lib64/libc.so.6
#1  0x00007f06e76618bf in mdb_txn_renew0 () at /lib64/liblmdb.so.0.0.0
#2  0x00007f06e7661f80 in mdb_txn_begin () at /lib64/liblmdb.so.0.0.0
#3  0x00007f06e791f4a6 in dbmdb_start_txn (funcname=funcname@entry=0x7f06e79507f0 <__FUNCTION__.2.lto_priv.0> "dbmdb_open_cursor", parent_txn=<optimized out>, parent_txn@entry=0x0, flags=flags@entry=0, txn=txn@entry=0x7f01671c08c8) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_txn.c:169
#4  0x00007f06e7922b2e in dbmdb_open_cursor (dbicur=0x7f01671c08c0, ctx=<optimized out>, dbi=<optimized out>, flags=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_instance.c:1222
#5  0x00007f06e792f481 in rdncache_index_lookup_by_rdn (_nrdnlen=<optimized out>, lognotfound=0, _nrdn=0x7f010c139a90 "uid=bkrispenz156924", parentid=1, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:240
#6  rdncache_rdn_lookup_no_lock (cache=0x55b828cc1480, parentid=parentid@entry=1, nrdn=nrdn@entry=0x7f010c139a90 "uid=bkrispenz156924", lognotfound=lognotfound@entry=0, slot=0x55b828d322e0) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:490
#7  0x00007f06e792f8b3 in rdncache_new_elem (head=0x7f00f80beeb0, entryid=entryid@entry=156925, parentid=parentid@entry=1, nrdnlen=nrdnlen@entry=20, nrdn=nrdn@entry=0x7f010c139a90 "uid=bkrispenz156924", rdnlen=rdnlen@entry=20, rdn=0x7f010c079600 "uid=BKrispenz156924", slot=0x55b828d322e0) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:322
#8  0x00007f06e792fb93 in rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d322e0, entryid=156925, parentid=parentid@entry=1, nrdnlen=20, nrdn=nrdn@entry=0x7f010c139a90 "uid=bkrispenz156924", rdnlen=20, rdn=0x7f010c079600 "uid=BKrispenz156924") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:389
#9  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d322e0, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#10 dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#11 0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#12 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#13 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 23 (Thread 0x7f01679c2640 (LWP 2355457) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32388, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32388, entryid=156932, parentid=parentid@entry=1, nrdnlen=20, nrdn=nrdn@entry=0x7f0100026130 "uid=trichards156931", rdnlen=20, rdn=0x7f010008cfb0 "uid=TRichards156931") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32388, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 22 (Thread 0x7f01681c3640 (LWP 2355456) "ns-slapd"):
#0  0x00007f06eb37392a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f06eb376434 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#2  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c
:103
#3  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#4  rdncache_wait4older_slots (slot=0x55b828d32430, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#5  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32430, entryid=156940, parentid=parentid@entry=1, nrdnlen=20, nrdn=nrdn@entry=0x7f00fc048ef0 "uid=mkrispenz156939", rdnlen=20, rdn=0x7f00fc05ad20 "uid=MKrispenz156939") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#6  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32430, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#7  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#8  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#9  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#10 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 21 (Thread 0x7f01689c4640 (LWP 2355455) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d324d8, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d324d8, entryid=156941, parentid=parentid@entry=1, nrdnlen=18, nrdn=nrdn@entry=0x7f010802b0a0 "uid=mbordaz156940", rdnlen=18, rdn=0x7f010802e3c0 "uid=MBordaz156940") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d324d8, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 20 (Thread 0x7f01691c5640 (LWP 2355454) "ns-slapd"):
#0  0x00007f06eb37392a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f06eb376434 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#2  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#3  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#4  rdncache_wait4older_slots (slot=0x55b828d32580, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#5  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32580, entryid=156942, parentid=parentid@entry=1, nrdnlen=17, nrdn=nrdn@entry=0x7f013804a860 "uid=bhonek156941", rdnlen=17, rdn=0x7f01380357e0 "uid=BHonek156941") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#6  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32580, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#7  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#8  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#9  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#10 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 19 (Thread 0x7f01699c6640 (LWP 2355453) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32628, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32628, entryid=156943, parentid=parentid@entry=1, nrdnlen=19, nrdn=nrdn@entry=0x7f0110152650 "uid=fjohnson156942", rdnlen=19, rdn=0x7f0110004a40 "uid=FJohnson156942") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32628, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 18 (Thread 0x7f016a1c7640 (LWP 2355452) "ns-slapd"):
#0  0x00007f06eb37392a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f06eb376434 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#2  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#3  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#4  rdncache_wait4older_slots (slot=0x55b828d326d0, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#5  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d326d0, entryid=156933, parentid=parentid@entry=1, nrdnlen=18, nrdn=nrdn@entry=0x7f0114072e80 "uid=bbordaz156932", rdnlen=18, rdn=0x7f0114035690 "uid=BBordaz156932") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#6  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d326d0, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#7  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#8  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#9  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#10 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 17 (Thread 0x7f016a9c8640 (LWP 2355451) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32778, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32778, entryid=156935, parentid=parentid@entry=1, nrdnlen=16, nrdn=nrdn@entry=0x7f01200949f0 "uid=crose156934", rdnlen=16, rdn=0x7f01200cdfc0 "uid=CRose156934") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32778, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 16 (Thread 0x7f016b1c9640 (LWP 2355450) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32820, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32820, entryid=156936, parentid=parentid@entry=1, nrdnlen=20, nrdn=nrdn@entry=0x7f0148033e20 "uid=cgriffith156935", rdnlen=20, rdn=0x7f014800d7d0 "uid=CGriffith156935") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32820, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 15 (Thread 0x7f016b9ca640 (LWP 2355449) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d328c8, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d328c8, entryid=156937, parentid=parentid@entry=1, nrdnlen=17, nrdn=nrdn@entry=0x7f012c0229f0 "uid=gbrown156936", rdnlen=17, rdn=0x7f012c0362f0 "uid=GBrown156936") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d328c8, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 14 (Thread 0x7f016c1cb640 (LWP 2355448) "ns-slapd"):
#0  0x00007f06eb37392a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f06eb376434 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#2  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c
:103
#3  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#4  rdncache_wait4older_slots (slot=0x55b828d32970, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#5  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32970, entryid=156944, parentid=parentid@entry=1, nrdnlen=17, nrdn=nrdn@entry=0x7f013c1433e0 "uid=fdugan156943", rdnlen=17, rdn=0x7f013c026410 "uid=FDugan156943") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#6  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32970, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#7  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#8  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#9  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#10 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 13 (Thread 0x7f016c9cc640 (LWP 2355447) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32a18, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32a18, entryid=156926, parentid=parentid@entry=1, nrdnlen=20, nrdn=nrdn@entry=0x7f012402eba0 "uid=areynolds156925", rdnlen=20, rdn=0x7f01240baaa0 "uid=AReynolds156925") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32a18, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 12 (Thread 0x7f016d1cd640 (LWP 2355446) "ns-slapd"):
#0  0x00007f06eb37392a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f06eb376434 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#2  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#3  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#4  rdncache_wait4older_slots (slot=0x55b828d32ac0, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#5  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32ac0, entryid=156927, parentid=parentid@entry=1, nrdnlen=18, nrdn=nrdn@entry=0x7f011c000e90 "uid=mmullen156926", rdnlen=18, rdn=0x7f011c104820 "uid=MMullen156926") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#6  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32ac0, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#7  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#8  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#9  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#10 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 11 (Thread 0x7f016d9ce640 (LWP 2355445) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32b68, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32b68, entryid=156928, parentid=parentid@entry=1, nrdnlen=20, nrdn=nrdn@entry=0x7f0140001950 "uid=drichards156927", rdnlen=20, rdn=0x7f0140133570 "uid=DRichards156927") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32b68, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 10 (Thread 0x7f016e1cf640 (LWP 2355444) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32c10, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32c10, entryid=156938, parentid=parentid@entry=1, nrdnlen=18, nrdn=nrdn@entry=0x7f012811a2b0 "uid=amullen156937", rdnlen=18, rdn=0x7f012801c510 "uid=AMullen156937") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32c10, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 9 (Thread 0x7f016e9d0640 (LWP 2355443) "ns-slapd"):
#0  0x00007f06eb37392a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f06eb376434 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#2  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#3  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#4  rdncache_wait4older_slots (slot=0x55b828d32cb8, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#5  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32cb8, entryid=156939, parentid=parentid@entry=1, nrdnlen=19, nrdn=nrdn@entry=0x7f0134043790 "uid=hsalinas156938", rdnlen=19, rdn=0x7f01340d4a00 "uid=HSalinas156938") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#6  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32cb8, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#7  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#8  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#9  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#10 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 8 (Thread 0x7f016f1d1640 (LWP 2355442) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32d60, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32d60, entryid=156945, parentid=parentid@entry=1, nrdnlen=17, nrdn=nrdn@entry=0x7f0144164d30 "uid=mwoods156944", rdnlen=17, rdn=0x7f014402a4f0 "uid=MWoods156944") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32d60, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 7 (Thread 0x7f016f9d2640 (LWP 2355441) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32e08, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32e08, entryid=156929, parentid=parentid@entry=1, nrdnlen=20, nrdn=nrdn@entry=0x7f0150088e40 "uid=akrispenz156928", rdnlen=20, rdn=0x7f0150163810 "uid=AKrispenz156928") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32e08, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 6 (Thread 0x7f01701d3640 (LWP 2355440) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32eb0, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32eb0, entryid=156934, parentid=parentid@entry=1, nrdnlen=17, nrdn=nrdn@entry=0x7f014c088cd0 "uid=csholl156933", rdnlen=17, rdn=0x7f014c03a860 "uid=CSholl156933") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32eb0, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 5 (Thread 0x7f01709d4640 (LWP 2355439) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d32f58, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d32f58, entryid=156946, parentid=parentid@entry=1, nrdnlen=19, nrdn=nrdn@entry=0x7f015c05e250 "uid=asalinas156945", rdnlen=19, rdn=0x7f015c13b110 "uid=ASalinas156945") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d32f58, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 4 (Thread 0x7f01711d5640 (LWP 2355438) "ns-slapd"):
#0  0x00007f06eb37392a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f06eb376434 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#2  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#3  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#4  rdncache_wait4older_slots (slot=0x55b828d33000, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#5  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d33000, entryid=156930, parentid=parentid@entry=1, nrdnlen=15, nrdn=nrdn@entry=0x7f015400b600 "uid=mkey156929", rdnlen=15, rdn=0x7f015409e200 "uid=MKey156929") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#6  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d33000, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#7  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#8  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#9  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#10 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 3 (Thread 0x7f01719d6640 (LWP 2355437) "ns-slapd"):
#0  0x00007f06eb373af0 in __lll_lock_wait () at /lib64/libc.so.6
#1  0x00007f06eb379413 in __pthread_mutex_cond_lock () at /lib64/libc.so.6
#2  0x00007f06eb37631e in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#3  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cc14b0, mutex=mutex@entry=0x55b828cc1488) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#4  0x00007f06e792fb63 in rdncache_wait4older_slots (slot=<optimized out>, cache=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:297
#5  rdncache_wait4older_slots (slot=0x55b828d330a8, cache=0x55b828cc1480) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:290
#6  rdncache_add_elem (cache=0x55b828cc1480, slot=slot@entry=0x55b828d330a8, entryid=156931, parentid=parentid@entry=1, nrdnlen=17, nrdn=nrdn@entry=0x7f01580a7bb0 "uid=fwoods156930", rdnlen=17, rdn=0x7f015802eee0 "uid=FWoods156930") at ldap/servers/slapd/back-ldbm/db-mdb/mdb_rdncache.c:388
#7  0x00007f06e793079a in process_entryrdn (wqelmnt=0x55b828d330a8, ep=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2356
#8  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:2666
#9  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#10 0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#11 0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 2 (Thread 0x7f01721d7640 (LWP 2355436) "ns-slapd"):
#0  0x00007f06eb37392a in __futex_abstimed_wait_common () at /lib64/libc.so.6
#1  0x00007f06eb376434 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /lib64/libc.so.6
#2  0x00007f06e7927797 in safe_cond_wait (cond=cond@entry=0x55b828cb7b78, mutex=mutex@entry=0x55b828cb7b50) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:103
#3  0x00007f06e792821b in dbmdb_import_workerq_push (q=q@entry=0x55b828cb7b48, data=data@entry=0x7f01721d6ab0) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:116
#4  0x00007f06e792b186 in dbmdb_import_producer (param=0x55b828cb7c40) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:563
#5  0x00007f06eb0a0c34 in _pt_root () at /lib64/libnspr4.so
#6  0x00007f06eb376d92 in start_thread () at /lib64/libc.so.6
#7  0x00007f06eb3169e0 in clone3 () at /lib64/libc.so.6

Thread 1 (Thread 0x7f06ea3209c0 (LWP 2355435) "ns-slapd"):
#0  0x00007f06eb41bddd in select () at /lib64/libc.so.6
#1  0x00007f06eb6671a4 in DS_Sleep (ticks=ticks@entry=100) at ldap/servers/slapd/util.c:1060
#2  0x00007f06e792cdd9 in dbmdb_import_monitor_threads (status=<synthetic pointer>, job=0x55b828cc12e0) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import.c:561
#3  dbmdb_import_run_pass (status=<synthetic pointer>, job=0x55b828cc12e0) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import.c:649
#4  dbmdb_public_dbmdb_import_main (arg=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import.c:780
#5  0x00007f06e792e6d8 in dbmdb_run_ldif2db (pb=pb@entry=0x55b828c27990) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import.c:1188
#6  0x00007f06e792e8dd in dbmdb_ldif2db (pb=0x55b828c27990) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_ldif2db.c:250
#7  0x00007f06e78c5995 in ldbm_back_ldif2ldbm (pb=0x55b828c27990) at ldap/servers/slapd/back-ldbm/ldif2ldbm.c:147
#8  0x000055b8271ea979 in slapd_exemode_ldif2db (mcfg=0x7ffefda9c4e0) at ldap/servers/slapd/main.c:2116
#9  main (argc=8, argv=0x7ffefda9c8e8) at ldap/servers/slapd/main.c:833
111

### PR DESCRIPTION
**Pull request by progier389**
Problem:
[A] lmdb import is very slow (and threads were waiting for mdb_rdncache.
When tesdting the fix I hit several other issues that i fixed here too:
  [B] dbscan database instance removal is broken
  [C] on line import performance is 10 time slower than off line one (while the import code is the same)

Solution:
  [A} removed the mdn_rdncache code and instead let the provider thread 
      creates a temporary mdb database to store:
         ndn -> entryId ancestorIds nrdn rdn 
  and provide these records and parent entry record to the worker threads so the entryrdn index can be created.
 ==> worker threads does not needs to wait (except for getting an entry as string from provider thread or to push a write operation in the writer thread queue.)
   Also have to duplicate addentry code to add an entry without updating the entry cache (because the worker threads may try to add an entry before its parent which trigger assertion in entry cache code) 
   Have also to create a provider thread for bulk import (to create the private db), So now ldap operation worker thread push the entry to the bulk import provider thread that push it to the import worker threads that push data to the writer thread.
  [B] fixed the code and also a few dbscan related memory leaks (to avoid the noise in the asan record)
  [C] Disabled the dn.c ndn_cache during the import because it is killing the performance 

Issue: [5408](https://github.com/389ds/389-ds-base/issues/5408)

Reviewd by: @mreynolds389, @tbordaz

### CODE REVIEW

**Comment by progier389** [comment]
There is still a problem with entryrdn and tombstone: 
     tombstone entries ends up in entryrdn while it is not the case with bdb 
  but it does it is not related to this fix as the same trouble occurs without using the import/reindex/bulk import code so I will open a new issue to handle that one.

**Comment by progier389** [comment]
here are the result of dsrate runall about import rate (in entries per seconds): 
( Note I do not have yet the 1M users  result ):
But it show a tremendous improvment ( mdb import performance is now better than bdb one)

<!DOCTYPE html>

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.3.4.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


  |   | 2021 measure |   |   | Today’s measure |  
-- | -- | -- | -- | -- | -- | --
users | measure | bdb | mdb |   | bdb | mdb
1000 | import rate | 346.454390841228 | 108.928940993245 |   | 311.135397082729 | 388.115253640319
10000 | import rate | 2016.21133259499 | 170.115552133972 |   | 1787.55064258345 | 2599.23919693058
100000 | import rate | 4282.74389642868 | 1285.4795518118 |   | 3878.26124015862 | 7421.80933966913


</body>

</html>

**Review by mreynolds389 — APPROVED** [review]
LGTM   Passes ASAN and compiler tests

File: ldap/servers/slapd/dn.c [hunk 1]
```diff
@@ -2894,6 +2895,18 @@ ndn_cache_init()
     return 0;
 }
 
+void
+ndn_cache_inc_import_task()
+{
+    slapi_atomic_incr_32(&ndn_import_task_count, __ATOMIC_RELEASE);
```
Comment (tbordaz) [inline ldap/servers/slapd/dn.c:2901]: Disabling ndn cache is beneficial for online import but may impact others operations. What about logging an 'info' when it is enabled/disabled.

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c [hunk 2]
```diff
@@ -77,121 +123,256 @@ dup_data(MDB_val *to, MDB_val *from)
...
+
+
+/* typical shouldwait callback for ImportNto1Queue */
 int
-dbmdb_import_workerq_push(ImportQueue_t *q, WorkerQueueData_t *data)
+generic_shouldwait(ImportNto1Queue_t *q)
 {
-    WorkerQueueData_t *slot =NULL;
+    ImportWorkerInfo *info = q->info;
+    return (q->nbitems < q->minitems && !info_is_finished(info));
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:194]: q->minitems is initialized to 1. The only case it shouldwait is when there is no item in the queue. Is that the expected behavior ? I was thinking we shouldwait until the queue has maxitem (2000).

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c [hunk 3]
```diff
@@ -77,121 +123,256 @@ dup_data(MDB_val *to, MDB_val *from)
...
-    const char *uniqueid = slapi_entry_get_uniqueid(e);
-    int rc = UID_SUCCESS;
+    memset(info, 0, sizeof(ImportWorkerInfo));
+    info->command = PAUSE;
+    info->work_type = role;
+    info->job = job;
+    info->first_ID = job->first_ID;
+    info->next = job->worker_list;
+    job->worker_list = info;
+    snprintf(info->name, WORKER_NAME_LEN, name, idx);
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:305]: Should not info->name be freed in bdb_import_free_thread_data ?

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c [hunk 4]
```diff
@@ -2654,29 +3066,9 @@ dbmdb_import_worker(void *param)
...
-                wqelmnt->wait_id = 0;
-                continue;
-            case PEA_SKIP:
-                /* Parent entry does not exists or Invalid DN */
-                backentry_free(&ep);
-                job->skipped++;
-                wqelmnt->wait_id = 0;
-                continue;
-        }
+        process_entryrdn(ep, wqelmnt);
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:3072]: Few lines above there is 'wqelmnt->wait_id', should not need to broadcast workerq.cv as well

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c [hunk 5]
```diff
@@ -387,44 +633,323 @@ dbmdb_import_add_created_attrs(Slapi_Entry *e)
...
+    if (param->flags & EIP_RDN) {
+        memcpy(&pidfromkey, param->pkey.mv_data, sizeof (ID));
+    }
+
+    dnrc = get_entry_type(wqelmt, &param->sdn);
+    if (dnrc == DNRC_SUFFIX) {
+        if ( param->eid != 1) {
+            dnrc = DNRC_BAD_SUFFIX_ID;
+        } else {
+            rdn = slapi_sdn_get_dn(&param->sdn);
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:761]: This call returns a 'dn' not a 'rdn'. should not it call slapi_sdn_get_rdn ?

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c [hunk 6]
```diff
@@ -387,44 +633,323 @@ dbmdb_import_add_created_attrs(Slapi_Entry *e)
...
+    }
+    if (dnrc == DNRC_SUFFIX || dnrc == DNRC_OK) {
+        /* Note: If someday we needs to rebuild the entry dn, we could store it in the entry info
+         *  and build it from parent entry info + entry rdn. But as of today we do not need it.
+         */
+        len = strlen(nrdn) + strlen(rdn) + 2 + (5 + pinfo[1]) * sizeof(ID);
+        data.mv_data = wqelmt->entry_info = (ID*)slapi_ch_calloc(ALIGN_TO_ID_SLOT(len), sizeof(ID));
+        data.mv_size = len;
+        wqelmt->entry_info[0] = param->eid;
+        wqelmt->entry_info[1] = pinfo[1] + 1;
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:823]: why parentID + 1 ?

**Review by tbordaz — COMMENTED** [review]
The patch is complex and I would say I only reviewed random parts. As far as I understand it, everything I looked at was looking good.

Is there specific parts you like us to review. Rare code paths, sensitive areas... ?

**Comment by progier389** [comment]
About tbordaz's general comments: Just needing a general reviews anyway most of the code is tested through the CI when running on mdb mode. (As far As I know there are two problematic points ( tombstone and entryrdn and the atomic CAS ) but these points are handled in other issues (5490 and 5484) so IMHO we should not focus on these part in this review)

File: ldap/servers/slapd/dn.c (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/dn.c:2901]: import/reindex/bulk import task in progress are already logged, so I have the feeling that adding an info message will probably be more confusing than helpful.
IMHO the impact of disabling the dn normalize cache is minor compared to the impact of the writing thread txn
 that would likely drastically reduce the database access rate. 
(I have not tested searchrate on a backend while reindexing another backend with lmdb but I suspect that the fact that there is a single database is a killer )

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c (hunk 2 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:194]: Setting the queue minimun to maxitem is a bad idea that mean that when pushing new data some the worker thread may have to wait for the writer thread empty the queue,
 I have done some tests with intermediary values but it did not improved the performance (in fact it slightly degrade it) 
 so IMHO we should better empty the queue and push the data towards the db as fast as we can ( i.e minitems == 1 )

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c (hunk 3 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:305]: info->name is a char[WORKER_NAME_LEN] and not a malloc string

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c (hunk 5 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:761]: Short answer is no. (suffix "rdn" is the dn) :
"rdn" notion in "entryrdn" index is a bit confusing:
  although it is the rdn for standard and RUV entry 
   it is the dn for the suffix and the 2 first rdns for tombstone entries (RUV excepted)

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c (hunk 4 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:3072]: Good catch

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c (hunk 6 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:823]: parentID is pinfo[0], pinfo[1] is the number of ancestors and entry number of ancestors  is 1 + number of parent ancestors

**Comment by progier389** [comment]
Fixed thierry's remark about  'wqelmnt->wait_id',

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c (hunk 2 above)
Comment (tbordaz) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:194]: Thanks for the explanation. Do you mind to add the comment that minitems stick to 1 because tests shows it is better to write DB as soon as we have something to write.

Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:194]: That is a good idea,  but I will do it in issue 5490 (because the queue code is refactored so I would rather limits the merge conflict. )
```
@@ -209,6 +201,7 @@ dbmdb_import_q_init(ImportNto1Queue_t *q, ImportWorkerInfo *info, int maxitems)
     pthread_cond_init(&q->cv, NULL);
     q->list = NULL;
     q->maxitems = maxitems;
+    /* Setting minitems to 1 because tests showed we get better performance with this value */
     q->minitems = 1;
```
