### PR TITLE
Issue 4418 - ldif2db - offline. Warn the user of skipped entries

### LINKED ISSUE #4418: ldif2db - offline. Warn the user of skipped entries
**Issue Description**
ldif2db is used to import directory entries from an ldif file to a directory server instance. During the import operation, entries might not conform to various constraints (attribute syntax, schema violation, etc) and be skipped. On completion of the import operation the user receives a success message, with no indication of a skipped entry, apart from a message in the error logs. 

**Package Version and Platform:**
 - Platform: 5.6.6-300.fc32.x86_64
 - Package and version: 389-Directory/1.4.4.4

**Steps to Reproduce**
1. Verify syntax checking is enabled (default)
2. Generate sample ldif file
3. Modify the ldif file to violate a syntax checking rule (An empty fax number)
4. Import ldif file, notice import success message
5. Check the server error logs:
```c
ERR - slapi_entry_syntax_check - "uid=OJeleniewski1000,ou=product development,dc=example,dc=com": (facsimileTelephoneNumber) value #0 invalid per syntax
WARN - import_producer - import userroot: Skipping entry "uid=OJeleniewski1000,ou=product development,dc=example,dc=com" which violates attribute syntax,
```

**Expected results**
The user should get a warning message saying some entries were skipped and the that they should check the logs for more info.

**Additional context**
Parent bug: https://bugzilla.redhat.com/show_bug.cgi?id=1627645
ldif2db can operate in both offline and online modes, the parent bug will be divided into offline and online updates that each will require a different approach.

### PR DESCRIPTION
**Pull request by jchapma**
Bug Description: During an ldif2db import entries that do not
conform to various constraints will be skipped and not imported.
On completition of an import with skipped entries, the server
returns a success exit code and logs the skipped entry detail to
the error logs. The success exit code could lead the user to
believe that all entries were successfully imported.

Fix Description: If a skipped entry occurs during import, the
import will continue and a warning will be returned to the user.

CLI tools for offline import updated to handle warning code.

Test added to generate an incorrect ldif entry and perform an
import.

Fixes: #4418

Reviewed by: ?

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c [hunk 1]
```diff
@@ -2637,6 +2637,7 @@ bdb_back_ldif2db(Slapi_PBlock *pb)
     int total_files, i;
     int up_flags = 0;
     PRThread *thread = NULL;
+	int ret = 0;
```
Comment (Firstyear) [inline ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c]: Indenting seems off here?

File: ldap/servers/slapd/pblock.c [hunk 2]
```diff
@@ -2059,6 +2059,13 @@ slapi_pblock_get(Slapi_PBlock *pblock, int arg, void *value)
             (*(int *)value) = 0;
         }
         break;
+    case SLAPI_TASK_MISC:
```
Comment (Firstyear) [inline ldap/servers/slapd/pblock.c]: Rather than new statements in the case/switch, look around line pblock.c:4280 for individual get/set in the pblock, that are then subject to inlining in compiling. It's better for performance and clarity, as well as avoiding void casting that present type unsafety.

File: ldap/servers/slapd/pblock_v3.h [hunk 3]
```diff
@@ -68,6 +68,7 @@ typedef struct _slapi_pblock_task
     int ldif2db_noattrindexes;
     int ldif_printkey;
     int task_flags;
+    int task_misc;
```
Comment (Firstyear) [inline ldap/servers/slapd/pblock_v3.h]: When adding new types, it's worth adding them with int32_t types for example rather tahn bare int if possible. this has impacts on future rust ffi

File: src/lib389/lib389/cli_ctl/dbtasks.py [hunk 4]
```diff
@@ -44,10 +45,13 @@ def dbtasks_db2ldif(inst, log, args):
...
 def dbtasks_ldif2db(inst, log, args):
-    if not inst.ldif2db(bename=args.backend, encrypt=args.encrypted, import_file=args.ldif,
-                        suffixes=None, excludeSuffixes=None, import_cl=False):
+    ret = inst.ldif2db(bename=args.backend, encrypt=args.encrypted, import_file=args.ldif,
+                        suffixes=None, excludeSuffixes=None, import_cl=False)
+    if not ret:
         log.fatal("ldif2db failed")
         return False
+    elif ret == LDIF2DB_WARN:
+        log.info("ldif2db successful with skipped entries")
```
Comment (Firstyear) [inline src/lib389/lib389/cli_ctl/dbtasks.py]: log.warn?

File: ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c [hunk 5]
```diff
@@ -2764,7 +2765,13 @@ bdb_back_ldif2db(Slapi_PBlock *pb)
     }
 
     /* old style -- do it all synchronously (THIS IS GOING AWAY SOON) */
-    return import_main_offline((void *)job);
+	ret = import_main_offline((void *)job);
+	if(job->skipped) {
+		int warn = 2;
```
Comment (Firstyear) [inline ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c]: Rather than the assuming warn=2 here, it would be good to have a warning enum type that can be extended in the future with different warning types that could exist in the future. Enum is preferable over a #define as well because that way there is type checking that can exist over the usage of the value.

**Comment by Firstyear** [comment]
Hope the comments help! This is a really good addition for users :)

File: ldap/servers/slapd/pblock.c (hunk 2 above)
Comment (jchapma) [reply ldap/servers/slapd/pblock.c]: That makes more sense alright

File: ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c (hunk 5 above)
Comment (jchapma) [reply ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c]: Great idea

**Comment by droideck** [comment]
The test case fails for me with the next errors:

```
    ==283519==ERROR: AddressSanitizer: heap-use-after-free on address 0x613000016218 at pc 0x7f5c0550d843 bp 
    0x7fffbae9b4f0 sp 0x7fffbae9b4e0
    READ of size 4 at 0x613000016218 thread T0
    #0 0x7f5c0550d842 in bdb_back_ldif2db ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c:2771
    #1 0x7f5c054f9101 in bdb_ldif2db ldap/servers/slapd/back-ldbm/db-bdb/bdb_ldif2db.c:385
    #2 0x7f5c054a9513 in ldbm_back_ldif2ldbm ldap/servers/slapd/back-ldbm/ldif2ldbm.c:147
    #3 0x562cfdabf836 in slapd_exemode_ldif2db ldap/servers/slapd/main.c:2100
    #4 0x7f5c0c088041 in __libc_start_main (/lib64/libc.so.6+0x27041)
    #5 0x562cfdac295d in _start (/usr/sbin/ns-slapd+0x3395d)

    0x613000016218 is located 88 bytes inside of 328-byte region [0x6130000161c0,0x613000016308)
    freed by thread T0 here:
    #0 0x7f5c0c9d6307 in __interceptor_free (/lib64/libasan.so.6+0xb0307)
    #1 0x7f5c0c67ecfa in slapi_ch_free (/usr/lib64/dirsrv/libslapd.so.0+0xe3cfa)
    #2 0x7f5c05513b0b in bdb_import_main ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c:2608
    #3 0x7f5c0550d4cf in bdb_back_ldif2db ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c:2768
    #4 0x7f5c054f9101 in bdb_ldif2db ldap/servers/slapd/back-ldbm/db-bdb/bdb_ldif2db.c:385
    #5 0x7f5c054a9513 in ldbm_back_ldif2ldbm ldap/servers/slapd/back-ldbm/ldif2ldbm.c:147
    #6 0x562cfdabf836 in slapd_exemode_ldif2db ldap/servers/slapd/main.c:2100
    #7 0x7f5c0c088041 in __libc_start_main (/lib64/libc.so.6+0x27041)

    previously allocated by thread T0 here:
    #0 0x7f5c0c9d6837 in __interceptor_calloc (/lib64/libasan.so.6+0xb0837)
    #1 0x7f5c0c67e915 in slapi_ch_calloc (/usr/lib64/dirsrv/libslapd.so.0+0xe3915)
    #2 0x7f5c0550cb5a in bdb_back_ldif2db ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c:2647
    #3 0x7f5c054f9101 in bdb_ldif2db ldap/servers/slapd/back-ldbm/db-bdb/bdb_ldif2db.c:385
    #4 0x7f5c054a9513 in ldbm_back_ldif2ldbm ldap/servers/slapd/back-ldbm/ldif2ldbm.c:147
    #5 0x562cfdabf836 in slapd_exemode_ldif2db ldap/servers/slapd/main.c:2100
    #6 0x7f5c0c088041 in __libc_start_main (/lib64/libc.so.6+0x27041)

    SUMMARY: AddressSanitizer: heap-use-after-free ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c:2771 in bdb_back_ldif2db
    Shadow bytes around the buggy address:
      0x0c267fffabf0: fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
      0x0c267fffac00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
      0x0c267fffac10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
      0x0c267fffac20: 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa
      0x0c267fffac30: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
    =>0x0c267fffac40: fd fd fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd
      0x0c267fffac50: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
      0x0c267fffac60: fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
      0x0c267fffac70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
      0x0c267fffac80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
      0x0c267fffac90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    Shadow byte legend (one shadow byte represents 8 application bytes):
      Addressable:           00
      Partially addressable: 01 02 03 04 05 06 07
      Heap left redzone:       fa
      Freed heap region:       fd
      Stack left redzone:      f1
      Stack mid redzone:       f2
      Stack right redzone:     f3
      Stack after return:      f5
      Stack use after scope:   f8
      Global redzone:          f9
      Global init order:       f6
      Poisoned by user:        f7
      Container overflow:      fc
      Array cookie:            ac
      Intra object redzone:    bb
      ASan internal:           fe
      Left alloca redzone:     ca
      Right alloca redzone:    cb
      Shadow gap:              cc
    ==283519==ABORTING
    FAILED

    =================================== FAILURES ====================================
    ___________________________ test_ldif2db_syntax_check ___________________________

    topo = <lib389.topologies.TopologyMain object at 0x7f985d6bc8e0>

    def test_ldif2db_syntax_check(topo):
        """ldif2db should return a warning when a skipped entry has occured.
        :id: 85e75670-42c5-4062-9edc-7f117c97a06f
        :setup:
            1. Standalone Instance
            2. Ldif entry that violates syntax check rule (empty givenname)
        :steps:
            1. Create an ldif file which violates the syntax checking rule
            2. Stop the server and import ldif file with ldif2db
        :expected results:
            1. ldif2db import returns a warning to signify skipped entries
        """
        import_ldif1 = _create_syntax_err_ldif(topo)
        # Import the offending LDIF data - offline
        topo.standalone.stop()
        ret = topo.standalone.ldif2db('userRoot', None, None, None, import_ldif1)
    >       assert ret == SKIPDENTRY
    E       assert False == 2
    E         -False
    E         +2
```

**Comment by Firstyear** [comment]
@jchapma Have you got ASAN setup/working in your dev environment? It really useful for catching things like this that @droideck found here. If you  need any help with it, let us know.

**Comment by jchapma** [comment]
To my horror I had it disabled for some reason, it is very useful. Thanks @Firstyear, @droideck

File: ldap/servers/slapd/slapi-private.h [hunk 6]
```diff
@@ -1464,6 +1464,17 @@ void slapi_pblock_set_operation_notes(Slapi_PBlock *pb, uint32_t opnotes);
 void slapi_pblock_set_flag_operation_notes(Slapi_PBlock *pb, uint32_t opflag);
 void slapi_pblock_set_result_text_if_empty(Slapi_PBlock *pb, char *text);
 
+/* task warnings */
+typedef enum task_warning_t{
+    WRN_UPGRD_DNFMT_ALL = (1 << 0),
```
Comment (Firstyear) [inline ldap/servers/slapd/slapi-private.h]: I don't think these should be abbreviated, should be WARN_UPGRADE_DN_FORMAT etc. Helps future readers know what's going on :)

File: src/lib389/lib389/_constants.py [hunk 7]
```diff
@@ -166,6 +166,13 @@
 DB2INDEX = 'db2index'
 DBSCAN = 'dbscan'
 
+# Task warnings
+class TaskWarning:
```
Comment (Firstyear) [inline src/lib389/lib389/_constants.py]: Isn't there an enum type in python ?

**Review by Firstyear — CHANGES_REQUESTED** [review]
Just some small nitpicks left :)

File: src/lib389/lib389/_constants.py (hunk 7 above)
Comment (jchapma) [reply src/lib389/lib389/_constants.py]: There is, to make matters worse we already import it for this file.

**Comment by Firstyear** [comment]
Looks great, ack from me. Thank you!

**Comment by jchapma** [comment]
Great, thanks for the feedback.
