### PR TITLE
Issue 7172 - Index ordering mismatch after upgrade

### LINKED ISSUE #7172: Index ordering mismatch after upgrade
**Issue Description**
Commit daf731f55071d45eaf403a52b63d35f4e699ff28 introduced a regression. After upgrading to a version that adds `integerOrderingMatch` matching rule to `parentid` and `ancestorid` indexes, searches may return empty or incorrect results.

This happens because the existing index data was created with lexicographic ordering, but the new compare function expects integer ordering. Index lookups fail because the compare function doesn't match the data ordering.
The root cause is that `ldbm_instance_create_default_indexes()` calls `attr_index_config()` unconditionally for `parentid` and `ancestorid` indexes, which triggers `ainfo_dup()` to overwrite `ai_key_cmp_fn` on existing indexes. This breaks indexes that were created without the `integerOrderingMatch` matching rule.

**Package Version and Platform:**
 - Platform: Fedora/RHEL
 - Package and version: all versions containing fix https://github.com/389ds/389-ds-base/issues/6928

**Steps to Reproduce**
Steps to reproduce the behavior: https://bugzilla.redhat.com/show_bug.cgi?id=2424132#c0

**Expected results**
No index ordering mismatch after upgrade. Instructions to reindex should be provided to the user, but the server should use the existing index ordering.

### PR DESCRIPTION
**Pull request by vashirov**
Bug Description:
Commit daf731f55071d45eaf403a52b63d35f4e699ff28 introduced a regression. After upgrading to a version that adds `integerOrderingMatch` matching rule to `parentid` and `ancestorid` indexes, searches may return empty or incorrect results.

This happens because the existing index data was created with lexicographic ordering, but the new compare function expects integer ordering. Index lookups fail because the compare function doesn't match the data ordering.
The root cause is that `ldbm_instance_create_default_indexes()` calls `attr_index_config()` unconditionally for `parentid` and `ancestorid` indexes, which triggers `ainfo_dup()` to overwrite `ai_key_cmp_fn` on existing indexes. This breaks indexes that were created without the `integerOrderingMatch` matching rule.

Fix Description:
* Call `attr_index_config()` for `parentid` and `ancestorid` indexes only if index config doesn't exist.

* Add `upgrade_check_id_index_matching_rule()` that logs a warning on server startup if `parentid` or `ancestorid` indexes are missing the integerOrderingMatch matching rule, advising administrators to reindex.

Fixes: https://github.com/389ds/389-ds-base/issues/7172

## Summary by Sourcery

Guard default index initialization for parentid and ancestorid to avoid overwriting existing index configurations and add an upgrade-time check that warns administrators when these ID indexes lack the required integerOrderingMatch rule so they can reindex and prevent incorrect search results.

Bug Fixes:
- Prevent regression where existing parentid and ancestorid indexes created without integerOrderingMatch were broken by unconditional reconfiguration during default index creation, leading to incorrect or empty search results.

Enhancements:
- Add an upgrade-time check that inspects backend index definitions for parentid and ancestorid and logs guidance to reconfigure and reindex when the integerOrderingMatch matching rule is missing.

### CODE REVIEW

File: ldap/servers/slapd/upgrade.c [hunk 1]
```diff
@@ -330,6 +330,102 @@ upgrade_remove_subtree_rename(void)
...
+static upgrade_status
+upgrade_check_id_index_matching_rule(void)
+{
+    struct slapi_pblock *pb = slapi_pblock_new();
+    Slapi_Entry **backends = NULL;
+    const char *be_base_dn = "cn=ldbm database,cn=plugins,cn=config";
+    const char *be_filter = "(objectclass=nsBackendInstance)";
+    const char *attrs_to_check[] = {"parentid", "ancestorid", NULL};
+    upgrade_status uresult = UPGRADE_SUCCESS;
+
```
[the remark this answers is not in the document]
Comment (vashirov) [reply ldap/servers/slapd/upgrade.c:349]: I don't have preference here, I'm not sure if `void` is better than returning always-true `upgrade_status`.

File: ldap/servers/slapd/upgrade.c [hunk 2]
```diff
@@ -330,6 +330,102 @@ upgrade_remove_subtree_rename(void)
...
+                continue;
+            }
+
+            /* Check each attribute that should have integerOrderingMatch */
+            for (size_t attr_idx = 0; attrs_to_check[attr_idx] != NULL; attr_idx++) {
+                const char *attr_name = attrs_to_check[attr_idx];
+                struct slapi_pblock *idx_pb = slapi_pblock_new();
+                Slapi_Entry **idx_entries = NULL;
+                char *idx_dn = slapi_ch_smprintf("cn=%s,cn=index,cn=%s,%s",
+                                                  attr_name, be_name, be_base_dn);
```
[the remark this answers is not in the document]
Comment (vashirov) [reply ldap/servers/slapd/upgrade.c]: Using `slapi_dn_escape_rdn_value()` makes sense. Not sure about helper function, the code is not reused. And when it will be, then we can move it out.

File: ldap/servers/slapd/back-ldbm/instance.c [hunk 3]
```diff
@@ -248,9 +249,14 @@ ldbm_instance_create_default_indexes(backend *be)
     ldbm_instance_config_add_index_entry(inst, e, flags);
     slapi_entry_free(e);
 
+    ainfo_get(be, (char *)LDBM_PARENTID_STR, &ai);
+    index_already_configured = (ai && ai->ai_type &&
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/instance.c]: If 'ai' is returned then ai_type is equal(ainfo_type_cmp) to LDBM_PARENTID_STR. You may define index_already_configured as 'struct attrinfo *' and set it to 'ai'.

File: ldap/servers/slapd/back-ldbm/instance.c [hunk 4]
```diff
@@ -248,9 +249,14 @@ ldbm_instance_create_default_indexes(backend *be)
...
+                                strcasecmp(ai->ai_type, LDBM_PARENTID_STR) == 0);
     e = ldbm_instance_init_config_entry(LDBM_PARENTID_STR, "eq", 0, 0, 0, "integerOrderingMatch", parentid_indexes_limit);
     ldbm_instance_config_add_index_entry(inst, e, flags);
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/instance.c]: IIRC it will return 'Already exists' in case of upgrade. Correct ?

File: ldap/servers/slapd/back-ldbm/instance.c [hunk 5]
```diff
@@ -288,9 +294,14 @@ ldbm_instance_create_default_indexes(backend *be)
      * ancestorid is special, there is actually no such attr type
      * but we still want to use the attr index file APIs.
      */
+    ainfo_get(be, (char *)LDBM_ANCESTORID_STR, &ai);
+    index_already_configured = (ai && ai->ai_type &&
+                                strcasecmp(ai->ai_type, LDBM_ANCESTORID_STR) == 0);
     e = ldbm_instance_init_config_entry(LDBM_ANCESTORID_STR, "eq", 0, 0, 0, "integerOrderingMatch", ancestorid_indexes_limit);
     ldbm_instance_config_add_index_entry(inst, e, flags);
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/instance.c]: same question (already exist). Can we skip the creation if the index already configured ?

**Review by tbordaz — APPROVED** [review]
LGTM. minor comments

File: ldap/servers/slapd/back-ldbm/instance.c (hunk 3 above)
Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/instance.c]: Good idea

File: ldap/servers/slapd/back-ldbm/instance.c (hunk 4 above)
Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/instance.c]: Yes, correct

File: ldap/servers/slapd/back-ldbm/instance.c (hunk 5 above)
Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/instance.c]: Right, makes sense, I will update it

**Review by progier389 — APPROVED** [review]
LGTM

File: ldap/servers/slapd/upgrade.c [hunk 6]
```diff
@@ -330,6 +330,107 @@ upgrade_remove_subtree_rename(void)
...
+                                break;
+                            }
+                        }
+                    }
+
+                    if (!has_matching_rule) {
+                        /* Index exists but doesn't have integerOrderingMatch, log a warning */
+                        slapi_log_err(SLAPI_LOG_WARNING, "upgrade_check_id_index_matching_rule",
+                                "Index '%s' in backend '%s' is missing 'nsMatchingRule: integerOrderingMatch'. "
+                                "Without it, searches may return incorrect or empty results. "
```
Comment (droideck) [inline ldap/servers/slapd/upgrade.c]: IMO, `searches may return incorrect or empty results` is severe enough for SLAPI_LOG_ERR.

**Review by droideck — APPROVED** [review]
Minor concern, otherwise -- looks great!

File: ldap/servers/slapd/upgrade.c (hunk 6 above)
Comment (vashirov) [reply ldap/servers/slapd/upgrade.c]: Right, DSBLE0007 has High severity, so SLAPI_LOG_ERR makes sense. Regarding the message, I will adjust it. Incorrect or empty results were caused by the bug, but the reason we add matching rule in the first place is that we had replication issues. DSBLE0007 has the following text:
```
System indexes are essential for proper directory server operation. Missing or incorrectly configured system indexes can lead to poor search performance, replication issues, and other operational problems.
```
I will update the error log level and the message to be more precise.

File: ldap/servers/slapd/back-ldbm/instance.c (hunk 3 above)
Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/instance.c]: This is not applicable to ancestorid. With this change upgrade fails:

```
[10/Jan/2026:16:58:51.125433428 +0000] - WARN - dbmdb_open_dbi_from_filename - Attempt to open to open dbi userRoot/.default while txn is already pending. Usually that means that the index m
ust be reindex. Root cause is likely that last import of reindex failed or that the index was created but not yet reindexed).
[10/Jan/2026:16:58:51.136566749 +0000] - WARN - slapi_log_backtrace -   [0]     /usr/lib64/dirsrv/libslapd.so.0(+0x6d148) [0x7f08f666d148]
[10/Jan/2026:16:58:51.138643296 +0000] - WARN - slapi_log_backtrace -   [1]     /usr/lib64/dirsrv/plugins/libback-ldbm.so(dbmdb_open_dbi_from_filename+0x36a) [0x7f08f1aa084a]
[10/Jan/2026:16:58:51.140718660 +0000] - WARN - slapi_log_backtrace -   [2]     /usr/lib64/dirsrv/plugins/libback-ldbm.so(dbmdb_get_db+0xbd) [0x7f08f1aa092d]
[10/Jan/2026:16:58:51.142754470 +0000] - WARN - slapi_log_backtrace -   [3]     /usr/lib64/dirsrv/plugins/libback-ldbm.so(dblayer_get_index_file+0xb1) [0x7f08f1a23631]
[10/Jan/2026:16:58:51.144736977 +0000] - WARN - slapi_log_backtrace -   [4]     /usr/lib64/dirsrv/plugins/libback-ldbm.so(+0x125af) [0x7f08f1a255af]
[10/Jan/2026:16:58:51.146529656 +0000] - WARN - slapi_log_backtrace -   [5]     /usr/lib64/dirsrv/plugins/libback-ldbm.so(ldbm_ancestorid_index_entry+0x58) [0x7f08f1a258e8]
[10/Jan/2026:16:58:51.148453497 +0000] - WARN - slapi_log_backtrace -   [6]     /usr/lib64/dirsrv/plugins/libback-ldbm.so(index_addordel_entry+0x300) [0x7f08f1a37b10]
[10/Jan/2026:16:58:51.150377952 +0000] - WARN - slapi_log_backtrace -   [7]     /usr/lib64/dirsrv/plugins/libback-ldbm.so(ldbm_back_add+0x1358) [0x7f08f1a40db8]
[10/Jan/2026:16:58:51.152229702 +0000] - WARN - slapi_log_backtrace -   [8]     /usr/lib64/dirsrv/libslapd.so.0(+0x19d01) [0x7f08f6619d01]
[10/Jan/2026:16:58:51.154429022 +0000] - WARN - slapi_log_backtrace -   [9]     /usr/lib64/dirsrv/libslapd.so.0(do_add+0xc5b) [0x7f08f661ae1b]
[10/Jan/2026:16:58:51.156379430 +0000] - WARN - slapi_log_backtrace -   [10]    /usr/bin/ns-slapd(+0x126a7) [0x55bda84506a7]
[10/Jan/2026:16:58:51.158313600 +0000] - WARN - slapi_log_backtrace -   [11]    /lib64/libnspr4.so(+0x24d13) [0x7f08f6d29d13]
[10/Jan/2026:16:58:51.160249559 +0000] - WARN - slapi_log_backtrace -   [12]    /lib64/libc.so.6(+0x7227a) [0x7f08f647f27a]
[10/Jan/2026:16:58:51.162198811 +0000] - WARN - slapi_log_backtrace -   [13]    /lib64/libc.so.6(+0xf4d5c) [0x7f08f6501d5c]
[10/Jan/2026:16:58:51.164370735 +0000] - ERR - ldbm_ancestorid_index_update - ancestorid.c BAD 13130, err=-30798 Unexpected dbimpl error code
```

The issue is that `ainfo_get()` falls back to the LDBM_PSEUDO_ATTR_DEFAULT attrinfo. So if ancestorid doesn't exist, `ai` pointer will point to LDBM_PSEUDO_ATTR_DEFAULT, not NULL, and the ancestorid index creation is skipped.

File: ldap/servers/slapd/back-ldbm/instance.c [hunk 7]
```diff
@@ -248,10 +249,14 @@ ldbm_instance_create_default_indexes(backend *be)
...
     slapi_entry_free(e);
 
-    e = ldbm_instance_init_config_entry(LDBM_PARENTID_STR, "eq", 0, 0, 0, "integerOrderingMatch", parentid_indexes_limit);
-    ldbm_instance_config_add_index_entry(inst, e, flags);
-    attr_index_config(be, "ldbm index init", 0, e, 1, 0, NULL);
-    slapi_entry_free(e);
+    ainfo_get(be, (char *)LDBM_PARENTID_STR, &ai);
+    index_already_configured = ai;
+    if (!index_already_configured) {
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/instance.c:254]: Can ai be NULL (since LDBM_PSEUDO_ATTR_DEFAULT is  used) ?
  maybe it is worth to also test (ai->indexmask & (INDEX_EQUALITY|INDEX_RULES)) == 0 to catch the LDBM_PSEUDO_ATTR_DEFAULT

(Same comment also apply for ANCESTORID)

Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/instance.c:254]: I've added some logging for testing, ai is never NULL:
```
[12/Jan/2026:16:12:28.531007379 +0000] - INFO - ldbm_instance_config_cachememsize_set - force a minimal value 512000
[12/Jan/2026:16:12:28.535415471 +0000] - ERR - ldbm_instance_create_default_indexes - parentid check: ai=0x7f63800c9900, ai_type=parentid, ai_indexmask=0x2, has_eq_or_rules=1, index_already_configured=1
[12/Jan/2026:16:12:28.537628321 +0000] - ERR - ldbm_instance_create_default_indexes - ancestorid check: ai=0x7f63800c45e0, ai_type=.default, ai_indexmask=0x1000, has_eq_or_rules=0, index_already_configured=0
[12/Jan/2026:16:12:28.541551383 +0000] - INFO - ldbm_instance_config_cachememsize_set - force a minimal value 512000
[12/Jan/2026:16:12:28.545216873 +0000] - ERR - ldbm_instance_create_default_indexes - parentid check: ai=0x7f637cfb0ca0, ai_type=parentid, ai_indexmask=0x2, has_eq_or_rules=1, index_already_configured=1
[12/Jan/2026:16:12:28.547698630 +0000] - ERR - ldbm_instance_create_default_indexes - ancestorid check: ai=0x7f63800c4960, ai_type=.default, ai_indexmask=0x1000, has_eq_or_rules=0, index_already_configured=0
[12/Jan/2026:16:12:28.551980595 +0000] - INFO - ldbm_instance_config_cachememsize_set - force a minimal value 512000
[12/Jan/2026:16:12:28.555285648 +0000] - ERR - ldbm_instance_create_default_indexes - parentid check: ai=0x7f637cfb34e0, ai_type=parentid, ai_indexmask=0x2, has_eq_or_rules=1, index_already_configured=1
[12/Jan/2026:16:12:28.557586152 +0000] - ERR - ldbm_instance_create_default_indexes - ancestorid check: ai=0x7f637cfae620, ai_type=.default, ai_indexmask=0x1000, has_eq_or_rules=0, index_already_configured=0
```
I think checking `ai_type` is clear enough.
