### PR TITLE
Issue 6680 - instance read-only mode is broken

### LINKED ISSUE #6680: instance read-only mode is broken.
**Issue Description**
Server fails to start after turning on nsslapd-readonly=on in cn=config.

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch

**Steps to Reproduce**
1. Configure a 389-ds-base instance
2. dsconf _instance_ config replace nsslapd-readonly=on
3. dsctl _instance_ restart
4. See error: The server fails to starts and errors logs shows errors

**Expected results**
Server should be able to start without errors

**Additional context**
Triaged: https://issues.redhat.com/browse/IDMDS-4841

### PR DESCRIPTION
**Pull request by progier389**
Read only mode is broken because some plugins fails to starts as they are not able to create/updates some entries in the dse backend.
Solution is to allow interrnal operations to write in dse.backend but not modify the dse.ldif (except for the special case when trying to modify nsslapd-readonly flags (to be allowed to set/unset the readonly mode)

Issue: #6680 

Reviewed by: @droideck, @tbordaz  (thanks!)

### CODE REVIEW

File: ldap/servers/slapd/dse.c [hunk 1]
```diff
@@ -1031,6 +1031,114 @@ dse_check_for_readonly_error(Slapi_PBlock *pb, struct dse *pdse)
...
+    Slapi_Regex *re_isro = recomp("^" CONFIG_READONLY_ATTRIBUTE ":\\s+on\\s*$");
+    Slapi_Regex *re_eoe = recomp("^$");
+    bool isconfigentry = false;
+    bool isro = false;
+    FILE *fdse = NULL;
+    char line[128];
+    char *error = NULL;
+    const char *regexp = "";
+
+    if (dsename) {
```
Comment (droideck) [inline ldap/servers/slapd/dse.c]: Should this be `if (!dsename) {` - or do I miss something?

File: ldap/servers/slapd/dse.c [hunk 2]
```diff
@@ -1031,6 +1031,114 @@ dse_check_for_readonly_error(Slapi_PBlock *pb, struct dse *pdse)
...
+        slapi_log_err(SLAPI_LOG_ERR, "is_readonly_set_in_dse",
+                      "Failed to compile '%s' regular expression. Error is %s\n",
+                      regexp, error);
+    }
+    slapi_ch_free_string(&error);
+    return re;
+}
+
+/*
+ * Check if "nsslapd-readlony: on" is in cn-config in dse.ldif file
```
Comment (droideck) [inline ldap/servers/slapd/dse.c]: Typo - `readlony -> readonly` in a few places

**Review by droideck — APPROVED** [review]
Besides the minor issues, LGTM!

File: ldap/servers/slapd/dse.c (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/dse.c]: Good catch but now I wonder why the testcase is working ?

File: ldap/servers/slapd/dse.c [hunk 3]
```diff
@@ -1031,6 +1031,114 @@ dse_check_for_readonly_error(Slapi_PBlock *pb, struct dse *pdse)
...
+        return false;
+    }
+    if (!slapi_config_get_readonly()) {
+        ro = false;
+        return ro;
+    }
+    if (ro) {
+        /* read-only mode and dse is up to date ==> Do not modify it. */
+        return ro;
+    }
```
Comment (droideck) [inline ldap/servers/slapd/dse.c:1130]: I think the tests worked because we return here.
I can't recall exactly the order config init operates on the start-up, but I think it has the config read into memory at this point.

And the core part of the fix is `is_rejected_op` func.

File: dirsrvtests/tests/suites/config/regression_test.py [hunk 4]
```diff
@@ -188,3 +190,41 @@ def test_idletimeout(idletimeout_topo, dn, expected_result):
...
+    inst.config.replace(RO_ATTR, 'on')
+    inst.restart
+    assert inst.config.get_attr_val_utf8(RO_ATTR) == "on"
+    attr = 'nsslapd-errorlog-maxlogsize'
+    val = inst.config.get_attr_val_utf8(attr)
+    with pytest.raises(ldap.UNWILLING_TO_PERFORM):
+        inst.config.replace(attr, val)
+    inst.config.replace(RO_ATTR, 'off')
+    inst.restart
+    assert inst.config.get_attr_val_utf8(RO_ATTR) == "off"
```
Comment (tbordaz) [inline dirsrvtests/tests/suites/config/regression_test.py:249]: Is it missing the step 7 - update a config attribute when RO is disabled

File: ldap/servers/slapd/dse.c [hunk 5]
```diff
@@ -1031,6 +1031,114 @@ dse_check_for_readonly_error(Slapi_PBlock *pb, struct dse *pdse)
...
+
+/*
+ * Check if "nsslapd-readonly: on" is in cn-config in dse.ldif file
+ * ( If the flag is set in memory but on in the file, the file should
+ *   be written (to let dsconf able to modify the nsslapd-readonly flag)
+ */
+static bool
+is_readonly_set_in_dse(const char *dsename)
+{
+    Slapi_Regex *re_config = recomp("^dn:\\s+cn=config\\s*$");
```
Comment (tbordaz) [inline ldap/servers/slapd/dse.c:1057]: Shouldn't it match only for a line ending with 'cn=config' ?

File: ldap/servers/slapd/mapping_tree.c [hunk 6]
```diff
@@ -2058,6 +2058,82 @@ slapi_dn_write_needs_referral(Slapi_DN *target_sdn, Slapi_Entry **referral)
...
+    /* Read operations are not rejected */
+    if ((be_op_type == SLAPI_OPERATION_SEARCH) ||
+        (be_op_type == SLAPI_OPERATION_COMPARE) ||
+        (be_op_type == SLAPI_OPERATION_BIND) ||
+        (be_op_type == SLAPI_OPERATION_UNBIND)) {
+        return false;
+    }
+
+    /* Tombstone fixup are not rejected. */
+    if (operation_is_flag_set(op, OP_FLAG_TOMBSTONE_FIXUP)) {
```
Comment (tbordaz) [inline ldap/servers/slapd/mapping_tree.c:2093]: Should we also accept RUV update (OP_FLAG_REPL_RUV) ? As there are no update, RUV should not change so it is probably fine to ignore RUV.
Or it may be handle by later test that accept all internal operation.

**Review by tbordaz — APPROVED** [review]
LGTM

File: ldap/servers/slapd/mapping_tree.c (hunk 6 above)
Comment (progier389) [reply ldap/servers/slapd/mapping_tree.c:2093]: Internal op are accepted only on  dse backendthat is not replicated and has no tombstone ...
Since old code was already only checking OP_FLAG_TOMBSTONE_FIXUP, I think that your first assumption is right: no  write operation means no RUV nor tombstone change

File: ldap/servers/slapd/dse.c (hunk 3 above)
Comment (progier389) [reply ldap/servers/slapd/dse.c:1130]: The impact of the dsename bug is that _is_readonly_set_in_dse_ always returns _false_, so ro variable stays _false_ and internal operation get written in the dse.file. 
I think that the reason the testcase pass is because it does not check that dse file is not modified after the restart.
I will improve that.

File: dirsrvtests/tests/suites/config/regression_test.py (hunk 4 above)
Comment (progier389) [reply dirsrvtests/tests/suites/config/regression_test.py:249]: Sorry, I do not understand what do you mean. Could you precise ?
|Oh, I guess you meant Step 8: Try to modify another config attribute
  (That is now step 14. I will add it)

File: ldap/servers/slapd/dse.c (hunk 5 above)
Comment (progier389) [reply ldap/servers/slapd/dse.c:1057]: Matching a line ending with 'cn=config' would also work because cn=config is always the first entry that match the _ending with 'cn=config'_ condition
But since the function is searching for nsslapd-readonly in cn=config entry, doing an exact match is more logical. 
FYI: nsslapd-readonly is also an attribute of the backend config entry and we should ignore it.
