### PR TITLE
Issue 5947 - CI test_vlv_recreation_reindex fails on LMDB

### LINKED ISSUE #5947: CI test_vlv_recreation_reindex fails on LMDB
**Issue Description**
CI test [https://github.com/389ds/389-ds-base/actions/runs/6463318723/job/17546826993
](https://github.com/389ds/389-ds-base/actions/runs/6463318723/job/17546826993) fails on LMDB:

```
dirsrvtests/tests/suites/vlv/regression_test.py::test_vlv_recreation_reindex FAILED [100%]
...
        for i, (dn, entry) in enumerate(result, start=imin):
            assert i <= imax
            expected_dn = f'uid=testuser{i},ou=People,dc=example,dc=com'
            log.debug(f'found {dn} expected {expected_dn}')
>           assert dn.lower() == expected_dn.lower()
E           AssertionError: assert 'uid=testuser...xample,dc=com' == 'uid=testuser...xample,dc=com'
E             - uid=testuser4498,ou=people,dc=example,dc=com
E             ?              ^^^
E             + uid=testuser4501,ou=people,dc=example,dc=com
E             ?              ^^^

dirsrvtests/tests/suites/vlv/regression_test.py:64: AssertionError
```

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch

**Steps to Reproduce**
1. See CI (LMDB Test( vlv)) report. 

**Expected results**
Test should pass.

**Additional context**
Looks like there is a bug in the mdb vlv reindexing code

### PR DESCRIPTION
**Pull request by progier389**
There are a few problems about vlv and lmdb:
 [1] Crash while reindexing a vlv index while trying to clear the vlv cache
 [2] Crash when VLV search fails because target entry is released twice
 [3] Confusion about db interface and recno (recno is in the key rather than the data)
 [4] dbscan fails to dump vlv cache database

Fix:
  [1] Do not clear the vlv cache when having a pseudo txn (i.e: in import/reindex)
  [2] Do not release the target entry in ldbm_back_search_cleanup
  [3] Use the key to set the recno
  [4] Do not try change the "vlv db name to vlv cache name" if the name
      is already a cache name (i.e starting with ~)

Issue: #5947 

Reviewed by: @droideck (Thanks!)

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c [hunk 1]
```diff
@@ -2300,11 +2300,21 @@ int dbmdb_cursor_get_recno(dbi_cursor_t *cursor, MDB_val *dbmdb_key, MDB_val *db
...
     int rc = 0;
+    struct ldbminfo *li = (struct ldbminfo *)cursor->be->be_database->plg_private;
+    dbmdb_ctx_t *ctx = MDB_CONFIG(li);
+    dbmdb_dbi_t *dbi = &ctx->dbi_slots[mdb_cursor_dbi(cursor->cur)];
 
     rc = MDB_CURSOR_GET(cursor->cur, &curpos_key, &curpos_data, MDB_GET_CURRENT);
     if (rc != 0) {
         return rc;
     }
+    if (dbi->dbname[0] == '~') {
```
Comment (droideck) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c:2311]: Just to clarify (as I am not very proficient with this area), `'~'` is used as a special prefix for VLV purposes?

**Review by droideck — APPROVED** [review]
Besides the question, LGTM! Ans I see that tests pass.

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c:2311]: Not really surprising you do not know about it as it is specific to lmdb vlv handling.
It is used for handling the vlv index cache that keep trace of the key that are at some position in the index file
