### PR TITLE
Issue 5020 - BUG - improve clarity of posix win sync logging

### LINKED ISSUE #5020: oc_check_required in winsync due to missing sn
Previously accounts were able to sync from AD to 389-ds, but as of version 1.4.4 this appears to be erroring due to the schema check on the entries. We need to resolve this as it's blocking upgrade from 1.4.3 to 1.4.4 for a customer. 

```
[22/Nov/2021:15:07:16.139009583 +1000] - WARN - NSMMReplicationPlugin - windows sync - windows_inc_run - agmt="cn=adsync_agreement" (addc:389): Replica has no update vector. It has never been initialized.
[22/Nov/2021:15:07:19.986880094 +1000] - ERR - NSMMReplicationPlugin - windows sync - windows_tot_run - Beginning total update of replica "agmt="cn=adsync_agreement" (addc:389)".
[22/Nov/2021:15:07:20.050970626 +1000] - ERR - oc_check_required - Entry "uid=Guest,ou=ad,dc=example,dc=com" missing attribute "sn" required by object class "person"
[22/Nov/2021:15:07:20.170465918 +1000] - ERR - oc_check_required - Entry "uid=Administrator,ou=ad,dc=example,dc=com" missing attribute "sn" required by object class "person"
```

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: When a user isn't synced from AD due to missing schema,
if the user was a member of a group then posix-winsync would confusingly
report an err=32 (NO_SUCH_OBJECT) which made it "appear" significantly
worse as a problem than it was.

Fix Description: This clarifies the error message to make it easier
for an administrator to understand why this is occuring.

fixes: https://github.com/389ds/389-ds-base/issues/5020

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

File: ldap/servers/plugins/posix-winsync/posix-group-func.c [hunk 1]
```diff
@@ -88,11 +88,11 @@ getEntry(const char *udn, char **attrs)
         if (result != NULL) {
             return result; /* Must be freed */
         } else {
-            slapi_log_err(SLAPI_LOG_PLUGIN, POSIX_WINSYNC_PLUGIN_NAME,
-                          "getEntry: %s not found\n", udn);
+            slapi_log_err(SLAPI_LOG_ERR, POSIX_WINSYNC_PLUGIN_NAME,
```
Comment (tbordaz) [inline ldap/servers/plugins/posix-winsync/posix-group-func.c]: I would prefer that the caller of getEntry decides if it is an error or not (that the entry does not exist) and then logs  the appropriate message.
Like you did in getMembershipFromDownward and modGroupMembership

**Review by tbordaz — CHANGES_REQUESTED** [review]

File: ldap/servers/plugins/posix-winsync/posix-group-func.c (hunk 1 above)
Comment (Firstyear) [reply ldap/servers/plugins/posix-winsync/posix-group-func.c]: Sure, I'll tweak that.

**Comment by Firstyear** [comment]
@tbordaz Changed :)

**Review by droideck — APPROVED** [review]
Looks good!
If Thierry is okay too, then - ack:)

**Comment by Firstyear** [comment]
I'll wait for his final approval :)

**Review by tbordaz — APPROVED** [review]
Looks good to me as well. Thanks. ACK
