### PR TITLE
Issue 6933 - When deferred memberof update is enabled after the serve…

### LINKED ISSUE #6933: When deferred memberof update is enabled after the server crashed it should not launch memberof fixup task by default
**Issue Description**
At startup, the deferred memberof update thread detects if server crashed. In that case, it exists a risk that membership ('memberof') was not properly updated. So the thread launch the fixup task.
By default, it should not do so because the fixup task consume a lot of resource. The administrator should decide when the fixup task should run.

**Package Version and Platform:**
 - since 2.6

**Steps to Reproduce**
testcase provided

**Expected results**
By default a message should warn the risk of invalid membership but not launch fixup task.

### PR DESCRIPTION
**Pull request by tbordaz**
…r crashed it should not launch memberof fixup task by default

Bug description:
	When deferred memberof update is enabled, the updates of the
	group and the members is done with different TXN.
	So there is a risk that at the time of a crash the membership
	('memberof') are invalid.
	To repair this we should run a memberof fixup task.
	The problem is that this task is resource intensive and
	should be, by default, scheduled by the administrator.

Fix description:
	The fix introduces a new memberof config parameter 'launchFixup'
	that is 'off' by default.
	After a crash, when it is 'on' the server launch the fixup
	task. If it is 'off' it logs a warning.

fixes: #6933

Reviewed by:

### CODE REVIEW

File: ldap/servers/plugins/memberof/memberof.c [hunk 1]
```diff
@@ -1020,9 +1020,16 @@ deferred_thread_func(void *arg)
...
      */
     g_incr_active_threadcnt();
-    if (memberof_get_config()->need_fixup && perform_needed_fixup()) {
-        slapi_log_err(SLAPI_LOG_ALERT, MEMBEROF_PLUGIN_SUBSYSTEM,
-                      "Failure occured during global fixup task: memberof values are invalid\n");
+    if (memberof_get_config()->need_fixup) {
+        if (memberof_get_config()->launch_fixup) {
+            if (perform_needed_fixup()) {
+                slapi_log_err(SLAPI_LOG_ALERT, MEMBEROF_PLUGIN_SUBSYSTEM,
+                        "Failure occured during global fixup task: memberof values are invalid\n");
```
Comment (droideck) [inline ldap/servers/plugins/memberof/memberof.c]: It was there, still, - let's fix it:)
```suggestion
                        "Failure occurred during global fixup task: memberof values are invalid\n");
```

File: dirsrvtests/tests/suites/memberof_plugin/regression_test.py [hunk 2]
```diff
@@ -1370,40 +1378,72 @@ def test_shutdown_on_deferred_memberof(topology_st):
...
+    else:
+        delay=10
+    value = memberof.get_memberofneedfixup()
+    assert ((str(value).lower() == "yes") or (str(value).lower() == "true"))
+    assert len(errlog.match('.*It is recommended to launch memberof fixup task.*')) == 1
+
+    # Step 10. allow the server to launch the fixup task
+    inst.stop()
+    lpath = inst.ds_error_log._get_log_path()
+    os.unlink(lpath)
```
Comment (droideck) [inline dirsrvtests/tests/suites/memberof_plugin/regression_test.py]: You can just call `inst.deleteErrorLogs()` here

**Review by droideck — APPROVED** [review]
LGTM!

**Comment by tbordaz** [comment]
b7fbf086f..409cb98bd  main
a9c59e6c4..213ef284d  389-ds-base-3.0
4efa29561..672cfe6d8  389-ds-base-2.7
03059e76e..315bc5365  389-ds-base-2.6
4f5230d36..a81ec63e5  389-ds-base-2.5
3e3a8a975..e5f425f3a  389-ds-base-2.4
5545b9faa..d696fdc7e  389-ds-base-2.3
09e1b455c..6e6b4e2d9  389-ds-base-2.2
bd5c3374a..2894439ea  389-ds-base-2.1
26792b57c..9fe222ae9  389-ds-base-2.0
c22d9c2ac..ace221e12  389-ds-base-1.4.4
4dc59b5fd..72f621c56  389-ds-base-1.4.3
