### PR TITLE
Issue 4894 - IPA failure in ipa user-del --preserve

### LINKED ISSUE #4763: Attribute Uniqueness Plugin uses wrong subtree on ModRDN
**Issue Description**
When using the Attribute uniqueness plugin, restricted to one subtree, moving an object with an already existing attribute to this subtree does not raise any exceptions. It appears that the originating subtree is searched instead.

**Package Version and Platform:**
 - Platform: Containerized Fedora (tested on 33 and 34)
 - Package and version: Tested with all versions >= 2.0.2

**Steps to Reproduce**

1. Create two container objects e.g `ou=c1,dc=example,dc=com` and `ou=c2,dc=example,dc=com`
2. Create an entry for the attr-uniq plugin restricted to the `c1` subtree, restricting (for example) the mail attribute.
3. Create two objects with the same value for `mail` in `c2` (this should be allowed).
4. Move one object to `c1`
5. Move the second object to `c1`. This should raise an exeption as another object with the same value for `mail` already exists in `c1` but works without issues.
6. Additionally, trying to move one of these objects back to `c2` raises an exception even though there is no uniqueness constraint on `c2`.

**Expected results**
The attr-uniq plugin should prevent invalid move operations.

**Additional context**
I've tried to get to the root cause of this issue, and debug logs suggest that https://github.com/389ds/389-ds-base/blob/master/ldap/servers/plugins/uiduniq/uid.c#L1395 is called with the old `parentDN`. However, as this is my first time digging through the codebase I was unable to figure out why this happens.

### PR DESCRIPTION
**Pull request by droideck**
Bug Description: Starting with 389-ds 2.0.8 on rawhide,
any call to ipa user-del --preserve fails with
This entry already exists.

Fix Description: We should split 'dn' parameter in searchAllSubtrees
into parent and target. As one of them is used for excluding the
subtree checks and another one for searching.

Fixes: https://github.com/389ds/389-ds-base/issues/4763

Reviewed by: ?

### CODE REVIEW

File: ldap/servers/plugins/uiduniq/uid.c [hunk 1]
```diff
@@ -1219,7 +1219,7 @@ preop_modify(Slapi_PBlock *pb)
         } else {
             /* Subtrees listed on invocation line */
             result = searchAllSubtrees(config->subtrees, config->exclude_subtrees, attrNames, NULL,
-                                       mod->mod_bvalues, requiredObjectClass, sdn, config->unique_in_all_subtrees);
+                                       mod->mod_bvalues, requiredObjectClass, sdn, sdn, config->unique_in_all_subtrees);
```
Comment (Firstyear) [inline ldap/servers/plugins/uiduniq/uid.c]: It may be worth renaming sdn here to clarify what's going on to prevent future confusiong :)

File: ldap/servers/plugins/uiduniq/uid.c [hunk 2]
```diff
@@ -793,7 +793,7 @@ searchAllSubtrees(Slapi_DN **subtrees, Slapi_DN **exclude_subtrees, const char *
            * violate constraint
            */
         for (i = 0; subtrees && subtrees[i]; i++) {
-            if (slapi_sdn_issuffix(dn, subtrees[i])) {
+            if (slapi_sdn_issuffix(parentDN, subtrees[i])) {
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: Is this change required for the fix ?
If I am not wrong I think that in the case that target DN (destination entry) is one of the subtrees, then testing the parent will result in_a_subtree=False, although it should be True.

It is a corner case but may be valuable if the moved entry is the head of a complete subtree.

File: ldap/servers/plugins/uiduniq/uid.c [hunk 3]
```diff
@@ -808,7 +808,7 @@ searchAllSubtrees(Slapi_DN **subtrees, Slapi_DN **exclude_subtrees, const char *
     if (exclude_subtrees != NULL) {
         PRBool in_a_subtree = PR_FALSE;
         for (i = 0; exclude_subtrees && exclude_subtrees[i]; i++) {
-            if (slapi_sdn_issuffix(dn, exclude_subtrees[i])) {
+            if (slapi_sdn_issuffix(parentDN, exclude_subtrees[i])) {
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: Same as above.

File: ldap/servers/plugins/uiduniq/uid.c [hunk 4]
```diff
@@ -828,8 +828,8 @@ searchAllSubtrees(Slapi_DN **subtrees, Slapi_DN **exclude_subtrees, const char *
      * The DN should already be normalized, so we don't have to
      * worry about that here.
      */
-        if (unique_in_all_subtrees || slapi_sdn_issuffix(dn, sufdn)) {
-            result = search(sufdn, attrNames, attr, values, requiredObjectClass, dn, exclude_subtrees);
+        if (unique_in_all_subtrees || slapi_sdn_issuffix(parentDN, sufdn)) {
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: same as above.

File: ldap/servers/plugins/uiduniq/uid.c [hunk 5]
```diff
@@ -1392,13 +1392,13 @@ preop_modrdn(Slapi_PBlock *pb)
              */
             if (NULL != markerObjectClass) {
                 /* Subtree defined by location of marker object class */
-                result = findSubtreeAndSearch(slapi_entry_get_sdn(e), attrNames, attr, NULL,
-                                              requiredObjectClass, superior,
+                result = findSubtreeAndSearch(superior, attrNames, attr, NULL,
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: Regarding this regression, is it the path that was failing ?

File: ldap/servers/plugins/uiduniq/uid.c (hunk 2 above)
Comment (droideck) [reply ldap/servers/plugins/uiduniq/uid.c]: Okay, I think I should rename it all as it brings a lot of confusion. :)

It's actually sourceDN and destinationDN. So for modrdn we should use destinationDN for any plugin checks as it's where we should apply the policies.
And sourceDN should be used for ignoring in the 'search()' function.

File: ldap/servers/plugins/uiduniq/uid.c (hunk 1 above)
Comment (droideck) [reply ldap/servers/plugins/uiduniq/uid.c]: Sure, thanks!

File: ldap/servers/plugins/uiduniq/uid.c (hunk 5 above)
Comment (droideck) [reply ldap/servers/plugins/uiduniq/uid.c]: Nope, this path was okay but I've decided to clear the things up a bit (so it uses the same logic as searchAllSubtrees, and we have one call less in the execution)

**Comment by Firstyear** [comment]
Looks a lot better mate :) ack from me, I'll leave @tbordaz to give his comments too.

File: ldap/servers/plugins/uiduniq/uid.c [hunk 6]
```diff
@@ -770,13 +770,13 @@ search_one_berval(Slapi_DN *baseDN, const char **attrNames, const struct berval
  *
  * Return:
  *   LDAP_SUCCESS - no matches, or the attribute matches the
- *     target dn.
+ *     destination (target) dn.
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: Sorry but I  am confused. With a MODRDN we have a  "sourceDN -> destinationDN". In my mind "target" is meaning SLAPI_<op>_TARGET_SDN, that is "sourceSDN". IIUC target is souce not destination.

File: ldap/servers/plugins/uiduniq/uid.c [hunk 7]
```diff
@@ -788,12 +788,12 @@ searchAllSubtrees(Slapi_DN **subtrees, Slapi_DN **exclude_subtrees, const char *
            * are unique in all the monitored subtrees
            */
 
-        /* First check the target entry is in one of
+        /* First check the source entry is in one of
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: So it would be 'destination'

File: ldap/servers/plugins/uiduniq/uid.c [hunk 8]
```diff
@@ -788,12 +788,12 @@ searchAllSubtrees(Slapi_DN **subtrees, Slapi_DN **exclude_subtrees, const char *
...
            * the monitored subtree, so adding 'values' would
            * violate constraint
            */
         for (i = 0; subtrees && subtrees[i]; i++) {
-            if (slapi_sdn_issuffix(dn, subtrees[i])) {
+            if (slapi_sdn_issuffix(sourceSDN, subtrees[i])) {
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: Here we should rather check if the destinationSDN lands into one of the monitored subtrees.

File: ldap/servers/plugins/uiduniq/uid.c [hunk 9]
```diff
@@ -808,7 +808,7 @@ searchAllSubtrees(Slapi_DN **subtrees, Slapi_DN **exclude_subtrees, const char *
     if (exclude_subtrees != NULL) {
         PRBool in_a_subtree = PR_FALSE;
         for (i = 0; exclude_subtrees && exclude_subtrees[i]; i++) {
-            if (slapi_sdn_issuffix(dn, exclude_subtrees[i])) {
+            if (slapi_sdn_issuffix(sourceSDN, exclude_subtrees[i])) {
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: Here we should check if the destinationSDN lands into a not monitored subtree

File: ldap/servers/plugins/uiduniq/uid.c [hunk 10]
```diff
@@ -820,16 +820,16 @@ searchAllSubtrees(Slapi_DN **subtrees, Slapi_DN **exclude_subtrees, const char *
...
    */
     for (i = 0; subtrees && subtrees[i]; i++) {
         Slapi_DN *sufdn = subtrees[i];
         /*
      * The DN should already be normalized, so we don't have to
      * worry about that here.
      */
-        if (unique_in_all_subtrees || slapi_sdn_issuffix(dn, sufdn)) {
-            result = search(sufdn, attrNames, attr, values, requiredObjectClass, dn, exclude_subtrees);
+        if (unique_in_all_subtrees || slapi_sdn_issuffix(sourceSDN, sufdn)) {
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: No, we should check that subtree if the destinationSDN lands into that monitored sufdn

File: ldap/servers/plugins/uiduniq/uid.c [hunk 11]
```diff
@@ -820,16 +820,16 @@ searchAllSubtrees(Slapi_DN **subtrees, Slapi_DN **exclude_subtrees, const char *
 
     /*
    * For each DN in the managed list, do uniqueness checking if
-   * the target DN is a subnode in the tree.
+   * the destination (target) DN is a subnode in the tree.
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c:823]: I agree it is destination but the word 'target' is IMHO confusing.

File: ldap/servers/plugins/uiduniq/uid.c [hunk 12]
```diff
@@ -903,20 +903,20 @@ getArguments(Slapi_PBlock *pb, char **attrName, char **markerObjectClass, char *
  *
  * Return:
  *   LDAP_SUCCESS - no matches, or the attribute matches the
- *     target dn.
+ *     destination (target) dn.
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: idem

File: ldap/servers/plugins/uiduniq/uid.c [hunk 13]
```diff
@@ -925,7 +925,7 @@ findSubtreeAndSearch(Slapi_DN *parentDN, const char **attrNames, Slapi_Attr *att
            * to have the attribute already.
            */
             result = search(curpar, attrNames, attr, values, requiredObjectClass,
-                            target, excludes);
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c:928]: This is something that I do not understand. uiduniqness should check if the uid value already exist in the parent of the destinationSDN, not in the parent of the sourceSDN.
IMHO it should be slapi_sdn_get_parent(destinationSDN, curpar);

File: ldap/servers/plugins/uiduniq/uid.c [hunk 14]
```diff
@@ -1271,8 +1271,8 @@ preop_modrdn(Slapi_PBlock *pb)
     int err;
     char *markerObjectClass = NULL;
     char *requiredObjectClass = NULL;
-    Slapi_DN *sdn = NULL;
-    Slapi_DN *superior;
+    Slapi_DN *sourceSDN = NULL;
+    Slapi_DN *superiorSDN;
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: I prefer destinationSDN rather than superiorSDN

File: ldap/servers/plugins/uiduniq/uid.c [hunk 15]
```diff
@@ -1311,26 +1311,26 @@ preop_modrdn(Slapi_PBlock *pb)
...
     /*
      * No superior means the entry is just renamed at
-     * its current level in the tree.  Use the target DN for
+     * its current level in the tree.  Use the source SDN for
      * determining which managed tree this belongs to
      */
-    if (!superior)
-        superior = sdn;
+    if (!superiorSDN)
+        superiorSDN = sourceSDN;
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: superiorSDN being SLAPI_MODRDN_NEWSUPERIOR_SDN, if it is NULL shouldn't it be initialized with slapi_sdn_get_parent(sourceSDN, superiorSDN) ?

File: ldap/servers/plugins/uiduniq/uid.c [hunk 16]
```diff
@@ -1392,13 +1392,13 @@ preop_modrdn(Slapi_PBlock *pb)
              */
             if (NULL != markerObjectClass) {
                 /* Subtree defined by location of marker object class */
-                result = findSubtreeAndSearch(slapi_entry_get_sdn(e), attrNames, attr, NULL,
-                                              requiredObjectClass, superior,
+                result = findSubtreeAndSearch(superiorSDN, attrNames, attr, NULL,
+                                              requiredObjectClass, sourceSDN,
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c:1396]: Instead of sourceSDN, shouldn't it be <rdn>,<superiorSDN> ?

File: ldap/servers/plugins/uiduniq/uid.c [hunk 17]
```diff
@@ -1392,13 +1392,13 @@ preop_modrdn(Slapi_PBlock *pb)
...
                                               markerObjectClass, config->exclude_subtrees);
             } else {
                 /* Subtrees listed on invocation line */
                 result = searchAllSubtrees(config->subtrees, config->exclude_subtrees, attrNames, attr, NULL,
-                                           requiredObjectClass, superior, config->unique_in_all_subtrees);
+                                           requiredObjectClass, superiorSDN, sourceSDN, config->unique_in_all_subtrees);
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c]: Interface is searchAllSubtrees(.., source, destination,..), shouldn't it be searchAllSubtrees(..., sourceSDN, "<rdn>,<superiorSDN>",... )

**Review by tbordaz — COMMENTED** [review]
@droideck thanks for the changes it is much clearer now.
Sorry to be pernickety but it remains things not clear to me and even wondering if there were not others hidden old bugs in that code

File: ldap/servers/plugins/uiduniq/uid.c (hunk 11 above)
Comment (droideck) [reply ldap/servers/plugins/uiduniq/uid.c:823]: searchAllSubtrees is also used for modify and add, and it uses targetSDN parameter. So I left it here for people who will read this function after preop_modify or preop_add, so they can easily understand (and not being confused by "destination")

File: ldap/servers/plugins/uiduniq/uid.c (hunk 15 above)
Comment (droideck) [reply ldap/servers/plugins/uiduniq/uid.c]: Later in the code, we use superiorSDN and construct the entry out of there. And slapi_sdn_get_parent is also used later.
We'll need to refactor a lot if we change it here...

File: ldap/servers/plugins/uiduniq/uid.c (hunk 16 above)
Comment (droideck) [reply ldap/servers/plugins/uiduniq/uid.c:1396]: Why? We need sourceSDN so we can ignore it in the results.

File: ldap/servers/plugins/uiduniq/uid.c (hunk 17 above)
Comment (droideck) [reply ldap/servers/plugins/uiduniq/uid.c]: Same as above. We need sourceSDN so we can ignore it in the results.

File: ldap/servers/plugins/uiduniq/uid.c (hunk 15 above)
Comment (tbordaz) [reply ldap/servers/plugins/uiduniq/uid.c]: Where later ?
Do you mean when it is used in slapi_entry_rename(e, rdn, deloldrdn, destinationSDN) ?

File: ldap/servers/plugins/uiduniq/uid.c (hunk 16 above)
Comment (tbordaz) [reply ldap/servers/plugins/uiduniq/uid.c:1396]: Your change looks valid to me, using destinationSDN and sourceSDN

File: ldap/servers/plugins/uiduniq/uid.c (hunk 17 above)
Comment (tbordaz) [reply ldap/servers/plugins/uiduniq/uid.c]: Your change looks valid to me, using destinationSDN and sourceSDN

File: ldap/servers/plugins/uiduniq/uid.c (hunk 15 above)
Comment (tbordaz) [reply ldap/servers/plugins/uiduniq/uid.c]: For me it is the last thing I do not understand. Unless I am mistaken, the forth param of slapi_entry_rename should be the parent of the destination entry and not the destination entry itself.

File: ldap/servers/plugins/uiduniq/uid.c [hunk 18]
```diff
@@ -1364,7 +1364,7 @@ preop_modrdn(Slapi_PBlock *pb)
 
     /* Apply the rename operation to the dummy entry. */
     /* slapi_entry_rename does not expect rdn normalized */
-    err = slapi_entry_rename(e, rdn, deloldrdn, superior);
+    err = slapi_entry_rename(e, rdn, deloldrdn, destinationSDN);
```
Comment (tbordaz) [inline ldap/servers/plugins/uiduniq/uid.c:1367]: This is the last thing that I do not understand. 
Initially it was called with 'superior'. It made sens as the fourth param is expected to be the parent of the destination entry.
But now, if SLAPI_MODRDN_NEWSUPERIOR_SDN is NULL (case an entry is just renamed not moved), then destinationSDN takes the value of sourceSDN. It should take the value of the parent of sourceDN.

**Review by tbordaz — COMMENTED** [review]
Thank you sooo much for all your changes. It makes the code much more simple to read IMHO.

**Comment by droideck** [comment]
Okay, I see your point. And I think you found one more bug in the previously existent code.
Now it's fixed! Please, review :)

And thank you so much for the thorough review as usual!

**Review by tbordaz — APPROVED** [review]
Thanks @droideck for all that cleanup in addition to the orginal fix. The code is good to me. ACK
