### PR TITLE
Issue 6553 - Update concread to 0.5.4 and refactor statistics tracking

### LINKED ISSUE #6553: Increased memory consumption caused by NDN cache
**Issue Description**

During online export, an increased memory consumption is observed. This is especially noticable with larger databases (1+ millions of entries), where database doesn't fully fit in memory, and during the export OOM-killer is invoked, killing the server.

I bisected the change that introduced the issue to https://github.com/389ds/389-ds-base/issues/4410.
If NDN cache is turned off during the export (`dsconf localhost config replace nsslapd-ndn-cache-enabled=off`), there is no increased memory consumption. Memory stays under 1.4GB, while with NDN cache it grows continiously. 

ASAN build doesn't show any leaks, but crashes with panic somewhere in concread code, when the export is done twice:
```
Jan 25 10:56:39 ns-slapd[444223]: [25/Jan/2025:10:56:39.595584783 -0500] - INFO - export_one_entry - export secauthority: Processed 42000 entries (3%).
Jan 25 10:56:39 ns-slapd[444223]: thread '<unnamed>' panicked at /root/ds/rpmbuild/BUILD/389-ds-base-1.4.3.39.20250125gitd0d980098/vendor/concread/src/arcache/mod.rs:1353:17:
Jan 25 10:56:39 ns-slapd[444223]: assertion failed: inner.ghost_rec.len() >= freq_to_len
Jan 25 10:56:39 ns-slapd[444223]: stack backtrace:
Jan 25 10:56:40 ns-slapd[444223]:    0: rust_begin_unwind
Jan 25 10:56:40 ns-slapd[444223]:              at /builddir/build/BUILD/rustc-1.79.0-src/library/std/src/panicking.rs:652:5
Jan 25 10:56:40 ns-slapd[444223]:    1: core::panicking::panic_fmt
Jan 25 10:56:40 ns-slapd[444223]:              at /builddir/build/BUILD/rustc-1.79.0-src/library/core/src/panicking.rs:72:14
Jan 25 10:56:40 ns-slapd[444223]:    2: core::panicking::panic
Jan 25 10:56:40 ns-slapd[444223]:              at /builddir/build/BUILD/rustc-1.79.0-src/library/core/src/panicking.rs:146:5
Jan 25 10:56:41 ns-slapd[444223]:    3: concread::arcache::ARCache<K,V>::evict
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/vendor/concread/src/arcache/mod.rs:474:9
Jan 25 10:56:41 ns-slapd[444223]:    4: concread::arcache::ARCache<K,V>::commit
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/vendor/concread/src/arcache/mod.rs:1457:9
Jan 25 10:56:41 ns-slapd[444223]:    5: concread::arcache::ARCacheWriteTxn<K,V>::commit
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/vendor/concread/src/arcache/mod.rs:1506:9
Jan 25 10:56:41 ns-slapd[444223]:    6: concread::arcache::ARCache<K,V>::try_quiesce
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/vendor/concread/src/arcache/mod.rs:796:13
Jan 25 10:56:41 ns-slapd[444223]:    7: <concread::arcache::ARCacheReadTxn<K,V> as core::ops::drop::Drop>::drop
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/vendor/concread/src/arcache/mod.rs:1929:9
Jan 25 10:56:41 ns-slapd[444223]:    8: core::ptr::drop_in_place<concread::arcache::ARCacheReadTxn<alloc::ffi::c_str::CString,alloc::ffi::c_str::CString>>
Jan 25 10:56:41 ns-slapd[444223]:              at /builddir/build/BUILD/rustc-1.79.0-src/library/core/src/ptr/mod.rs:514:1
Jan 25 10:56:41 ns-slapd[444223]:    9: core::ptr::drop_in_place<rslapd::cache::ARCacheCharRead>
Jan 25 10:56:41 ns-slapd[444223]:              at /builddir/build/BUILD/rustc-1.79.0-src/library/core/src/ptr/mod.rs:514:1
Jan 25 10:56:41 ns-slapd[444223]:   10: core::ptr::drop_in_place<alloc::boxed::Box<rslapd::cache::ARCacheCharRead>>
Jan 25 10:56:41 ns-slapd[444223]:              at /builddir/build/BUILD/rustc-1.79.0-src/library/core/src/ptr/mod.rs:514:1
Jan 25 10:56:41 ns-slapd[444223]:   11: cache_char_read_complete
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/src/librslapd/src/cache.rs:92:5
Jan 25 10:56:41 ns-slapd[444223]:   12: ndn_cache_add
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/ldap/servers/slapd/dn.c:3192:5
Jan 25 10:56:41 ns-slapd[444223]:   13: slapi_dn_normalize_ext
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/ldap/servers/slapd/dn.c:1186:13
Jan 25 10:56:41 ns-slapd[444223]:   14: slapi_sdn_get_dn
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/ldap/servers/slapd/dn.c:2374:18
Jan 25 10:56:41 ns-slapd[444223]:   15: slapi_sdn_get_ndn_len
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/ldap/servers/slapd/dn.c:2590:11
Jan 25 10:56:41 ns-slapd[444223]:   16: slapi_sdn_get_size
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/ldap/servers/slapd/dn.c:2751:11
Jan 25 10:56:41 ns-slapd[444223]:   17: backdn_init
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/ldap/servers/slapd/back-ldbm/backentry.c:127:20
Jan 25 10:56:41 ns-slapd[444223]:   18: bdb_db2ldif
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/ldap/servers/slapd/back-ldbm/db-bdb/bdb_ldif2db.c:1222:27
Jan 25 10:56:41 ns-slapd[444223]:   19: ldbm_back_ldbm2ldif
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/ldap/servers/slapd/back-ldbm/ldif2ldbm.c:198:12
Jan 25 10:56:41 ns-slapd[444223]:   20: task_export_thread
Jan 25 10:56:41 ns-slapd[444223]:              at /usr/src/debug/389-ds-base-1.4.3.39-20250125gitd0d980098.el8.x86_64/ldap/servers/slapd/task.c:1189:32
Jan 25 10:56:41 ns-slapd[444223]:   21: <unknown>
Jan 25 10:56:41 ns-slapd[444223]:   22: start_thread
Jan 25 10:56:42 ns-slapd[444223]:   23: __clone
Jan 25 10:56:42 ns-slapd[444223]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Jan 25 10:56:42 ns-slapd[444223]: fatal runtime error: failed to initiate panic, error 5
```

This applies to all versions after 1.4.3.32+.

### PR DESCRIPTION
**Pull request by droideck**
Description: Implement new cache statistics tracking with atomic counters
and dedicated stats structs.
Update concread dependency to 0.5.4 for improved cache performance.
Add tests for cache statistics functionality.

Fixes: https://github.com/389ds/389-ds-base/issues/6553

Reviewed by: ?

### CODE REVIEW

**Comment by droideck** [comment]
@Firstyear hi! Could you please take a look at the PR, as I'm not sure how to get:
`include, modify, evict_from_recent, and evict_from_frequent` working...

I've tried to implement the stats for them here, but I think I missed something, as I don't see them in the result stats.

Also, note that I created `CacheStats` for read_stats tracking because they are not collected from cache when I call `read_stats -> finish` in `cache_char_stats`. But I get a singular increase from the actual read transaction, so there is a way.:)

File: src/librslapd/src/cache.rs [hunk 1]
```diff
@@ -78,17 +238,29 @@ pub extern "C" fn cache_char_read_begin(cache: *mut ARCacheChar) -> *mut ARCache
...
 }
 
 #[no_mangle]
 pub extern "C" fn cache_char_read_complete(read_txn: *mut ARCacheCharRead) {
     debug_assert!(!read_txn.is_null());
+
     unsafe {
-        let _drop = Box::from_raw(read_txn);
+        let read_txn_box = Box::from_raw(read_txn);
+        read_txn_box.cache.inner.try_quiesce();
```
Comment (Firstyear) [inline src/librslapd/src/cache.rs]: you need to do try_quiesce_stats(); and you need to do it *after* you call .finish.

**Comment by Firstyear** [comment]
> @Firstyear hi! Could you please take a look at the PR, as I'm not sure how to get: `include, modify, evict_from_recent, and evict_from_frequent` working...
> 
> I've tried to `impl<K> ARCacheWriteStat<K> for` them here, but I think I missed something, as I don't see them in the result stats.
> 
> Also, note that I created `CacheStats` for read_stats tracking because they are not collected from cache when I call `read_stats -> finish` in `cache_char_stats`. But I get a singular increase from the actual read transaction, so there is a way.:)

I think you may be misunderstanding how the stats api is working.

The stats struct you pass in is just triggered on those *events*. The cache itself *tracks nothing*. You need to track all the state and values. 

So this:  https://github.com/389ds/389-ds-base/pull/6607/files#diff-3292c7c1da4d212ee8ca277908c4b63bdd14216f92e4ea623782cd3f65fadad4R224 does *nothing* because between the start of the txn to the commit you never read or write from the txn, so the stats shows zero - because nothing was done during the transaction!!!!

You actually need to be putting in a stats tracker https://github.com/389ds/389-ds-base/pull/6607/files#diff-3292c7c1da4d212ee8ca277908c4b63bdd14216f92e4ea623782cd3f65fadad4R257 and then using that to adjust your hit/load amounts as they change. Because the quiesce step is where the read transaction inclusions/evictions are actually triggered. 

PS: Your cache stats don't actually need to be a struct of Atomics, you can make it a Struct inside a CowCell and then when someone wants to view the stats you read it, when a thread wants to update you take a write on the cow cell. That way it never blocks anything.

**Comment by Firstyear** [comment]
> > So this: https://github.com/389ds/389-ds-base/pull/6607/files#diff-3292c7c1da4d212ee8ca277908c4b63bdd14216f92e4ea623782cd3f65fadad4R224 does _nothing_ because between the start of the txn to the commit you never read or write from the txn, so the stats shows zero - because nothing was done during the transaction!!!!
> 
> Sure, I totally understand the last part. I see, though, that during w_txn.,commit, we can get some stats that are valid through the whole cache's lifetime:
> 
> ```rust
>         stats.p_weight(inner.p as u64);
>         stats.shared_max(shared.max as u64);
>         stats.freq(inner.freq.len() as u64);
>         stats.recent(inner.rec.len() as u64);
>         stats.all_seen_keys(cache.len() as u64);
> ```

Still not correct - those are the current value of those stats at *this exact point in time*. They are not lifetime stats. You need to stop thinking that these values exist and are stored and tracked but the arcache, they aren't, you need to store them. The arcache doesn't track any statistics at all, the whole point of the stats api is to let you build something that tracks the values you are interested in. 

For example, between the first write txn and the second, the p_weight can move up, down, or stay the same. We don't tell you which way it went. All we do is tell you "this is the p_weight at this point in time". The same with freq/rec lengths, these values move both up and down. and "all seen keys" will either go up or stay the same, but we don't tell you the difference, just the value as it exists right now. You need to calculate the difference between the previous write txn and this write txn. 

For example if the p_weight moves down, that indicates pressure on the recent side of the cache, which causes the frequent side to be evicted. So you can use this api to work out "oh P weight has dropped by 10% of shared max, there must be pressure". But that requires you to check the p value between the first txn and the second, then to calculate that difference and ratio to shared max between both values, and make that assessment. We don't do that for you, we just show you the values at those points in time. 

Does that make more sense? 

> 
> IIUC, it's safe to get them only on the `cache_char_stats` call, as getting them each time we do a write txn's commit will be overkill. Right?

No, you have to do it each write txn commit. As mentioned the values are *not* lifetime stats, they are the exact values at *this* point in time, and you need to track those events yourself, including calculating the differences as those values at those points in time change. 

Cache_char_stats should do nothing except return the current value of stats *you* have been tracking.

Each time you call .commit or .finish, you need to update those stats, else your values will not be correct. 


> 
> Please, review! And thank you for your help with the developing concread understanding. I really appreciate that!

concread is a "fun one" because you have to think concurrently, about everything happening all at once. It can be tricky, but it's worth it. 

You can tihnk of a cowcell as a rwlock btw, where read/writes never block (unlike a rwlock).

**Comment by tbordaz** [comment]
@Firstyear , reading your explanations my understanding is that Cache_char_stats will get sample of values. The values are valid but there may be small/significant variations between the two samples. Am I correct ?
If we want to compute a hit ratio (or eviction rate) during a specific testcase should we increase the sampling frequency ? Can intensive sampling  impact the cache efficiency itself ?

**Comment by droideck** [comment]
@Firstyear Okay... Following your guidance, I've updated the code to collect stats from both `try_quiesce_stats` and read transaction `.finish()` results. And I've added a call for `cache_char_write_commit` even though we don't use it.

Another thing.
Interestingly, I've tried to remove stats collection and set `set_reader_quiesce(true)`, -> I saw a 10% performance improvement (I tested on a large export task).
So what I think, we could either:
1. Follow @tbordaz's suggestion to limit quiesce frequency (I'm afraid, though, it can affect the cache validity)
2. Make NDN cache stats collection optional via a config setting (could be a separate ticket)

BTW, I'm also seeing concerning memory behavior that needs investigation. With NDN cache enabled, memory usage grows significantly during exports and isn't freed afterward (unless we restart, of course). With NDN cache **disabled**, memory usage stays normal. ASAN shows no issues. Also, I've checked if all write and read transactions are freed on the 389 DS side, and all is good (I counted new and closed txns and the numbers where equal after the massive online export).

This suggests either a concread internal issue or misuse on our part. My current thoughts:
- Could unlimited ghost set growth be the culprit? Is there an automatic ghost-cleaning mechanism, or should we call something with a `clean` flag somewhere?

Would appreciate any insights on the memory growth issue, but I'll keep investigating regardless...

**Comment by Firstyear** [comment]
> @Firstyear Okay... Following your guidance, I've updated the code to collect stats from both `try_quiesce_stats` and read transaction `.finish()` results. And I've added a call for `cache_char_write_commit` even though we don't use it.
> 
> Another thing. Interestingly, I've tried to remove stats collection and set `set_reader_quiesce(true)`, -> I saw a 10% performance improvement (I tested on a large export task). So what I think, we could either:
> 
>     1. Follow @tbordaz's suggestion to limit quiesce frequency (I'm afraid, though, it can affect the cache validity)

Collect, if you don't quiesce then new cache items will never actually be included or accessible, you need to try_quiesce after any read op. 

Consider reading https://github.com/kanidm/concread/blob/master/CACHE.md to understand why. The inclusion and tracking queues are bounded by the way, so they can only "buffer" so much. 

> 
>     2. Make NDN cache stats collection optional via a config setting (could be a separate ticket)

Yeah, that sounds optional and better done later. 

> 
> 
> BTW, I'm also seeing concerning memory behavior that needs investigation. With NDN cache enabled, memory usage grows significantly during exports and isn't freed afterward (unless we restart, of course). With NDN cache **disabled**, memory usage stays normal. ASAN shows no issues. Also, I've checked if all write and read transactions are freed on the 389 DS side, and all is good (I counted new and closed txns and the numbers where equal after the massive online export).
> 
> This suggests either a concread internal issue or misuse on our part. My current thoughts:
> 
>     * Could unlimited ghost set growth be the culprit? Is there an automatic ghost-cleaning mechanism, or should we call something with a `clean` flag somewhere?
> 
> Would appreciate any insights on the memory growth issue, but I'll keep investigating regardless...

https://github.com/kanidm/concread/?tab=readme-ov-file#what-is-concurrently-readable

"This is a space-time trade off, using more memory to achieve better parallel behaviour."

Which is what you are seeing here. We have to keep the ghost lists to track *time* as well, because we need to be able to order cache events based on time too. 

We *could* investigate ways to trim the ghost lists more effectively based on epochs or similar. But yes, this is the trade of concread, you gain by having non-blocking parallel operations, but you are paying by using more ram. 

Realistically, the cache will grow to some X point, and then plateau because the ghost lists then settle. The amount in them shouldn't be so huge that it's a problem, and if it is then perhaps expanding the cache is worth more. This is why you could consider looking at the ghost lists as a stat to collect too. 

Anyway, I've opened https://github.com/kanidm/concread/issues/128 which I'll work on today for you.

**Review by Firstyear — APPROVED** [review]
Outside of the changes I need to make in concread, looks good.

**Comment by Firstyear** [comment]
@droideck https://github.com/kanidm/concread/pull/129 is done, will merge and release today. Should just be a version bump to 5.4 over 5.3 for you.

**Comment by Firstyear** [comment]
@droideck 5.4 is out, give it a try :)

**Comment by droideck** [comment]
> @droideck 5.4 is out, give it a try :)

Much better! The instance used only 5% or my machine's memory during the huge export. (it was nearly 19% before the update)
And I see 5% performance improvement for the task.
Thanks!

**Review by Firstyear — APPROVED** [review]
Then lets merge it :)
