### PR TITLE
Issue 6848 - AddressSanitizer: leak in do_search

### LINKED ISSUE #6848: AddressSanitizer: leak in do_search
**Issue Description**

Reproducible in dirsrvtests/tests/suites/basic/basic_test.py::test_attr_description_limit or by running 
```
ldapsearch -LLLx -s base cn "" "" "" "" "" "" "" "" "" "" ""
```

```
=================================================================
==11271==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 36192 byte(s) in 348 object(s) allocated from:
    #0 0x7f16258e6f0b in malloc (/lib64/libasan.so.8+0xe6f0b) (BuildId: 7f1aa7e2e600e8c9d54ce6e3d36f3d31bfe7949a)
    #1 0x7f1626057dcc in ber_memalloc_x (/lib64/liblber.so.2+0x3dcc) (BuildId: 0db15534bd84f99d6892b2cb4595a5f8a77a39f2)
    #2 0x7f162605800c in ber_get_stringbvl /usr/src/debug/openldap-2.6.9-3.fc42.x86_64/openldap-2.6.9/libraries/liblber/decode.c:421
    #3 0x7f162605a4ec in ber_scanf (/lib64/liblber.so.2+0x64ec) (BuildId: 0db15534bd84f99d6892b2cb4595a5f8a77a39f2)
    #4 0x56095c3d2d12 in do_search (/usr/bin/ns-slapd+0x58d12) (BuildId: b88d8d2a541da8e449c4802489929812bdcf8a83)
    #5 0x56095c3a83fe in connection_dispatch_operation (/usr/bin/ns-slapd+0x2e3fe) (BuildId: b88d8d2a541da8e449c4802489929812bdcf8a83)
    #6 0x56095c3a95ea in connection_threadmain (/usr/bin/ns-slapd+0x2f5ea) (BuildId: b88d8d2a541da8e449c4802489929812bdcf8a83)
    #7 0x7f16257e0842 in _pt_root ../../../../nspr/pr/src/pthreads/ptthread.c:191
    #8 0x7f1625828ee5 in asan_thread_start ../../../../libsanitizer/asan/asan_interceptors.cpp:239
    #9 0x7f162507f1d3 in start_thread (/lib64/libc.so.6+0x711d3) (BuildId: 7504db94dbf054e06eaac49950f57161c601f5c6)
    #10 0x7f1625101ceb in __GI___clone3 (/lib64/libc.so.6+0xf3ceb) (BuildId: 7504db94dbf054e06eaac49950f57161c601f5c6)

Indirect leak of 4872 byte(s) in 4176 object(s) allocated from:
    #0 0x7f16258e6f0b in malloc (/lib64/libasan.so.8+0xe6f0b) (BuildId: 7f1aa7e2e600e8c9d54ce6e3d36f3d31bfe7949a)
    #1 0x7f1626057dcc in ber_memalloc_x (/lib64/liblber.so.2+0x3dcc) (BuildId: 0db15534bd84f99d6892b2cb4595a5f8a77a39f2)
    #2 0x7f1626057ebf in ber_get_stringbv (/lib64/liblber.so.2+0x3ebf) (BuildId: 0db15534bd84f99d6892b2cb4595a5f8a77a39f2)
    #3 0x7f1626058088 in ber_get_stringbvl /usr/src/debug/openldap-2.6.9-3.fc42.x86_64/openldap-2.6.9/libraries/liblber/decode.c:447
    #4 0x7f162605a4ec in ber_scanf (/lib64/liblber.so.2+0x64ec) (BuildId: 0db15534bd84f99d6892b2cb4595a5f8a77a39f2)
    #5 0x56095c3d2d12 in do_search (/usr/bin/ns-slapd+0x58d12) (BuildId: b88d8d2a541da8e449c4802489929812bdcf8a83)
    #6 0x56095c3a83fe in connection_dispatch_operation (/usr/bin/ns-slapd+0x2e3fe) (BuildId: b88d8d2a541da8e449c4802489929812bdcf8a83)
    #7 0x56095c3a95ea in connection_threadmain (/usr/bin/ns-slapd+0x2f5ea) (BuildId: b88d8d2a541da8e449c4802489929812bdcf8a83)
    #8 0x7f16257e0842 in _pt_root ../../../../nspr/pr/src/pthreads/ptthread.c:191
    #9 0x7f1625828ee5 in asan_thread_start ../../../../libsanitizer/asan/asan_interceptors.cpp:239
    #10 0x7f162507f1d3 in start_thread (/lib64/libc.so.6+0x711d3) (BuildId: 7504db94dbf054e06eaac49950f57161c601f5c6)
    #11 0x7f1625101ceb in __GI___clone3 (/lib64/libc.so.6+0xf3ceb) (BuildId: 7504db94dbf054e06eaac49950f57161c601f5c6)

SUMMARY: AddressSanitizer: 41064 byte(s) leaked in 4524 allocation(s).
```

### PR DESCRIPTION
**Pull request by vashirov**
Bug Description:
When there's a BER decoding error and the function goes to `free_and_return`, the `attrs` variable is not being freed because it's only freed if `!psearch || rc != 0 || err != 0`, but `err` is still 0 at that point.

If we reach `free_and_return` from the `ber_scanf` error path, `attrs` was never set in the pblock with `slapi_pblock_set()`, so the `slapi_pblock_get()` call will not retrieve the potentially partially allocated `attrs` from the BER decoding.

Fixes: https://github.com/389ds/389-ds-base/issues/6848

### CODE REVIEW

**Comment by vashirov** [comment]
Tests are failing, investigating...

**Comment by vashirov** [comment]
Ok, tests are fixed, the usual tests are failing.

File: ldap/servers/slapd/search.c [hunk 1]
```diff
@@ -420,8 +421,16 @@ do_search(Slapi_PBlock *pb)
...
         slapi_ch_free_string(&fstr);
         slapi_filter_free(filter, 1);
-        slapi_pblock_get(pb, SLAPI_SEARCH_ATTRS, &attrs);
-        charray_free(attrs);    /* passing NULL is fine */
+
+        /* Get attrs from pblock if it was set there, otherwise use local attrs */
+        char **pblock_attrs = NULL;
+        slapi_pblock_get(pb, SLAPI_SEARCH_ATTRS, &pblock_attrs);
+        if (pblock_attrs != NULL) {
+            charray_free(pblock_attrs); /* Free attrs from pblock */
```
Comment (tbordaz) [inline ldap/servers/slapd/search.c:429]: I suggest to reset the pblock (slapi_pblock_set(pb, SLAPI_SEARCH_ATTRS, NULL)), to prevent a risk of double free

**Review by tbordaz — APPROVED** [review]
LGTM with a minor comment

File: ldap/servers/slapd/search.c (hunk 1 above)
Comment (vashirov) [reply ldap/servers/slapd/search.c:429]: Good point, added.

**Review by droideck — APPROVED** [review]
LGTM! Ack

**Comment by vashirov** [comment]
Failed tests are unrelated to the PR, I'll fix them as part of another change, merging.
