### PR TITLE
Issue 5490 - tombstone in entryrdn index with lmdb but not with bdb

### LINKED ISSUE #5490: tombstone in entryrdn index with lmdb but not with bdb
**Issue Description**

There is a inconsistency 

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch

**Steps to Reproduce**
1. Run following script
4. See error: nsuniqueid are present in mdb (before and after reindex but not in mdb)

**Expected results**
bdb and mdb should have the same result (no tombstone in entryrdn)

```
DBBASEDIR=/tmp/DB

doit()
{
    export NSSLAPD_DB_LIB=${1:?}
    mkm2  # create supplier1/supplier2 instances and setup replication

    ldapmodify -Y EXTERNAL -H ldapi://$S1 <<!
dn: ou=new_ou,ou=people,dc=example,dc=com
changetype: add
ou: new_ou
objectClass: organizationalunit

dn: uid=new_demo_user,ou=new_ou,ou=people,dc=example,dc=com
changetype: add
nsAccountLock: true
loginShell: /bin/false
homeDirectory: /var/empty
gidNumber: 99997
uidNumber: 99997
legalName: Demo User Name
displayName: Demo User
cn: New Demo User
uid: new_demo_user
objectClass: top
objectClass: nsPerson
objectClass: nsAccount
objectClass: nsOrgPerson
objectClass: posixAccount

dn: uid=demo_user,ou=people,dc=example,dc=com
changetype: modify
replace: description
description: $(date)

dn: uid=new_demo_user,ou=new_ou,ou=people,dc=example,dc=com
changetype: delete

dn: ou=new_ou,ou=people,dc=example,dc=com
changetype: delete
!

    cp -r $PREFIX/var/lib/dirsrv/slapd-supplier1/db $DBBASEDIR/db.$NSSLAPD_DB_LIB.br
    dsconf supplier1 backend index reindex userroot
    cp -r $PREFIX/var/lib/dirsrv/slapd-supplier1/db $DBBASEDIR/db.$NSSLAPD_DB_LIB.ar
    dbscan -D ${NSSLAPD_DB_LIB:?} -f $DBBASEDIR/db.$NSSLAPD_DB_LIB.br/userroot/entryrdn.db > $DBBASEDIR/entryrdn.$NSSLAPD_DB_LIB.ar
    dbscan -D ${NSSLAPD_DB_LIB:?} -f $DBBASEDIR/db.$NSSLAPD_DB_LIB.ar/userroot/entryrdn.db > $DBBASEDIR/entryrdn.$NSSLAPD_DB_LIB.br
}

/bin/rm -rf $DBBASEDIR
mkdir $DBBASEDIR
doit bdb
doit mdb
grep nsuniqueid $DBBASEDIR/entryrdn.*
```

### PR DESCRIPTION
**Pull request by progier389**
Align mdb behavior on bdb one about tombstone entries and (entryrdn / parentid/ ancestorid ) indexes:
Make sure that entry info are build for tombstone and RUV entry so the indexes get properly updated.
Fix deadlock by insuring that ai is provided when first opening the dbi while reindexing (so that cmp function is rightly set and does not need to be set later on)

[1] Added a test that check the tombstone in entryrdn after import/reindex/bulk import
[2] I found that Tombstone entry should be in the entryrdn index but:
       parent should be looked up with the nsparentuniqueid rather than on the parent dn.
       ==>  entries nsuniqueid should also be a key of the import private database
       And tombstone entry should also be stored in the private database
 [3] Fixed some issue in test case
 [4] removed the cas atomic operation 
 [5] Fixed dsrate issue about full lmdb database  
 [6] Fixed issue around cursor bulk operation
 [7] Improved/fixed entryrdn and lmdb debug   
       
Issue: 5490

Reviewed by: @tbordaz

### CODE REVIEW

**Comment by progier389** [comment]
https://github.com/389ds/389-ds-base/actions/runs/3428815879 still shows errors in replication but anyway I propose to commit what is already fixed.

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c [hunk 1]
```diff
@@ -268,20 +272,47 @@ dbg_log(const char *file, int lineno, const char *funcname, int loglevel, char *
...
+dbg_should_log(int loglvl, MDB_dbi dbi, MDB_cursor *cursor)
+{
+    dbmdb_dbi_t *dbi1;
+
+    if (dbgmdb_level & loglvl) {
+        return 1;
+    }
+    if (dbgmdb_level & DBGMDB_LEVEL_REPL) {
+        if (cursor) {
+            dbi = mdb_cursor_dbi(cursor);
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c:298]: Shouldn't it be '*dbi' ?

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c [hunk 2]
```diff
@@ -785,15 +829,20 @@ dbmdb_import_entry_info_by_param(EntryInfoParam_t *param, WorkerQueueData_t *wqe
...
                 param->pkey.mv_size = strlen(param->pkey.mv_data)+1;
                 if (!param->pkey.mv_data) {
                     dnrc = DNRC_NOPARENT_DN;
                 }
             }
         }
     }
-    if (dnrc == DNRC_OK) {
+    if (param->eid == 1 && dnrc == DNRC_RUV) {
+        /* RUV is first entry lets return it as it */
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:841]: Does it assume that the RUV is the first entry in the ldiffile ? What if it is not ?

**Review by tbordaz — APPROVED** [review]
LGTM, just a couple of comments

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c (hunk 2 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:841]: Indeed this test goal is to handle the" RUV entry is before suffix entry" case 
 if the RUV is not the first entry, the suffix entry is supposed to be the first entry
    (otherwise the ldif is buggy and all entries before the suffix get skipped) .
 and in this case the RUV is handled as standard entry 
     ( looking for the parent (i.e the suffix) entry info and adding the entry info)

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c:298]: No, this function is called either with a meaningful dbi or with a meaningful cursor (not both)
 so if we have a cursor then we must extract the dbi from the cursor.
    ( The reason is that dbi is not provided in the lmdb  function prototype that handle cursor _ )

Comment (tbordaz) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c:298]: Sorry, I still miss something. If the cursor handle (dbi) is retrieved from the cursor, shouldn't do
`*dbi = mdb_cursor_dbi(cursor)` rather than
`dbi = mdb_cursor_dbi(cursor)`

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c (hunk 2 above)
Comment (tbordaz) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:841]: Thanks

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c:298]: No: dbi is a MDB_dbi and not a MDB_dbi* (in fact it is a plain integer)

**Comment by progier389** [comment]
This PR also take care of [issue 5484](https://github.com/389ds/389-ds-base/issues/5484) by removing the CAS atomic operation and replacing it with mutex.

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c [hunk 3]
```diff
@@ -434,10 +476,10 @@ int
 dbg_mdb_drop(const char *file, int lineno, const char *funcname, MDB_txn *txn, MDB_dbi dbi, int del)
 {
     int rc = mdb_drop(txn, dbi, del);
-    if (dbgmdb_level & DBGMDB_LEVEL_MDBAPI) {
+    if (dbg_should_log(DBGMDB_LEVEL_MDBAPI, dbi, NULL)) {
         char dbistr[DBGVAL2STRMAXSIZE];
         dbi_str(NULL, dbi, dbistr);
-        dbg_log(file, lineno, funcname, DBGMDB_LEVEL_MDBAPI, "mdb_drop(txn: %p, %s, del: %d)=%d", txn, dbistr, del, rc);
+        dbg_log(file, lineno, funcname, DBGMDB_LEVEL_MDBAPI+DBGMDB_LEVEL_FORCE, "mdb_drop(txn: %p, %s, del: %d)=%d", txn, dbistr, del, rc);
```
Comment (Firstyear) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c:482]: I think normal convention is | not + for log mask combinations, but it's not a huge deal here I guess.

File: ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c [hunk 4]
```diff
@@ -37,8 +37,21 @@ static int entryrdn_noancestorid = 0;
 
 #ifdef LDAP_DEBUG_ENTRYRDN
 #define _ENTRYRDN_DUMP_RDN_ELEM(elem) _entryrdn_dump_rdn_elem(__LINE__, #elem, elem)
+#define _ENTRYRDN_DUMP_RDN_ELEM_ARRAY(elem) { \
+            if (elem) { \
+                char buff[50]; \
+                int i; \
```
Comment (Firstyear) [inline ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c:43]: size_t i, and inline with the for loop 

```
for (size_t i = 0; ...)
```
