### PR TITLE
Issue 6442 - Fix latest covscan memory leaks

### LINKED ISSUE #6442: Fix covscan memory leaks on main branch
**Issue Description**

Covscan reports 26 leaks on main branch, and other issues of course.   

```
ARRAY_VS_SINGLETON        9
BAD_CHECK_OF_WAIT_COND    11
COMPILER_WARNING          1
IDENTICAL_BRANCHES        1
INTEGER_OVERFLOW          5
LOCK_EVASION              9
OVERRUN                   35
RESOURCE_LEAK             26
USE_AFTER_FREE            25
Y2K38_SAFETY              2
```

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:

Fixed a majority of the memory leaks (except ACL leaks), and some Y2K38 issues

Fixes: https://github.com/389ds/389-ds-base/issues/6442

### CODE REVIEW

File: ldap/servers/plugins/acctpolicy/acct_plugin.c [hunk 1]
```diff
@@ -272,9 +272,11 @@ acct_update_login_history(const char *dn, char *timestr)
         }
         /* first time round */
     } else if (cfg->login_history_size > 0) {
-        login_hist = (char **)slapi_ch_calloc(2, sizeof(char *));
-        /* alloc new array and append latest value */
-        login_hist = (char **)slapi_ch_realloc((char *)login_hist, sizeof(char *) * (num_entries + 2));
+        if (login_hist == NULL) {
```
Comment (progier389) [inline ldap/servers/plugins/acctpolicy/acct_plugin.c]: FYI:  According to realloc man page, If ptr is NULL, then realloc(ptr, size) is equivalent to malloc(size)
so IMHO the proper code is:
```
/* alloc new array and append latest value */
login_hist = (char **)slapi_ch_realloc((char *)login_hist, sizeof(char *) * (num_entries + 2));
```
(i.e only removing useless line 275 ...)

File: dirsrvtests/tests/suites/basic/basic_test.py [hunk 2]
```diff
@@ -537,11 +537,10 @@ def test_basic_import_export(topology_st, import_example_ldif):
     import_task.import_suffix_from_ldif(ldiffile=import_ldif, suffix=DEFAULT_SUFFIX)
 
     # Wait a bit till the task is created and available for searching
-    time.sleep(1)
+    time.sleep(2)
```
Comment (progier389) [inline dirsrvtests/tests/suites/basic/basic_test.py]: I do not think the changes in this file belong to this PR as it has nothing to do with covscan fixes ...
IMHO covscan fix is tricky enough to avoid the complexity of adding other changes in middle of them.
Better push them in another PR

File: ldap/servers/plugins/acl/acllas.c [hunk 3]
```diff
@@ -4308,6 +4308,10 @@ acllas_replace_attr_macro(char *rule, lasInfo *lasinfo)
              * list which replaces the old one.
              */
             l = acl_strstr(&str[0], ")");
+            if (l + 2 < 0) {
```
Comment (progier389) [inline ldap/servers/plugins/acl/acllas.c]: test is a bit stange as l  +2 < 0 because acl_stestr either returns -1 or the string lenght which is >= 0  so l+2 >= 1
IMHO if (l<0) does makes more sense

File: ldap/servers/plugins/acl/acllas.c [hunk 4]
```diff
@@ -4323,7 +4327,7 @@ acllas_replace_attr_macro(char *rule, lasInfo *lasinfo)
 
             str++; /* skip the . */
             l = acl_strstr(&str[0], ")");
-            if (l == -1){
+            if (l < 0) {
```
Comment (progier389) [inline ldap/servers/plugins/acl/acllas.c]: why changing that one ?

File: ldap/servers/plugins/chainingdb/cb_conn_stateless.c [hunk 5]
```diff
@@ -958,21 +959,22 @@ cb_update_failed_conn_cpt(cb_backend_instance *cb)
                           "cb_update_failed_conn_cpt - Farm server unavailable");
         }
     }
+    slapi_unlock_mutex(cb->monitor_availability.cpt_lock);
```
Comment (progier389) [inline ldap/servers/plugins/chainingdb/cb_conn_stateless.c:961]: lock unlocked twice: lines 950 and 962.
Should rather be in else par

File: ldap/servers/plugins/replication/repl5_replica.c [hunk 6]
```diff
@@ -35,7 +35,7 @@ struct replica
     ReplicaUpdateDNList updatedn_list; /* list of dns with which a supplier should bind to update this replica */
     Slapi_ValueSet *updatedn_groups;   /* set of groups whose memebers are allowed to update replica */
     ReplicaUpdateDNList groupdn_list;  /* exploded listof dns from update group */
-    uint32_t updatedn_group_last_check;    /* the time of the last group check */
+    uint64_t updatedn_group_last_check;    /* the time of the last group check */
```
Comment (progier389) [inline ldap/servers/plugins/replication/repl5_replica.c]: Should be a time_t I think

File: ldap/servers/plugins/retrocl/retrocl_trim.c [hunk 7]
```diff
@@ -239,7 +239,7 @@ trim_changelog(void)
     time_t now_maxage; /* used for checking if the changelog entry can be trimmed */
     changeNumber first_in_log = 0, last_in_log = 0;
     int num_deleted = 0;
-    int max_age, last_trim, trim_interval;
+    uint64_t max_age, last_trim, trim_interval;
```
Comment (progier389) [inline ldap/servers/plugins/retrocl/retrocl_trim.c]: time_t

File: ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c [hunk 8]
```diff
@@ -1749,7 +1749,7 @@ bdb_import_push_progress_history(ImportJob *job, ID current_id, time_t current_t
 }
 
 static void
-bdb_import_calc_rate(ImportWorkerInfo *info, int time_interval)
+bdb_import_calc_rate(ImportWorkerInfo *info, uint64_t time_interval)
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/db-bdb/bdb_import.c]: time_t ?

File: ldap/servers/slapd/plugin_internal_op.c [hunk 9]
```diff
@@ -282,12 +276,6 @@ slapi_search_internal_set_pb_ext(Slapi_PBlock *pb, Slapi_DN *sdn, int scope, con
         return;
     }
 
-    /* Free op/attrs just in case this pb is being reused */
```
Comment (progier389) [inline ldap/servers/slapd/plugin_internal_op.c:285]: Not sure we should not keep these an rather add
 slapi_pblock_set(pb, SLAPI_OPERATION, NULL);
 slapi_pblock_get(pb, SLAPI_SEARCH_ATTRS, NULL);
 to avoid double free
 
 Same issue in two next changes

File: ldap/servers/slapd/util.c [hunk 10]
```diff
@@ -1067,6 +1067,16 @@ slapi_rand_r(unsigned int *randx)
     return (int)(*randx & 0x7FFFFFFF);
 }
 
+int
+slapi_rand_r_64(uint64_t *randx)
```
Comment (progier389) [inline ldap/servers/slapd/util.c]: Does this change belong to that PR ?

**Review by progier389 — CHANGES_REQUESTED** [review]
one serious issues  (double unlock)
and lots of minor ones.

File: ldap/servers/plugins/acl/acllas.c (hunk 3 above)
Comment (mreynolds389) [reply ldap/servers/plugins/acl/acllas.c]: Again this is just fixing a warning.  And I found it here:

```
Error: INTEGER_OVERFLOW ([CWE-190](https://cwe.mitre.org/data/definitions/190.html)): [[#def2]](https://cov01.lab.eng.brq2.redhat.com/osh/task/766355/log/389-ds-base-3.1.1.202412091343git4c51c6ea1-1.fc41/scan-results.html#def2) [important]
389-ds-base-3.1.1.202412091343git4c51c6ea1-build/389-ds-base-3.1.1.202412091343git4c51c6ea1/ldap/servers/plugins/acl/acllas.c:4310:13: tainted_data_return: Called function "acl_strstr(&str[0], ")")", and a possible return value may be less than zero.
389-ds-base-3.1.1.202412091343git4c51c6ea1-build/389-ds-base-3.1.1.202412091343git4c51c6ea1/ldap/servers/plugins/acl/acllas.c:4310:13: assign: Assigning: "l" = "acl_strstr(&str[0], ")")".
389-ds-base-3.1.1.202412091343git4c51c6ea1-build/389-ds-base-3.1.1.202412091343git4c51c6ea1/ldap/servers/plugins/acl/acllas.c:4315:13: overflow: The expression "l + 2" is considered to have possibly overflowed.
389-ds-base-3.1.1.202412091343git4c51c6ea1-build/389-ds-base-3.1.1.202412091343git4c51c6ea1/ldap/servers/plugins/acl/acllas.c:4315:13: overflow_sink: "l + 2", which might be negative, is passed to "slapi_ch_malloc(l + 2)".
# 4313|                   return NULL;
# 4314|               }
# 4315|->             macro_str = slapi_ch_malloc(l + 2);
# 4316|               strncpy(macro_str, &str[0], l + 1);
# 4317|               macro_str[l + 1] = '\0';

Error: INTEGER_OVERFLOW ([CWE-190](https://cwe.mitre.org/data/definitions/190.html)): [[#def3]](https://cov01.lab.eng.brq2.redhat.com/osh/task/766355/log/389-ds-base-3.1.1.202412091343git4c51c6ea1-1.fc41/scan-results.html#def3) [important]
389-ds-base-3.1.1.202412091343git4c51c6ea1-build/389-ds-base-3.1.1.202412091343git4c51c6ea1/ldap/servers/plugins/acl/acllas.c:4329:13: tainted_data_return: Called function "acl_strstr(&str[0], ")")", and a possible return value may be less than zero.
389-ds-base-3.1.1.202412091343git4c51c6ea1-build/389-ds-base-3.1.1.202412091343git4c51c6ea1/ldap/servers/plugins/acl/acllas.c:4329:13: assign: Assigning: "l" = "acl_strstr(&str[0], ")")".
389-ds-base-3.1.1.202412091343git4c51c6ea1-build/389-ds-base-3.1.1.202412091343git4c51c6ea1/ldap/servers/plugins/acl/acllas.c:4337:13: overflow: The expression "l + 1" is considered to have possibly overflowed.
389-ds-base-3.1.1.202412091343git4c51c6ea1-build/389-ds-base-3.1.1.202412091343git4c51c6ea1/ldap/servers/plugins/acl/acllas.c:4337:13: overflow_sink: "l + 1", which might have overflowed, is passed to "slapi_ch_malloc(l + 1)".
# 4335|                   return NULL;
# 4336|               }
# 4337|->             macro_attr_name = slapi_ch_malloc(l + 1);
# 4338|               strncpy(macro_attr_name, &str[0], l);
# 4339|               macro_attr_name[l] = '\0';
```

File: dirsrvtests/tests/suites/basic/basic_test.py (hunk 2 above)
Comment (mreynolds389) [reply dirsrvtests/tests/suites/basic/basic_test.py]: sounds good

File: ldap/servers/slapd/util.c (hunk 10 above)
Comment (mreynolds389) [reply ldap/servers/slapd/util.c]: Ok, so for Y2K38 time_t is going to become 64 bit (versus 32 bit).  So a lot of these changes are to address the upcoming Y2K38 issues.  So we need a 64 bit version of slapi_rand_r() for passwd_extop.c

File: ldap/servers/plugins/chainingdb/cb_conn_stateless.c (hunk 5 above)
Comment (mreynolds389) [reply ldap/servers/plugins/chainingdb/cb_conn_stateless.c:961]: > lock unlocked twice: lines 950 and 962. Should rather be in else par

Yeah I forgot to remove the unlock on line 950 when I moved it to after the "if" block.  Good catch.

File: ldap/servers/slapd/util.c (hunk 10 above)
Comment (progier389) [reply ldap/servers/slapd/util.c]: I do not think we really need to change that code as the time is only used to get a random seed value.
  That is the rare case were we could safely truncated the 64 bit time_t to a 32 bit unsigned integer   (upper bits are not really significant as they rarely change anyway) 
Using a 32 bit seed seems good enough especially as we want to generate a  small  random value ...

**Comment by mreynolds389** [comment]
@progier389 Changes made, please review...

File: ldap/servers/slapd/passwd_extop.c [hunk 11]
```diff
@@ -288,8 +288,8 @@ passwd_modify_generate_policy_passwd(passwdPolicy *pwpolicy,
     /* if only minalphas is set, divide it into minuppers and minlowers. */
     if (pwpolicy->pw_minalphas > 0 &&
         (my_policy[idx_minuppers] == 0 && my_policy[idx_minlowers] == 0)) {
-        unsigned int x = (unsigned int)time(NULL);
-        my_policy[idx_minuppers] = slapi_rand_r(&x) % pwpolicy->pw_minalphas;
+        uint64_t x = time(NULL);
```
Comment (progier389) [inline ldap/servers/slapd/passwd_extop.c]: should rather be uint32_t x = (uint32_t)time(NULL)
... slapi_rand_r(&x) ...

File: ldap/servers/slapd/passwd_extop.c [hunk 12]
```diff
@@ -346,10 +346,10 @@ passwd_modify_generate_policy_passwd(passwdPolicy *pwpolicy,
     /* if password length is longer the sum of my_policy's,
        let them share the burden */
     if (passlen > tmplen) {
-        unsigned int x = (unsigned int)time(NULL);
+        uint64_t x = time(NULL);
```
Comment (progier389) [inline ldap/servers/slapd/passwd_extop.c]: same as above: uint32_t x = ...

**Review by progier389 — COMMENTED** [review]
Still two changes needed passwd_extop.c around the slapi_rand_r
Casting int64 pointer to int32 pointer is a bad idea (depending on the endianess, we may ends up with a constand seed)  that is the value that should be cast.
 I wrote `uint32_t x = (uint32_t)time(NULL) `but reading the change again I have the feeling that the original code `unsigned int x = (unsigned int)time(NULL);` is correct.
(Sorry I should have been more precise when speaking about the cast in my previous week comments)
Everything else looks good ...

File: ldap/servers/slapd/passwd_extop.c (hunk 11 above)
Comment (mreynolds389) [reply ldap/servers/slapd/passwd_extop.c]: I think coverity is still going to complain about this change as it wants a uint64_t for the time value.  I will try it, but... we do have some time (13 years) until a change is actually needed :-)  So we could skip this for now.

Comment (progier389) [reply ldap/servers/slapd/passwd_extop.c]: Maybe add a comment saying that we should ignore coverity scan warning (because we do not care about the 64-32 bits values when initializing the random seed)

Comment (mreynolds389) [reply ldap/servers/slapd/passwd_extop.c]: Reverted change and added comments.  Please review...

File: ldap/servers/slapd/passwd_extop.c [hunk 13]
```diff
@@ -287,7 +287,9 @@ passwd_modify_generate_policy_passwd(passwdPolicy *pwpolicy,
 
     /* if only minalphas is set, divide it into minuppers and minlowers. */
     if (pwpolicy->pw_minalphas > 0 &&
-        (my_policy[idx_minuppers] == 0 && my_policy[idx_minlowers] == 0)) {
+        (my_policy[idx_minuppers] == 0 && my_policy[idx_minlowers] == 0))
+    {
+        /* For Y2K38 we will need to handle time() returning a uint64_t value */
```
Comment (progier389) [inline ldap/servers/slapd/passwd_extop.c]: I have the feeling that you missed my point: 
 For Y2K38 we do NOT have to do anything in this file:  time() will then return a uint64_t value that will then be truncated to a uint32_t but that is ok as we only want to generate 32 random  (more or less) bytes to initialize the pseudo random generator seed. (i.e: we do not care about the real date)
 The comment we should add is that we should ignore covscan Y2K38 warning. in theses two lines) !-;)
 
 Anyway I will approve the changes as it is as nothing is broken ...

**Review by progier389 — APPROVED** [review]
LGTM

File: ldap/servers/slapd/passwd_extop.c (hunk 13 above)
Comment (mreynolds389) [reply ldap/servers/slapd/passwd_extop.c]: I added this above the two random function calls:

      /* coverity[store_truncates_time_t] */
