### PR TITLE
Issue 4396 - Minor memory leak in backend

### LINKED ISSUE #4396: Memory leak in BE (minor)
```
=================================================================
==53701==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 40 byte(s) in 1 object(s) allocated from:
   #0 0x7fe2652ec27f in __interceptor_malloc (/usr/lib64/libasan.so.6+0xae27f)
   #1 0x7fe264e96b34 in slapi_ch_malloc /home/william/development/389ds/ds/ldap/servers/slapd/ch_malloc.c:95
   #2 0x7fe264eb41c9 in slapi_sdn_new /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:1888
   #3 0x7fe264eb4a4b in slapi_sdn_new_normdn_byval /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2087
   #4 0x7fe264eb6871 in slapi_sdn_dup /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2474
   #5 0x7fe264e8eb25 in be_addsuffix /home/william/development/389ds/ds/ldap/servers/slapd/backend.c:176
   #6 0x444bae in setup_internal_backends /home/william/development/389ds/ds/ldap/servers/slapd/fedse.c:2887
   #7 0x448d11 in main /home/william/development/389ds/ds/ldap/servers/slapd/main.c:718
   #8 0x7fe264655e09 in __libc_start_main (/lib64/libc.so.6+0x27e09)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
   #0 0x7fe2652ec27f in __interceptor_malloc (/usr/lib64/libasan.so.6+0xae27f)
   #1 0x7fe264e96b34 in slapi_ch_malloc /home/william/development/389ds/ds/ldap/servers/slapd/ch_malloc.c:95
   #2 0x7fe264eb41c9 in slapi_sdn_new /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:1888
   #3 0x7fe264eb4a4b in slapi_sdn_new_normdn_byval /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2087
   #4 0x7fe264eb6871 in slapi_sdn_dup /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2474
   #5 0x7fe264e8eb25 in be_addsuffix /home/william/development/389ds/ds/ldap/servers/slapd/backend.c:176
   #6 0x444b95 in setup_internal_backends /home/william/development/389ds/ds/ldap/servers/slapd/fedse.c:2886
   #7 0x448d11 in main /home/william/development/389ds/ds/ldap/servers/slapd/main.c:718
   #8 0x7fe264655e09 in __libc_start_main (/lib64/libc.so.6+0x27e09)

Indirect leak of 11 byte(s) in 1 object(s) allocated from:
   #0 0x7fe2652993f7 in strdup (/usr/lib64/libasan.so.6+0x5b3f7)
   #1 0x7fe264e9701b in slapi_ch_strdup /home/william/development/389ds/ds/ldap/servers/slapd/ch_malloc.c:196
   #2 0x7fe264eb50d4 in slapi_sdn_set_normdn_byval /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2167
   #3 0x7fe264eb4a62 in slapi_sdn_new_normdn_byval /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2088
   #4 0x7fe264eb6871 in slapi_sdn_dup /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2474
   #5 0x7fe264e8eb25 in be_addsuffix /home/william/development/389ds/ds/ldap/servers/slapd/backend.c:176
   #6 0x444bae in setup_internal_backends /home/william/development/389ds/ds/ldap/servers/slapd/fedse.c:2887
   #7 0x448d11 in main /home/william/development/389ds/ds/ldap/servers/slapd/main.c:718
   #8 0x7fe264655e09 in __libc_start_main (/lib64/libc.so.6+0x27e09)

Indirect leak of 1 byte(s) in 1 object(s) allocated from:
   #0 0x7fe2652993f7 in strdup (/usr/lib64/libasan.so.6+0x5b3f7)
   #1 0x7fe264e9701b in slapi_ch_strdup /home/william/development/389ds/ds/ldap/servers/slapd/ch_malloc.c:196
   #2 0x7fe264eb50d4 in slapi_sdn_set_normdn_byval /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2167
   #3 0x7fe264eb4a62 in slapi_sdn_new_normdn_byval /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2088
   #4 0x7fe264eb6871 in slapi_sdn_dup /home/william/development/389ds/ds/ldap/servers/slapd/dn.c:2474
   #5 0x7fe264e8eb25 in be_addsuffix /home/william/development/389ds/ds/ldap/servers/slapd/backend.c:176
   #6 0x444b95 in setup_internal_backends /home/william/development/389ds/ds/ldap/servers/slapd/fedse.c:2886
   #7 0x448d11 in main /home/william/development/389ds/ds/ldap/servers/slapd/main.c:718
   #8 0x7fe264655e09 in __libc_start_main (/lib64/libc.so.6+0x27e09)
```

Found during execution of the mapping tree test suites. After talking to @mreynolds389 we think this may be related to backend monitor changes that were recently made. These appear to be minor/non-critical but always best to resolve these!

### PR DESCRIPTION
**Pull request by jchapma**
Bug Description: As multiple suffixes per backend were no longer used, this
functionality has been replaced with a single suffix per backend. Legacy
code remains that adds multiple suffixes to the dse internal backend,
resulting in memory allocations that are lost and never used.

Also a minor typo is corrected in backend.c

Fix Description: Multiple calls to be_addsuffix on the DSE backend are removed
as they are never used.

Fixes: https://github.com/389ds/389-ds-base/issues/4396

Reviewed by: ??

### CODE REVIEW

File: ldap/servers/slapd/fedse.c [hunk 1]
```diff
@@ -2950,15 +2950,10 @@ setup_internal_backends(char *configdir)
         dse_register_callback(pfedse, SLAPI_OPERATION_ADD, DSE_FLAG_PREOP, &plugins, LDAP_SCOPE_SUBTREE, "(objectclass=nsSlapdPlugin)", check_plugin_path, NULL, NULL);
 
         be = be_new_internal(pfedse, "DSE", DSE_BACKEND, &fedse_plugin);
```
Comment (mreynolds389) [inline ldap/servers/slapd/fedse.c]: You could remove "Slapi_Backend *be" from the top of the function, and change this call to just be:  

    be_new_internal(pfedse, "DSE", DSE_BACKEND, &fedse_plugin);

I don't think that will trigger a complier warning, but best to check.  Otherwise ack from me.

For other reviewers ->  be_new_internal() adds that backend to a global list (backends in backend_manager.c), and it does get freed later.

Comment (Firstyear) [reply ldap/servers/slapd/fedse.c]: Seems like a good approach to me @mreynolds389 :)

Comment (jchapma) [reply ldap/servers/slapd/fedse.c]: Makes sense, I should have removed that with the previous change.

**Comment by mreynolds389** [comment]
LGTM, ack

**Review by droideck — APPROVED** [review]
Looks good to me too!
Nice clean up:)
