### PR TITLE
Issue 6928 - The parentId attribute is indexed with improper matching…

### LINKED ISSUE #6915: DSRetroclPlugin - An error occured while adding change number
**Issue Description**
Under certain circumstances RetroCL plugin can experience an issue that can cause errors such as:
```
ERR - DSRetroclPlugin - retrocl_postob - Operation failure [68]
WARN - flush_hash - Upon BETXN callback failure, entry cache is flushed during 0.015972218
WARN - flush_hash - Upon BETXN callback failure, entry cache is flushed during 0.000910450
ERR - DSRetroclPlugin - write_replog_db - An error occured while adding change number 100, dn = changenumber=100,cn=changelog: Already exists.
```

Reproducer:
```
dsconf localhost plugin retro-changelog enable
dsctl localhost restart
dsconf localhost backend index set --attr changeNumber --del-mr integerOrderingMatch changelog --reindex
ldapadd -D cn=Directory\ Manager -w password -f bad.ldif -c
modifying entry "ou=people,dc=example,dc=com"

modifying entry "ou=people,dc=example,dc=com"

modifying entry "ou=people,dc=example,dc=com"

modifying entry "ou=people,dc=example,dc=com"

modifying entry "ou=people,dc=example,dc=com"

modifying entry "ou=people,dc=example,dc=com"

modifying entry "ou=people,dc=example,dc=com"

modifying entry "ou=people,dc=example,dc=com"

modifying entry "ou=people,dc=example,dc=com"

modifying entry "ou=people,dc=example,dc=com"

modifying entry "uid=foobar,ou=people,dc=example,dc=com"
ldap_modify: No such object (32)
        matched DN: ou=people,dc=example,dc=com

modifying entry "ou=people,dc=example,dc=com"
ldap_modify: Already exists (68)

```

```
cat bad.ldif
dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-

dn: uid=foobar,ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should fail
-

dn: ou=people,dc=example,dc=com
changetype: modify
replace: description
description: This should work
-
```

### LINKED ISSUE #6928: The parentid attribute is indexed with improper matching rule
**Issue Description**
ParentID attribute contains integer values and needs to be indexed with integerOrderingMatch matching rule.
This attribute is a system attribute and the configuration entry for this attribute is created when a backend is created.
The bug is that the per backend configuration entry does not contains 'nsMatchingRule: integerOrderingMatch'

One of the main impact of that bug is that it can break online total init (replication).

**Package Version and Platform:**
All releases (since https://github.com/389ds/389-ds-base/issues/1815) 

**Steps to Reproduce**
1. create an instance with a backend
2. add 1000 entries
3. dbscan -f /var/lib/dirsrv/slapd-instance/db/backend/parentid should show
=0                                      
=1        
=10
=100                                     
=1000 
....    

**Expected results**
The index should contain
=0
=1
=2
=3
...

### PR DESCRIPTION
**Pull request by vashirov**
… rule

Bug Description:
`parentId` attribute contains integer values and needs to be indexed with `integerOrderingMatch` matching rule. This attribute is a system attribute and the configuration entry for this attribute is created when a backend is created. The bug is that the per backend configuration entry does not contain `nsMatchingRule: integerOrderingMatch`.

Fix Description:
* Update `ldbm_instance_create_default_indexes` to support matching rules and update default system index configuration for `parentId` to include `integerOrderingMatch` matching rule.
* Add healthcheck linter for default system indexes and indexes created by RetroCL and USN plugins.

Fixes: https://github.com/389ds/389-ds-base/issues/6928
Fixes: https://github.com/389ds/389-ds-base/issues/6915

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/instance.c [hunk 1]
```diff
@@ -182,50 +188,50 @@ ldbm_instance_create_default_indexes(backend *be)
...
+    e = ldbm_instance_init_config_entry(LDBM_PSEUDO_ATTR_DEFAULT, "none", 0, 0, 0, 0);
     attr_index_config(be, "ldbm index init", 0, e, 1, 0, NULL);
     slapi_entry_free(e);
 
     /*
      * ancestorid is special, there is actually no such attr type
      * but we still want to use the attr index file APIs.
      */
-    e = ldbm_instance_init_config_entry(LDBM_ANCESTORID_STR, "eq", 0, 0, 0);
+    e = ldbm_instance_init_config_entry(LDBM_ANCESTORID_STR, "eq", 0, 0, 0, 0);
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/instance.c]: Should also be integerOrderingMatch

**Review by progier389 — CHANGES_REQUESTED** [review]
Looks good except the fact that ancestorid requires the same change

File: ldap/servers/slapd/back-ldbm/instance.c (hunk 1 above)
Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/instance.c]: Should I also add `ancestorid` to the list of default indexes to `ldap/ldif/template-dse.ldif.in`, so it would be created for new backends?

File: src/lib389/lib389/backend.py [hunk 2]
```diff
@@ -607,6 +608,125 @@ def _lint_cl_trimming(self):
...
+        indexes = self.get_indexes()
+
+        # Default system indexes taken from ldap/servers/slapd/back-ldbm/instance.c
+        expected_system_indexes = {
+            'entryrdn': {'types': ['subtree'], 'matching_rule': None},
+            'parentId': {'types': ['eq'], 'matching_rule': 'integerOrderingMatch'},
+            'objectClass': {'types': ['eq'], 'matching_rule': None},
+            'aci': {'types': ['pres'], 'matching_rule': None},
+            'nsUniqueId': {'types': ['eq'], 'matching_rule': None},
+            'nsds5ReplConflict': {'types': ['eq', 'pres'], 'matching_rule': None}
```
Comment (tbordaz) [inline src/lib389/lib389/backend.py:626]: Any reason why 'nscpEntryDN' and 'ancestorid' are not listed ?

**Review by tbordaz — COMMENTED** [review]
The overall patch looks good to me. I agree on integerOrder for ancestorid as well

File: src/lib389/lib389/backend.py (hunk 2 above)
Comment (vashirov) [reply src/lib389/lib389/backend.py:626]: Initially I based my list on default system indexes (`nssystemindex: true`) from `ldap/ldif/template-dse.ldif.in`. I see now that I also missed:
- nsCertSubjectDN
- numsubordinates
- nsTombstoneCSN
- targetuniqueid

File: ldap/servers/slapd/back-ldbm/instance.c (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/instance.c]: Definitively yes. (That is the index used for subtree searches. parentid is used for onelevel searches)

File: src/lib389/lib389/backend.py (hunk 2 above)
Comment (vashirov) [reply src/lib389/lib389/backend.py:626]: I've added missing indexes

File: ldap/servers/slapd/back-ldbm/instance.c (hunk 1 above)
Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/instance.c]: I've added `ancestorid` to the template and to the check.

**Review by tbordaz — APPROVED** [review]
LGTM

**Review by progier389 — APPROVED** [review]
LGTM

**Comment by vashirov** [comment]
basic test suite is now failing, investigating.
