### PR TITLE
Issue 7115 - LeakSanitizer: leak in slapd_bind_local_user

### LINKED ISSUE #7115: LeakSanitizer: leak in slapd_bind_local_user
**Issue Description**
```
Direct leak of 368 byte(s) in 2 object(s) allocated from:
    #0 0x7f8b7e5728a3 in calloc (/usr/lib64/libasan.so.8+0xe68a3) (BuildId: 0adabddcb77130fc2ea3840d060eb4e8a9ae0c85)
    #1 0x7f8b7e170e1c in slapi_ch_calloc (/usr/lib64/dirsrv/libslapd.so.0+0x20e1c) (BuildId: 971a9b69d84f8b7ef43886193048efa2b1116cbf)
    #2 0x7f8b7e17edbb in slapi_entry_alloc (/usr/lib64/dirsrv/libslapd.so.0+0x2edbb) (BuildId: 971a9b69d84f8b7ef43886193048efa2b1116cbf)
    #3 0x7f8b7e17f25f in slapi_entry_dup (/usr/lib64/dirsrv/libslapd.so.0+0x2f25f) (BuildId: 971a9b69d84f8b7ef43886193048efa2b1116cbf)
    #4 0x7f8b7e1e1f1b in slapi_search_internal_get_entry (/usr/lib64/dirsrv/libslapd.so.0+0x91f1b) (BuildId: 971a9b69d84f8b7ef43886193048efa2b1116cbf)
    #5 0x7f8b7e19582b in slapd_bind_local_user (/usr/lib64/dirsrv/libslapd.so.0+0x4582b) (BuildId: 971a9b69d84f8b7ef43886193048efa2b1116cbf)
    #6 0x5594efe32ec6 in do_bind ldap/servers/slapd/bind.c:254
    #7 0x5594efe390b2 in connection_threadmain ldap/servers/slapd/connection.c:2058
    #8 0x7f8b7d77de02 in _pt_root ../../../../nspr/pr/src/pthreads/ptthread.c:191
    #9 0x7f8b7e4b4ee5 in asan_thread_start ../../../../libsanitizer/asan/asan_interceptors.cpp:239
    #10 0x7f8b7dfbe1d3 in start_thread (/lib64/libc.so.6+0x711d3) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)
    #11 0x7f8b7e040ceb in __GI___clone3 (/lib64/libc.so.6+0xf3ceb) (BuildId: 2b3c02fe7e4d3811767175b6f323692a10a4e116)

```
**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-3.1.3.202511190602git7df263085-1.fc43.x86_64

**Steps to Reproduce**
1. Run `dirsrvtests/tests/suites/ldapi` under AddressSanitizer.

### PR DESCRIPTION
**Pull request by vashirov**
Bug Description:
In `slapd_bind_local_user()` when checking LDAPI auth mappings, `slapi_search_internal_get_entry()` allocates and returns a duplicated entry. This entry was never freed before jumping to the `done:` label, causing a memory leak on each BIND operation.

Fix Description:
Free the duplicated `e` before jumping to the `done:` label.

Fixes: https://github.com/389ds/389-ds-base/issues/7115

## Summary by Sourcery

Bug Fixes:
- Release the duplicated entry returned during LDAPI auth mapping checks to prevent a per-BIND memory leak detected by LeakSanitizer.

### CODE REVIEW

**Review by mreynolds389 — APPROVED** [review]

File: ldap/servers/slapd/ldapi.c [hunk 1]
```diff
@@ -201,6 +201,7 @@ slapd_bind_local_user(Connection *conn)
                                                         NULL, NULL, NULL, NULL);
                         }
```
Comment (droideck) [inline ldap/servers/slapd/ldapi.c:204]: I think we might have another leak here for the case when account is locked, auth_dn is never passed to `bind_credentials_set_nolock()` (which assigns it to `conn`), nor is it explicitly freed.

Comment (vashirov) [reply ldap/servers/slapd/ldapi.c:204]: Right, I didn't encounter this case under ASAN, so I missed that.
I will add a test to reproduce this.

Comment (vashirov) [reply ldap/servers/slapd/ldapi.c:204]: `root_dn` is also leaked when root account is locked. I've added tests to verify these leaks under ASAN.
