### PR TITLE
Issue 6028 - vlv index keys inconsistencies

### LINKED ISSUE #6028: vlv index keys inconsistencies
**Issue Description**
When working on issue #6022 I discovered some inconsistencies that impact both bdb and lmdb 

**Package Version and Platform:**
 - Platform:  Fedora
 - Package and version: main branch

**Steps to Reproduce**
1. Go to 389-ds-base/dirsrvtests/tests/suites/vlv
2. Edit regression_test.py and comment  M2.restart() in test_vlv_cache_subdb_names
3. Run ( DEBUGGING=1 pytest -x $PWD -k test_vlv_cache_subdb_names) 
4. Run dbscan -f '$DBDIR/userroot/vlv#vlvidx.db' > keys.1
5. Run ( DEBUGGING=1 pytest -x $PWD -k 'test_bulk_import_when_the_backend_with_vlv_was_recreated or test_vlv_cache_subdb_names') 
6. Run dbscan -f '$DBDIR/userroot/vlv#vlvidx.db' > keys.2
7. compare keys.1 and keys.2
    See that keys.1 are the keys for the entries that matches (uid=*)
    See that keys.2 are the keys for the entries that matches (|(uid=*)(cn=*))

**Expected results**
Should have keys matching the same entries

### PR DESCRIPTION
**Pull request by progier389**
The issue is that reindexed vlv database are not cleared, so old keys remains
Solution: truncate the reindexed vlv sub database and its cache before starting the import engine.
Note: this is tested by:  dirsrvtests/tests/suites/vlv/regression_test.py::test_vlv_cache_subdb_names CI test

Issue #6028 

Reviewed by: @droideck (Thanks!)

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import.h [hunk 1]
```diff
@@ -157,6 +157,7 @@ int dbmdb_run_ldif2db(Slapi_PBlock *pb);
 
 
 /* mdb_import_threads.c */
+const char *attr_in_list(const char *search, char **list);
```
Comment (droideck) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_import.h]: This line seems to be unrelated to the change (and not mentioned in the commit message). Is it here by mistake or do I miss something?

**Review by droideck — APPROVED** [review]
The rest looks good! 
P.S. nice touch with the truncate_index_dbi callback!

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import.h (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_import.h]: You are right: this is a left over of a previous attempt that was using attr_in_list instead of is_reindex attr
I will remove it.
