### PR TITLE
Issue 5984 - Crash when paged result search are abandoned

### LINKED ISSUE #4551: Paged search impacts performance
**Issue Description**
When a server is under search load, a paged search from a regular user impacts the performance. 
Same paged search requested by DM has much smaller impact. 

**Package Version and Platform:**
 - Platform: Fedora 33
 - Package and version: 389-ds-base-1.4.4.9-1.fc33.x86_64. 

**Steps to Reproduce**
1. Create a db with 40000 users
2. Run search load using  `ldclt -D "uid=test,ou=people,dc=example,dc=com" -w test -e bindeach,esearch -b "ou=people,dc=example,dc=com" -f "uid=00001"`
3. While the search load is running, run paged search in a loop that requests all ids: 
`while : ; do ldapsearch -D "uid=test,ou=people,dc=example,dc=com" -w test -b dc=example,dc=com 'uid=*'  -E pr=100/noprompt; done `

**Actual results**
```
ldclt[1353]: Average rate: 2415.70/thr  (2415.70/sec), total:  24157 -- only ldclt is running 
ldclt[1353]: Average rate: 2342.50/thr  (2342.50/sec), total:  23425
ldclt[1353]: Average rate: 1048.90/thr  (1048.90/sec), total:  10489 -\
ldclt[1353]: Average rate:  413.10/thr  ( 413.10/sec), total:   4131   | paged search from a regular user
ldclt[1353]: Average rate:  461.00/thr  ( 461.00/sec), total:   4610   |
ldclt[1353]: Average rate: 1759.30/thr  (1759.30/sec), total:  17593 -/
ldclt[1353]: Average rate: 2374.70/thr  (2374.70/sec), total:  23747
ldclt[1353]: Average rate: 1952.70/thr  (1952.70/sec), total:  19527 -\
ldclt[1353]: Average rate: 1783.00/thr  (1783.00/sec), total:  17830   | paged search from DM
ldclt[1353]: Average rate: 1749.70/thr  (1749.70/sec), total:  17497 -/
ldclt[1353]: Average rate: 2319.80/thr  (2319.80/sec), total:  23198
ldclt[1353]: Average rate: 2378.80/thr  (2378.80/sec), total:  23788
```

**Expected results**
There shouldn't be a significant drop in performance.

**Additional information**
@wisebaldone who reported the issue, also mentioned that 1.2.11.15-48 doesn't have the issue and 1.2.11.15-97 does have.

### LINKED ISSUE #5984: Crash when paged result search are abandoned
**Issue Description**
The fact that the paged result search is now using a lock different than the connection lock introduced a race condition 
  with the ABANDON operation leading to a double free that usually leads to an heap corruption and  a crash (SIGSEGV)
Note:  a signature of that crash is that:
 strings -a `path_of_core_file`  | grep 'ABANDON targetop=Simple Paged Results' 
displays some results (if access log is not disabled)

**Package Version and Platform:**
 - Platform: Any
 - Package and version: Unfortunately all branches released after July 2023 are impacted 

**Steps to Reproduce**
Will provide a CI test but the idea is to have a relatively long paged result search and abandoning it while it is sending entries.

**Expected results**
No crash !

### PR DESCRIPTION
**Pull request by progier389**
Problem:
  Fix #4551 has changed the lock that protects the paged result data
  within a connection. But the abandon operation attempts to free
  the paged search result with the connection lock.
  This leads to race condition and double free causing an heap
  corruption and a SIGSEGV.

  Solution:
   - Get a copy of the operation data that needs to be logged.
   - Unlock the connection mutex (to avoid deadlock risk)
   - Free the paged result while holding the paged result lock.

Issue: 5984

Reviewed by: @tbordaz  (Thanks!)

### CODE REVIEW

File: ldap/servers/slapd/opshared.c [hunk 1]
```diff
@@ -921,9 +921,7 @@ op_shared_search(Slapi_PBlock *pb, int send_result)
                     next_be = NULL; /* to break the loop */
                     if (operation->o_status & SLAPI_OP_STATUS_ABANDONED) {
                         /* It turned out this search was abandoned. */
-                        pthread_mutex_lock(pagedresults_mutex);
-                        pagedresults_free_one_msgid_nolock(pb_conn, operation->o_msgid);
-                        pthread_mutex_unlock(pagedresults_mutex);
+                        pagedresults_free_one_msgid(pb_conn, operation->o_msgid, pagedresults_mutex);
```
Comment (tbordaz) [inline ldap/servers/slapd/opshared.c:924]: IIUC it looks to me that pagedresults_mutex is set if it is an paged result search.
In case of abandon (not paged result) how is it set ?

File: ldap/servers/slapd/pagedresults.c [hunk 2]
```diff
@@ -350,7 +354,7 @@ pagedresults_free_one(Connection *conn, Operation *op, int index)
  * Used for abandoning - pageresult_lock_get_addr(conn) is already locked in do_abandone.
  */
 int
-pagedresults_free_one_msgid_nolock(Connection *conn, ber_int_t msgid)
+pagedresults_free_one_msgid(Connection *conn, ber_int_t msgid, pthread_mutex_t *mutex)
```
Comment (tbordaz) [inline ldap/servers/slapd/pagedresults.c:357]: Why not retrieving the mutex in the function itself with pageresult_lock_get_addr(conn) ?

File: ldap/servers/slapd/pagedresults.c [hunk 3]
```diff
@@ -361,6 +365,7 @@ pagedresults_free_one_msgid_nolock(Connection *conn, ber_int_t msgid)
         } else {
             slapi_log_err(SLAPI_LOG_TRACE,
                           "pagedresults_free_one_msgid_nolock", "=> msgid=%d\n", msgid);
+            pthread_mutex_lock(mutex);
```
Comment (tbordaz) [inline ldap/servers/slapd/pagedresults.c:368]: A dummy question not related to that specific line.
The "random" mutex is taken from a hash table based on the 'conn' value (pageresult_lock_get_addr). How can we be sure there is no collision ?
For example, two different connections using the same mutex.

Another question, I believe it is possible to have several paged result searches on the same connection. Any risk they are stepping on each over toes ? I mean lock/unlock the same mutex

File: ldap/servers/slapd/abandon.c [hunk 4]
```diff
@@ -130,7 +140,8 @@ do_abandon(Slapi_PBlock *pb)
         slapi_log_err(SLAPI_LOG_TRACE, "do_abandon", "op not found\n");
     }
 
-    if (0 == pagedresults_free_one_msgid_nolock(pb_conn, id)) {
+    pthread_mutex_unlock(&(pb_conn->c_mutex));
```
Comment (tbordaz) [inline ldap/servers/slapd/abandon.c:143]: Does that mean that one of the possible symptom was a deadlock ?

File: ldap/servers/slapd/abandon.c [hunk 5]
```diff
@@ -130,7 +140,8 @@ do_abandon(Slapi_PBlock *pb)
         slapi_log_err(SLAPI_LOG_TRACE, "do_abandon", "op not found\n");
     }
 
-    if (0 == pagedresults_free_one_msgid_nolock(pb_conn, id)) {
```
Comment (tbordaz) [inline ldap/servers/slapd/abandon.c:133]: IIUC here was the culprit of the crashes. We freed using c_mutex instead of paged_result_mutex. Correct ?

**Review by tbordaz — COMMENTED** [review]
The overall fix looks good to me.
I added few comments/questions to clarify my understanding.

File: ldap/servers/slapd/pagedresults.c (hunk 3 above)
Comment (progier389) [reply ldap/servers/slapd/pagedresults.c:368]: Indeed in both these scenarios different threads will use the same mutex and there will be some lock contention.
But that is the finality of a mutex and the contention is smaller with an array of mutexes than with a single one !

File: ldap/servers/slapd/pagedresults.c (hunk 2 above)
Comment (progier389) [reply ldap/servers/slapd/pagedresults.c:357]: Why recomputing the hash in the function when the caller already have computed it ( as in opshared.c case ) ?

File: ldap/servers/slapd/opshared.c (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/opshared.c:924]: Abandon code does not use `pagedresults_mutex` but  `pageresult_lock_get_addr(pb_conn)`
which will return one of the mutex of the hash array initialized during the server startup
(whether there are paged search result associated with the connection or not ... )

File: ldap/servers/slapd/abandon.c (hunk 4 above)
Comment (progier389) [reply ldap/servers/slapd/abandon.c:143]: Well everything is possible after an heap corruption but deadlock is really very improbable, because the previous code was not locking at all (causing the race condition and the heap corruption) 
But my first idea was to simply protect the pagedresults_free_one_msgid_nolock with the paged mutex lock and I realized that this could generate deadlock if the connection mutex was not freed before.

File: ldap/servers/slapd/abandon.c (hunk 5 above)
Comment (progier389) [reply ldap/servers/slapd/abandon.c:133]: Yes

File: ldap/servers/slapd/pagedresults.c (hunk 3 above)
Comment (tbordaz) [reply ldap/servers/slapd/pagedresults.c:368]: Yes that make sense. The target was to reduce the contention. thanks

File: ldap/servers/slapd/pagedresults.c (hunk 2 above)
Comment (tbordaz) [reply ldap/servers/slapd/pagedresults.c:357]: exact

File: ldap/servers/slapd/opshared.c (hunk 1 above)
Comment (tbordaz) [reply ldap/servers/slapd/opshared.c:924]: Sorry, my question was confusing. The call (pagedresults_free_one_msgid) uses pagedresults_mutex and I thought that pagedresults_mutex was not initialized. But I was wrong, we are in a 'op_is_pagedresults' block where pagedresults_mutex is initialized.
Sorry for the noise

**Review by tbordaz — APPROVED** [review]
The C code looks good to me
