### PR TITLE
Issue 6347 - better fix for desyncronized vlv cache

### LINKED ISSUE #6347: VLV search sometime fails with operation error
**Issue Description**
https://issues.redhat.com/browse/RHCS-5299
VLV search sometime fails with LDAP_OPERATION error 
And error log contains 
`ERR - vlv_build_idl - Can't follow db cursor (err -12797)
`

**Package Version and Platform:**
 - Platform: [e.g. Fedora] Fedora 40 
 - Package and version: [e.g. 389-ds-base-3.0.1.2

**Steps to Reproduce**
1.  Prepare a F40 test machine
`1minutetip 1MT-Fedora-40`
2. . Install and launch the following script
```
#!/bin/bash
git clone https://github.com/freeipa/freeipa.git
cd freeipa/
dnf builddep -D "with_wheels 1" -D "with_lint 1" -D "with_doc 1" --spec freeipa.spec.in --best --allowerasing --setopt=install_weak_deps=False -y
bash makerpms.sh
dnf localinstall dist/rpms/* -y
ipa-server-install -a password -p dmpassword -r EXAMPLE.TEST -U --setup-dns --allow-zone-overlap --no-forwarders -N --auto-reverse --random-serial-numbers
mkdir ~/.ipa
cp /etc/ipa/default.conf  ~/.ipa
cp /etc/ipa/ca.crt  ~/.ipa
echo password | kinit admin
PYTHONPATH=. ipatests/ipa-run-tests -sv test_xmlrpc/test_cert_plugin.py
grep vlv_build_idl /var/log/dirsrv/slapd-EXAMPLE-TEST/errors
```
3. See the errors:
   - Some tests are FAIL
   - Error log show message like:
`
 [17/Sep/2024:18:54:05.250571209 +0000] - ERR - vlv_build_idl - Can't follow db cursor (err -12797)
`
   - Access log shows that a VLV operation fails with err=1 
```
   [26/Sep/2024:10:32:12.175793074 -0400] conn=17 op=315 SRCH base="ou=certificateRepository,ou=ca,o=ipaca" scope=1 filter="(certStatus=*)" attrs=ALL
[26/Sep/2024:10:32:12.179149635 -0400] conn=17 op=315 VLV 0:100:A None
[26/Sep/2024:10:32:12.179157931 -0400] conn=17 op=315 SORT serialno
[26/Sep/2024:10:32:12.179836172 -0400] conn=17 op=315 RESULT err=1 tag=101 nentries=0 wtime=0.000129631 optime=0.004046465 etime=0.004173324
```
Note: the VLV and SORT control may be missing becaise of https://github.com/389ds/389-ds-base/issues/6328
    Error lo

**Expected result**
All tests are PASS
Search should success
And no error should be logged. 

***See Also ***
Triaged: https://issues.redhat.com/browse/IDMDS-4698

### PR DESCRIPTION
**Pull request by progier389**
A better fix than [PR 6349](https://github.com/389ds/389-ds-base/pull/6349) about corrupted vlv cache
Problem is a race condition because txn was released while building the cache. 
Solution keep the write txn open until the cache is fully rebuilt.
Also fixed some debug logs
And also added the source of a tool useful to check the vlv cache consistency
Note: this remove PR #6349 and integrate PR #6356 

Issue: #6347 

Reviewed by @tbodaz (Thanks!)

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c [hunk 1]
```diff
@@ -533,7 +549,7 @@ void dbmdb_log_dbi_set_fn(const char *file, int lineno, const char *funcname, co
     Dl_info info = {0};
     dladdr(fn, &info);
     /* Cannot use dbi_str here because slot is not yet up2date (so dbname is an argument) */
-    dbg_log(file, lineno, funcname, DBGMDB_LEVEL_MDBAPI,  "%s(txn=0x%p, dbi=%d <%s>, fn=0x%p <%s>)\n", action, txn, dbi, dbname, fn, info.dli_sname);
+    dbg_log(file, lineno, funcname, DBGMDB_LEVEL_MDBAPI, "%s(txn=0x%p, dbi=%d <%s>, fn=0x%p <%s>)\n", action, txn, dbi, dbname, fn, info.dli_sname);
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c:552]: Why not calling txn_loglvl() instead of DBGMDB_LEVEL_MDBAPI?

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c [hunk 2]
```diff
@@ -2131,31 +2132,13 @@ void *dbmdb_recno_cache_build(void *arg)
...
-        } else {
-            rc = MDB_CURSOR_GET(txn_ctx.cursor, &key, &data, MDB_SET);
-            if (rc == MDB_NOTFOUND) {
-                rc = MDB_CURSOR_GET(txn_ctx.cursor, &key, &data, MDB_SET_RANGE);
-            }
-        }
-        if (rc) {
-            break;
-        }
+        if (recno % RECNO_CACHE_INTERVAL == 1) {
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c:2141]: Is it good indentation here ?

**Review by tbordaz — APPROVED** [review]
Only cosmetic points. LGTM

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_debug.c:552]: txn_log() is used only for txn  related function It allows to log when txn are open and closed when 
 DBGMDB_LEVEL_MDBAPI or DBGMDB_LEVEL_TXN is set but log txn backtrace only if DBGMDB_LEVEL_TXN is set

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c (hunk 2 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/db-mdb/mdb_layer.c:2141]: Good catch!
