### PR TITLE
Issue 7358 - NSACLPlugin - acl_access_allowed - Missing aclpb 1

### LINKED ISSUE #7358: IPA test failure - NSACLPlugin - acl_access_allowed - Missing aclpb    1
**Issue Description**
FreeIPA nightly tests detected a regression with the 389ds version shipped in the copr repository @389ds/389-ds-base-nightly

The addition of a DNS zone with dnssec enabled fails to trigger the signing of the zone. The syncrepl_poll calls fails with OPERATIONS_ERROR.

**Package Version and Platform:**
 - Platform: Fedora 43
 - Package and version: 389-ds-base-3.2.0.202603202348gitc9dc8ba99-1.fc43.x86_64

**Steps to Reproduce**
1. Install ipa server with:
```
dnf copr enable -y @389ds/389-ds-base-nightly
dnf copr enable -y @freeipa/freeipa-master-nightly
dnf install -y freeipa-server-dns
ipa-server-install --domain ipa.test --realm IPA.TEST -a Secret123 -p Secret123 -U
echo Secret123 | kinit admin
ipa-dns-install --dnssec-master --forwarder 10.11.5.160 -U
```
2. Add a signed zone
```
ipa dnszone-add example.test --dnssec true
```

**Expected results**
The zone should be signed.

The journal shows an error in syncrepl_poll:
```
Mar 23 10:07:00 server.ipa.test [57029]: GSSAPI client step 1
Mar 23 10:07:00 server.ipa.test [57029]: GSSAPI client step 1
Mar 23 10:07:00 server.ipa.test [57029]: GSSAPI client step 1
Mar 23 10:07:00 server.ipa.test ns-slapd[55095]: [23/Mar/2026:10:07:00.727171179 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]: Traceback (most recent call last):
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:   File "/usr/libexec/ipa/ipa-dnskeysyncd", line 130, in <module>
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:     while ldap_connection.syncrepl_poll(all=1, msgid=ldap_search):
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 23 10:07:00 server.ipa.test ns-slapd[55095]: [23/Mar/2026:10:07:00.732888066 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:   File "/usr/lib64/python3.14/site-packages/ldap/syncrepl.py", line 403, in syncrepl_poll
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:     type, msg, mid, ctrls, n, v = self.result4(
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:                                   ~~~~~~~~~~~~^
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:         msgid=msgid,
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:         ^^^^^^^^^^^^
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:     ...<3 lines>...
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:         all=0,
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:         ^^^^^^
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:     )
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:     ^
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:   File "/usr/lib64/python3.14/site-packages/ldap/ldapobject.py", line 553, in result4
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:     ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:   File "/usr/lib64/python3.14/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]:     result = func(*args,**kwargs)
Mar 23 10:07:00 server.ipa.test ipa-dnskeysyncd[57870]: ldap.OPERATIONS_ERROR: {'msgtype': 101, 'msgid': 4, 'result': 1, 'desc': 'Operations error', 'ctrls': []}
Mar 23 10:07:00 server.ipa.test ns-slapd[55095]: [23/Mar/2026:10:07:00.735126757 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1
Mar 23 10:07:00 server.ipa.test ns-slapd[55095]: [23/Mar/2026:10:07:00.737609147 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1
Mar 23 10:07:00 server.ipa.test ns-slapd[55095]: [23/Mar/2026:10:07:00.740230731 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1
Mar 23 10:07:00 server.ipa.test ns-slapd[55095]: [23/Mar/2026:10:07:00.743562011 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1
Mar 23 10:07:00 server.ipa.test ns-slapd[55095]: [23/Mar/2026:10:07:00.745478528 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1
Mar 23 10:07:00 server.ipa.test ns-slapd[55095]: [23/Mar/2026:10:07:00.755281128 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1
Mar 23 10:07:00 server.ipa.test ns-slapd[55095]: [23/Mar/2026:10:07:00.765128925 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1
Mar 23 10:07:00 server.ipa.test /mod_wsgi[57029]: [🡕] [IPA.API] admin@IPA.TEST: dnszone_add: SUCCESS [ldap2_140707569713568] {"idnsname": {"__dns_name__": "example.test."}, "idnssoarname": {"__dns_name__": "hostmaster"}, "idnssoarefresh": 3600, "idnssoaretry": 900, "idnssoaexpire": 1209600, "idnssoaminimum": 3600, "idnsupdatepolicy": "grant IPA.TEST krb5-self * A; grant IPA.TEST krb5-self * AAAA; grant IPA.TEST krb5-self * SSHFP;", "idnsallowdynupdate": false, "idnsallowquery": "any;", "idnsallowtransfer": "none;", "idnssecinlinesigning": true, "skip_overlap_check": false, "force": false, "skip_nameserver_check": false, "all": false, "raw": false, "version": "2.257"}
Mar 23 10:07:00 server.ipa.test systemd[1]: ipa-dnskeysyncd.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 10:07:00 server.ipa.test systemd[1]: ipa-dnskeysyncd.service: Failed with result 'exit-code'.
Mar 23 10:07:00 server.ipa.test audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=ipa-dnskeysyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mar 23 10:07:00 server.ipa.test systemd[1]: ipa-dnskeysyncd.service: Consumed 1.549s CPU time, 75.2M memory peak.
Mar 23 10:07:13 server.ipa.test systemd[1]: systemd-hostnamed.service: Deactivated successfully.
Mar 23 10:07:13 server.ipa.test audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 23 10:07:13 server.ipa.test audit: BPF prog-id=917 op=UNLOAD
```

and 389ds error log also displays some errors:
```
[23/Mar/2026:10:04:49.520568570 -0400] - ERR - NSACLPlugin - acl_access_allowed - Missing aclpb    1 
```

This may be related to this recent commit on 389ds: https://github.com/389ds/389-ds-base/commit/3d6977e254ad566711e2ea2399135eb8e7f8a073

### PR DESCRIPTION
**Pull request by vashirov**
Bug Description:
`sync_pblock_copy()` creates a new operation using `slapi_operation_new(0)` without calling `factory_create_extension()`, so the ACL pblock extension is never initialized. When the sync-send thread evaluates a filter with access checks finds no aclpb and logs 'Missing aclpb 1', returning LDAP_OPERATIONS_ERROR to the client.

Fix Description:
Call `factory_create_extension()` after creating the new operation so that all operation extensions (including the ACL pblock) are properly initialized. Also copy SLAPI_REQUESTOR_DN so that ACL checks evaluate against the correct bind identity.

Fixes: https://github.com/389ds/389-ds-base/issues/7358

## Summary by Sourcery

Ensure sync plugin operations are created with fully initialized extensions and correct requestor identity for ACL evaluation.

Bug Fixes:
- Initialize operation extensions when creating sync operations so the ACL pblock is present and access checks no longer fail with 'Missing aclpb 1'.
- Propagate the original requestor DN into cloned sync operations so ACL checks run under the correct bind identity.

### CODE REVIEW

**Review by progier389 — APPROVED** [review]
LGTM

File: ldap/servers/plugins/sync/sync_util.c [hunk 1]
```diff
@@ -907,6 +909,7 @@ sync_pblock_copy(Slapi_PBlock *src)
     slapi_operation_set_msgid(operation_new, msgid);
     tag = slapi_operation_get_tag(operation);
     slapi_operation_set_tag(operation_new, tag);
+    operation_new->o_extension = factory_create_extension(get_operation_object_type(), operation_new, connection);
```
Comment (tbordaz) [inline ldap/servers/plugins/sync/sync_util.c:914]: Do you think we could use internal_operation_new rather than slapi_connection_new ?

Comment (progier389) [reply ldap/servers/plugins/sync/sync_util.c:914]: IMHO the answer depend whether we want to bypass acl checking or not
 (acl checking is bypassed in internal operations)

Comment (vashirov) [reply ldap/servers/plugins/sync/sync_util.c:914]: Comment here says we should verify access:
https://github.com/389ds/389-ds-base/blob/bd7aafeae1e603441f1967126981762ecde94635/ldap/servers/plugins/sync/sync_persist.c#L1007-L1016
So I guess we don't want to bypass it.

**Review by droideck — APPROVED** [review]
LGTM!

The only "concern" I have that the issue was introduced after commit 3d6977e removed the be == NULL → skip safety net from acl_skip_access_check(), hence the code now proceeds to full ACL evaluation.

Your fix works for our case and the `Missing aclpb 1` error is gone, but I think it'll be cleaner to copy SLAPI_BACKEND for completeness. The original search knows its backend, and the persistent thread operates on entries from that backend.
