### PR TITLE
Issue 6778 - Memory leak in roles_cache_create_object_from_entry

### LINKED ISSUE #6778: Memory leak in roles_cache_create_object_from_entry
**Issue Description**
```
=================================================================
==15730==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fdebaab4a07 in __interceptor_malloc (/lib64/libasan.so.6+0xb4a07)
    #1 0x7fdeba598168 in slapi_ch_malloc (/usr/lib64/dirsrv/libslapd.so.0+0x198168)
    #2 0x7fdeba5a93f7 in slapi_sdn_new (/usr/lib64/dirsrv/libslapd.so.0+0x1a93f7)
    #3 0x7fdeb2f0e32b in roles_cache_create_object_from_entry ldap/servers/plugins/roles/roles_cache.c:1115
    #4 0x7fdeb2f0e32b in roles_cache_create_role_under ldap/servers/plugins/roles/roles_cache.c:998
    #5 0x7fdeb2f0e96e in roles_cache_add_entry_cb ldap/servers/plugins/roles/roles_cache.c:964
    #6 0x7fdeba614d5b in send_ldap_search_entry_ext ldap/servers/slapd/result.c:1593
    #7 0x7fdeba615233 in send_ldap_search_entry (/usr/lib64/dirsrv/libslapd.so.0+0x215233)
    #8 0x7fdeba644001 in send_results_ext.constprop.0 ldap/servers/slapd/opshared.c:1162
    #9 0x7fdeba5f09d2 in op_shared_search (/usr/lib64/dirsrv/libslapd.so.0+0x1f09d2)
    #10 0x7fdeba60176f  (/usr/lib64/dirsrv/libslapd.so.0+0x20176f)
    #11 0x7fdeb2f0f63d in roles_cache_add_roles_from_suffix ldap/servers/plugins/roles/roles_cache.c:936
    #12 0x7fdeb2f0f733 in roles_cache_init ldap/servers/plugins/roles/roles_cache.c:210
    #13 0x7fdeb2f0f8cc in roles_start ldap/servers/plugins/roles/roles_plugin.c:174
    #14 0x7fdeba5f9c6d in plugin_call_func ldap/servers/slapd/plugin.c:2001
    #15 0x7fdeba5fad8b in plugin_call_one ldap/servers/slapd/plugin.c:1950
    #16 0x7fdeba5fad8b in plugin_dependency_startall ldap/servers/slapd/plugin.c:1705
    #17 0x564fb8aac5c0 in main (/usr/sbin/ns-slapd+0xac5c0)
    #18 0x7fdeba0295cf in __libc_start_call_main (/lib64/libc.so.6+0x295cf)
    #19 0x7fdeba02967f in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2967f)
    #20 0x564fb8ab0494 in _start (/usr/sbin/ns-slapd+0xb0494)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fdebaa5baf7 in strdup (/lib64/libasan.so.6+0x5baf7)
    #1 0x7fdeba59ab6d in slapi_ch_strdup (/usr/lib64/dirsrv/libslapd.so.0+0x19ab6d)
    #2 0x7fdeba5aa416 in slapi_sdn_copy (/usr/lib64/dirsrv/libslapd.so.0+0x1aa416)
    #3 0x7fdeb2f0e352 in roles_cache_create_object_from_entry ldap/servers/plugins/roles/roles_cache.c:1116
    #4 0x7fdeb2f0e352 in roles_cache_create_role_under ldap/servers/plugins/roles/roles_cache.c:998
    #5 0x7fdeb2f0e96e in roles_cache_add_entry_cb ldap/servers/plugins/roles/roles_cache.c:964
    #6 0x7fdeba614d5b in send_ldap_search_entry_ext ldap/servers/slapd/result.c:1593
    #7 0x7fdeba615233 in send_ldap_search_entry (/usr/lib64/dirsrv/libslapd.so.0+0x215233)
    #8 0x7fdeba644001 in send_results_ext.constprop.0 ldap/servers/slapd/opshared.c:1162
    #9 0x7fdeba5f09d2 in op_shared_search (/usr/lib64/dirsrv/libslapd.so.0+0x1f09d2)
    #10 0x7fdeba60176f  (/usr/lib64/dirsrv/libslapd.so.0+0x20176f)
    #11 0x7fdeb2f0f63d in roles_cache_add_roles_from_suffix ldap/servers/plugins/roles/roles_cache.c:936
    #12 0x7fdeb2f0f733 in roles_cache_init ldap/servers/plugins/roles/roles_cache.c:210
    #13 0x7fdeb2f0f8cc in roles_start ldap/servers/plugins/roles/roles_plugin.c:174
    #14 0x7fdeba5f9c6d in plugin_call_func ldap/servers/slapd/plugin.c:2001
    #15 0x7fdeba5fad8b in plugin_call_one ldap/servers/slapd/plugin.c:1950
    #16 0x7fdeba5fad8b in plugin_dependency_startall ldap/servers/slapd/plugin.c:1705
    #17 0x564fb8aac5c0 in main (/usr/sbin/ns-slapd+0xac5c0)
    #18 0x7fdeba0295cf in __libc_start_call_main (/lib64/libc.so.6+0x295cf)
    #19 0x7fdeba02967f in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2967f)
    #20 0x564fb8ab0494 in _start (/usr/sbin/ns-slapd+0xb0494)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fdebaa5baf7 in strdup (/lib64/libasan.so.6+0x5baf7)
    #1 0x7fdeba59ab6d in slapi_ch_strdup (/usr/lib64/dirsrv/libslapd.so.0+0x19ab6d)
    #2 0x7fdeba5aa3e6 in slapi_sdn_copy (/usr/lib64/dirsrv/libslapd.so.0+0x1aa3e6)
    #3 0x7fdeb2f0e352 in roles_cache_create_object_from_entry ldap/servers/plugins/roles/roles_cache.c:1116
    #4 0x7fdeb2f0e352 in roles_cache_create_role_under ldap/servers/plugins/roles/roles_cache.c:998
    #5 0x7fdeb2f0e96e in roles_cache_add_entry_cb ldap/servers/plugins/roles/roles_cache.c:964
    #6 0x7fdeba614d5b in send_ldap_search_entry_ext ldap/servers/slapd/result.c:1593
    #7 0x7fdeba615233 in send_ldap_search_entry (/usr/lib64/dirsrv/libslapd.so.0+0x215233)
    #8 0x7fdeba644001 in send_results_ext.constprop.0 ldap/servers/slapd/opshared.c:1162
    #9 0x7fdeba5f09d2 in op_shared_search (/usr/lib64/dirsrv/libslapd.so.0+0x1f09d2)
    #10 0x7fdeba60176f  (/usr/lib64/dirsrv/libslapd.so.0+0x20176f)
    #11 0x7fdeb2f0f63d in roles_cache_add_roles_from_suffix ldap/servers/plugins/roles/roles_cache.c:936
    #12 0x7fdeb2f0f733 in roles_cache_init ldap/servers/plugins/roles/roles_cache.c:210
    #13 0x7fdeb2f0f8cc in roles_start ldap/servers/plugins/roles/roles_plugin.c:174
    #14 0x7fdeba5f9c6d in plugin_call_func ldap/servers/slapd/plugin.c:2001
    #15 0x7fdeba5fad8b in plugin_call_one ldap/servers/slapd/plugin.c:1950
    #16 0x7fdeba5fad8b in plugin_dependency_startall ldap/servers/slapd/plugin.c:1705
    #17 0x564fb8aac5c0 in main (/usr/sbin/ns-slapd+0xac5c0)
    #18 0x7fdeba0295cf in __libc_start_call_main (/lib64/libc.so.6+0x295cf)
    #19 0x7fdeba02967f in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2967f)
    #20 0x564fb8ab0494 in _start (/usr/sbin/ns-slapd+0xb0494)

SUMMARY: AddressSanitizer: 136 byte(s) leaked in 3 allocation(s).
```

Reproducible with dirsrvtests/tests/suites/roles/basic_test.py

### PR DESCRIPTION
**Pull request by vashirov**
Bug Description:
`this_role` has internal allocations (`dn`, `rolescopedn`, etc.) that are not freed.

Fix Description:
Use `roles_cache_role_object_free` to free `this_role` and all its internal structures.

Fixes: https://github.com/389ds/389-ds-base/issues/6778

### CODE REVIEW

**Comment by vashirov** [comment]
Ugh, checks are failing because of the incompatible pointer types, working on it...

File: ldap/servers/plugins/roles/roles_cache.c [hunk 1]
```diff
@@ -1098,7 +1098,7 @@ roles_cache_create_object_from_entry(Slapi_Entry *role_entry, role_object **resu
     /* We determine the role type by reading the objectclass */
     if (roles_cache_is_role_entry(role_entry) == 0) {
         /* Bad type */
-        slapi_ch_free((void **)&this_role);
+        roles_cache_role_object_free(this_role);
```
Comment (mreynolds389) [inline ldap/servers/plugins/roles/roles_cache.c]: You need to cast these to avoid compiler warnings:  

    roles_cache_role_object_free((caddr_t)this_role));

**Review by mreynolds389 — CHANGES_REQUESTED** [review]

File: ldap/servers/plugins/roles/roles_cache.c (hunk 1 above)
Comment (vashirov) [reply ldap/servers/plugins/roles/roles_cache.c]: Yeah, didn't catch these on 389-ds-base-2.5 branch.

**Review by mreynolds389 — APPROVED** [review]
Thanks, ack
