### PR TITLE
Issue 6507 - changelog modifiers operation not displayed in dbscan

### LINKED ISSUE #6507: changelog modifiers operation not displayed in dbscan
**Issue Description**
When dumping a changelog file with dbscan, in modify operation the modifiers operation (add/delete/replace) are not listed
 (i.e deleting an attribute looks the same than adding one)

**Package Version and Platform:**
 - Platform: [e.g. Fedora]
 - Package and version: main

**Steps to Reproduce**
1. Set up multi master instances and perform some modify operations
2. Run 'dbscan -f  /var/lib/dirsrv/slapd-supplier1/db/userroot/replication_changelog.db'
4. See error: the modifier list does not specify the modifier operation (add/delete/replace)

**Expected results**
modifier list should be displayed as in ldif

**Additional context**

All versions existing are impacted

https://issues.redhat.com/browse/RHEL-61353
https://issues.redhat.com/browse/IDMDS-4856

### PR DESCRIPTION
**Pull request by progier389**
Problem: when dbscan dumps the changelog, it does not display modify operation modifier sub operation
 (i.e: add/delete/replace) on the specified attribute
 
 Solution:
   Use a format similar to the ldif one:
```
    suboperation: type
    type: value
    ...
    -
```
but only when dumpoing a modify operation : add and modrdn still use the 
```
   type:value
   ...
```
format

Issue: #6507 

Reviewd by: @mreynolds389, @tbordaz  (Thanks!)

### CODE REVIEW

**Review by mreynolds389 — APPROVED** [review]

File: ldap/servers/slapd/tools/dbscan.c [hunk 1]
```diff
@@ -516,6 +521,10 @@ _cl5ReadMod(char **buff)
     val_count = ntohl(val_count);
     pos += sizeof(uint32_t);
 
+    op &= LDAP_MOD_OP;
+    if (print_op && op < PR_ARRAY_SIZE(ops)) {
```
Comment (tbordaz) [inline ldap/servers/slapd/tools/dbscan.c:525]: It should be the case but just for safety you may check that op>0

**Review by tbordaz — APPROVED** [review]
LGTM as well
