### PR TITLE
Issue 7291 - Crash when configuring a replica with an incorrect nsds5ReplicaRoot

### LINKED ISSUE #7291: Crash when configuring a replica with an incorrect nsds5ReplicaRoot
**Issue Description**
RHDS is crashing when trying to manually configure a replica and the replicaRoot is incorrect.

**Package Version and Platform:**
 - Package and version: main branch

**Steps to Reproduce**
1. Create an instance and define a suffix ( eg: dc=example,dc=com )
2. Define a replica with an incorrect setting for the replicaRoot
```
cat /var/tmp/consumer_conf.ldif
dn: cn=replica,cn=dc\3Dexample\2Cdc\3Dcom,cn=mapping tree,cn=config
objectclass: top
objectclass: nsds5replica
objectclass: extensibleObject
cn: replica
nsds5replicaroot: o=test
nsds5replicaid: 65535
nsds5replicatype: 2
nsds5ReplicaBindDN: cn=replication manager,cn=config
nsds5flags: 0
```
3. ldapmodify -x -D "cn=Directory Manager" -w password  -H ldaps://localhost:5636 -a -f /var/tmp/consumer_conf.ldif
5. adding new entry "cn=replica,cn=dc\3Dexample\2Cdc\3Dcom,cn=mapping tree,cn=config"
ldap_result: Can't contact LDAP server (-1)

**Expected results**
No crash and a message stating that the replicaRoot does not exist

**Additional context**
Reported by @mirielka

### PR DESCRIPTION
**Pull request by jchapma**
Description:
Configuring a replica when the replica_root does not exist, results in a NULL mapping tree node extension, which is deferenced without checking for NULL.

Fix:
Add a  NULL check, log an error message, return LDAP_UNWILLING_TO_PERFORM.

Fixes: https://github.com/389ds/389-ds-base/issues/7291

Reviewed by:

## Summary by Sourcery

Bug Fixes:
- Prevent a crash when configuring a replica with a non-existent replica root by checking for a NULL mapping tree node extension and aborting cleanly.

### CODE REVIEW

**Review by progier389 — APPROVED** [review]
LGTM

File: ldap/servers/plugins/replication/repl5_replica_config.c [hunk 1]
```diff
@@ -200,7 +200,17 @@ replica_config_add(Slapi_PBlock *pb __attribute__((unused)),
...
 
     mtnode_ext = _replica_config_get_mtnode_ext(e);
-    PR_ASSERT(mtnode_ext);
+    if (!mtnode_ext) {
+        if (errortext) {
+            PR_snprintf(errortext, SLAPI_DSE_RETURNTEXT_SIZE,
+                        "replica root '%s' does not exist", replica_root);
+        }
+        slapi_log_err(SLAPI_LOG_ERR, repl_plugin_name,
+                    "replica_config_add - replica root %s does not exist\n",
```
Comment (mreynolds389) [inline ldap/servers/plugins/replication/repl5_replica_config.c]: Indentation is off :-)   Otherwise LGTM as well

**Review by mreynolds389 — APPROVED** [review]

File: ldap/servers/plugins/replication/repl5_replica_config.c [hunk 2]
```diff
@@ -200,7 +200,17 @@ replica_config_add(Slapi_PBlock *pb __attribute__((unused)),
...
+                    replica_root);
+        *returncode = LDAP_UNWILLING_TO_PERFORM;
+        goto done;
```
Comment (droideck) [inline ldap/servers/plugins/replication/repl5_replica_config.c:210]: Kind of a preexisting issue.

When mtnode_ext is NULL and we `goto done`, the DN added by `replica_add_by_dn(replica_root)` is never removed from the hash.
IIUC, we need to move `replica_delete_by_dn(replica_root)` to `done:` or call it before `goto done`.

File: ldap/servers/plugins/replication/repl5_replica_config.c [hunk 3]
```diff
@@ -200,7 +200,17 @@ replica_config_add(Slapi_PBlock *pb __attribute__((unused)),
     replica_add_by_dn(replica_root);
 
     mtnode_ext = _replica_config_get_mtnode_ext(e);
-    PR_ASSERT(mtnode_ext);
+    if (!mtnode_ext) {
+        if (errortext) {
```
Comment (droideck) [inline ldap/servers/plugins/replication/repl5_replica_config.c]: Surrounding code has a bit different style. IMO, worth aligning it. 

```suggestion
        if (errortext != NULL) {
```

**Comment by progier389** [comment]
Looks good after https://github.com/389ds/389-ds-base/pull/7292/commits/59396791aca90bd95cd1652950fd0f2d2806a180 commit
