### PR TITLE
Ticket 4326 - entryuuid fixup did not work correctly

### LINKED ISSUE #4326: entryuuid fixup doesn't work correctly
In a minor piece of oversight, it appears the entryuuid fixup task doesn't work. This was due to my misinterpretation of the memberof fixup task and how it worked.

This should be corrected.

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: due to an oversight in how fixup tasks
worked, the entryuuid fixup task did not work correctly and
would not persist over restarts.

Fix Description: Correctly implement entryuuid fixup.

fixes: #4326

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

File: src/plugins/entryuuid/src/lib.rs [hunk 1]
```diff
@@ -187,9 +187,46 @@ impl SlapiPlugin3 for EntryUuid {
...
+            sdn.to_dn_string()
+        );
+        return Ok(());
+    }
+
+    // Setup the modifications
+    let mut mods = SlapiMods::new();
+
+    let u: Uuid = Uuid::new_v4();
+    let uuid_value = Value::from(&u);
```
Comment (tbordaz) [inline src/plugins/entryuuid/src/lib.rs:208]: I thought uuid_value was derived from nsuniqueid. Does 'u' contains the nsuniqueid ?

**Review by mreynolds389 — APPROVED** [review]
LGTM

File: src/plugins/entryuuid/src/lib.rs (hunk 1 above)
Comment (Firstyear) [reply src/plugins/entryuuid/src/lib.rs:208]: No, it's generated seperately. Uuid::new_v4() is what creates a new randomised UUID, and &u is a reference to that. :)
