### PR TITLE
Issue 5346 - New connection table fails with ASAN failures

### LINKED ISSUE #5346: New connection table fails with ASAN
New connection table code causes address sanitiser failures. 

```
[16/Jun/2022:13:51:24.835804473 +1000] - DEBUG - NSMMReplicationPlugin - agmtlist_config_init - Found 0 replication agreements in DIT
=================================================================
==11431==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7ff9ff5a5800 at pc 0x0000003ad69f bp 0x7ffefe55fc10 sp 0x7ffefe55fc08
WRITE of size 8 at 0x7ff9ff5a5800 thread T0
    #0 0x3ad69e in connection_table_new /home/william/development/389ds/ds/ldap/servers/slapd/conntable.c:198:40
    #1 0x3b4c1f in slapd_daemon /home/william/development/389ds/ds/ldap/servers/slapd/daemon.c:931:28
    #2 0x3c3c8c in main /home/william/development/389ds/ds/ldap/servers/slapd/main.c:1131:9
    #3 0x7ffa5a2a25af in __libc_start_call_main (/lib64/libc.so.6+0x405af) (BuildId: fda03f8cdd5c498a69f50759e61a74ae630ce917)
    #4 0x7ffa5a2a2678 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x40678) (BuildId: fda03f8cdd5c498a69f50759e61a74ae630ce917)
    #5 0x2c34e4 in _start /home/abuild/rpmbuild/BUILD/glibc-2.35/csu/../sysdeps/x86_64/start.S:115

0x7ff9ff5a5800 is located 0 bytes to the right of 524288-byte region [0x7ff9ff525800,0x7ff9ff5a5800)
allocated by thread T0 here:
    #0 0x346708 in calloc /home/abuild/rpmbuild/BUILD/llvm-14.0.4.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:77:3
    #1 0x7ffa5ab28ae8 in slapi_ch_calloc /home/william/development/389ds/ds/ldap/servers/slapd/ch_malloc.c:175:27
    #2 0x3accf2 in connection_table_new /home/william/development/389ds/ds/ldap/servers/slapd/conntable.c:141:37
    #3 0x3b4c1f in slapd_daemon /home/william/development/389ds/ds/ldap/servers/slapd/daemon.c:931:28
    #4 0x3c3c8c in main /home/william/development/389ds/ds/ldap/servers/slapd/main.c:1131:9
    #5 0x7ffa5a2a25af in __libc_start_call_main (/lib64/libc.so.6+0x405af) (BuildId: fda03f8cdd5c498a69f50759e61a74ae630ce917)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/william/development/389ds/ds/ldap/servers/slapd/conntable.c:198:40 in connection_table_new
Shadow bytes around the buggy address:
  0x0fffbfeacab0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffbfeacac0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffbfeacad0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffbfeacae0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffbfeacaf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fffbfeacb00:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fffbfeacb10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fffbfeacb20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fffbfeacb30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fffbfeacb40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fffbfeacb50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==11431==ABORTING
```

### PR DESCRIPTION
**Pull request by jchapma**
Bug Description: Commit 489b585a67bf9b91c33a93cf8b0c6c7bca398bee
contains a buffer overflow that causes asan failures.

Fix Decription: Removed the overflow, corrected an incorrect memory
allocation and corrected some debug strings.

fixes: https://github.com/389ds/389-ds-base/issues/5346
relates: https://github.com/389ds/389-ds-base/issues/4812

Reviewed by: ??

### CODE REVIEW

File: ldap/servers/slapd/conntable.c [hunk 1]
```diff
@@ -132,9 +132,9 @@ connection_table_new(int table_size)
     ct->size = table_size;
     ct->list_num = SLAPD_DEFAULT_NUM_LISTENERS;
 
-    ct->list_size = table_size/ct->list_num + 1; /* +1 to avoid rounding issue */
+    ct->list_size = (table_size+ct->list_num-1)/ct->list_num; /* to avoid rounding issue */
```
Comment (Firstyear) [inline ldap/servers/slapd/conntable.c:135]: Is it worth check for this to be at least greater than some minimum?

**Review by Firstyear — APPROVED** [review]

File: ldap/servers/slapd/conntable.c (hunk 1 above)
Comment (jchapma) [reply ldap/servers/slapd/conntable.c:135]: @Firstyear 
When we enable multi ct list we can add a check as you described.

File: ldap/servers/slapd/conntable.c [hunk 2]
```diff
@@ -181,13 +181,13 @@ connection_table_new(int table_size)
...
+                slapi_log_err(SLAPI_LOG_ERR, "connection_table_new", "pthread_mutex_init failed\n");
                 exit(1);
             }
 
             ct->c[ct_list][i].c_pdumutex = PR_NewLock();
             if (ct->c[ct_list][i].c_pdumutex == NULL) {
-                slapi_log_err(SLAPI_LOG_ERR, "connection_table_get_connection", "PR_NewLock failed\n");
+                slapi_log_err(SLAPI_LOG_ERR, "connection_table_new", "PR_NewLock failed\n");
                 exit(1);
             }
```
Comment (progier389) [inline ldap/servers/slapd/conntable.c:193]: When multi list will be enabled, you shall remember that there is still an overflow (when rounding occurs) because ct->list_num * ct->list_size > table_size in that case ...
so to avoid forgetting it I think you should also add 
+ if (free_idx<table_size) {
            ct->c_freelist[free_idx++] = &(ct->c[ct_list][i]);
+ }
Thar said, if you want to commit as it for now, I am ok with that ...

**Review by progier389 — COMMENTED** [review]
OK as far as ct->numlist is fixed to 1 , will require changes to support multi lists

File: ldap/servers/slapd/conntable.c (hunk 2 above)
Comment (Firstyear) [reply ldap/servers/slapd/conntable.c:193]: I think we shouldn't just "yolo commit" when obvious faults exist, because we'll forgetn about the issue and never fix it, then in a years time we'll be like "oh fuck why did this break".

So IMO fix it now. If we identify a problem, resolve it.

Comment (jchapma) [reply ldap/servers/slapd/conntable.c:193]: It could be me that says that, I agree with ye guys, the right thing is to fix it now. Will do. Thanks
