### PR TITLE
Issue 7333 - Fail open condition in ACL

### LINKED ISSUE #7333: Fail open condition in ACL
**Issue Description**
ACI code returns unconditionally True if backend is NULL. 
 This typically occur when evaluting the referral entry of a backend in referral or referral on update mode.

It is not really an issue because:
    - Referral are always visible by nature. (Anonymous user must be able to get it to be able to forward the bind operation to the referred server)
    - As referral is returned instead of entry, there is no way to get the other attributes

But it is still better to strenghen the code by:
     - Using default backend instead of NULL one in that case
     - Setting in the referral entry an aci attribute allowing to read the "ref" attribute and the attributes used in the rdn (so that the entry and its ref attribute are readable)

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch 

**Steps to Reproduce**
None.  Code analysis around https://github.com/389ds/389-ds-base/blob/887d50180f65d4d2a2fda6f09f836a9f5567e44f/ldap/servers/plugins/acl/acl.c#L4205

**Expected results**
Remove the problematic code from acl.c

**Additional context**
https://issues.redhat.com/browse/RHEL-141049

### PR DESCRIPTION
**Pull request by progier389**
Fix Fail open condition in ACL

Issue: #7333 

Reviewed by: @mreynolds389 , @droideck (Thanks!)

## Summary by Sourcery

Tighten access control handling for referrals by removing a fail-open ACL condition and extending tests to cover referral behavior for both privileged and anonymous binds.

Bug Fixes:
- Eliminate the fail-open ACL behavior that granted access when no backend was present in the pblock during access checks.

Tests:
- Extend referral tests to verify that both directory manager and anonymous clients receive referral errors without following referrals.

### CODE REVIEW

File: ldap/servers/slapd/mapping_tree.c [hunk 1]
```diff
@@ -228,13 +228,56 @@ slapi_mtn_get_dn(mapping_tree_node *node)
...
+    Slapi_RDN *rdn = slapi_entry_get_srdn(e);
+    char *theType = NULL;
+    char *value = NULL;
+    char **attrs = NULL;
+    char **pt = NULL;
+    char *pt2 = NULL;
+    char *attrlist = NULL;
+    int index = slapi_rdn_get_first(rdn, &theType, &value);
+    size_t len = 0;
+    char *aci = NULL;
```
[the remark this answers is not in the document]
Comment (progier389) [reply ldap/servers/slapd/mapping_tree.c]: rdn cannot be NULL in this case:
The rdn is the backend suffix entry. Its consistency is already checked when configuring the backend.

**Review by mreynolds389 — APPROVED** [review]

**Comment by progier389** [comment]
Investigating some suspicious failure in tests:
FAILED dirsrvtests/tests/suites/acl/default_aci_allows_self_write_test.py::test_acl_default_allow_self_write_nsuser
FAILED dirsrvtests/tests/suites/acl/modify_test.py::test_allow_write_access_to_targetattr_with_a_single_attribute
FAILED dirsrvtests/tests/suites/acl/modify_test.py::test_allow_write_access_to_targetattr_with_multiple_attibutes
FAILED dirsrvtests/tests/suites/acl/modify_test.py::test_allow_selfwrite_access_to_anyone
FAILED dirsrvtests/tests/suites/acl/valueacl_part2_test.py::test_modify_with_multiple_filters
FAILED dirsrvtests/tests/suites/acl/valueacl_part2_test.py::test_denied_by_multiple_filters
FAILED dirsrvtests/tests/suites/acl/valueacl_part2_test.py::test_allowed_add_one_attribute
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_delete_an_attribute_value_we_are_not_allowed_to_delete
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_donot_allow_write_access_to_title_if_value_is_not_architect
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_delete_an_attribute_value_we_are_allowed_to_delete
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_allow_modify_delete
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_replace_an_attribute_if_we_lack
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_remove_an_attribute_if_we_have_del_rights_to_all_attr_value
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_remove_an_attribute_if_we_have_del_rights_to_all_attr_values
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_allow_to_modify - ...
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_add_an_attribute_value_we_are_allowed_to_add_with_ldapanyone
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_hierarchy - ldap.I...
FAILED dirsrvtests/tests/suites/acl/valueacl_test.py::test_targattrfilters_and_search_permissions_and_that_ldapmodify_works_as_expected

File: ldap/servers/slapd/defbackend.c [hunk 2]
```diff
@@ -49,22 +50,23 @@ static int defbackend_next_search_entry(Slapi_PBlock *pb);
  */
 
 /*
- * defbackend_init:  instantiate the default backend
+ * new_default_backend:  instantiate a backend with default behavior
  */
-void
-defbackend_init(void)
+Slapi_Backend *
+new_default_backend(const char *bename)
```
Comment (droideck) [inline ldap/servers/slapd/defbackend.c]: Should this function be `static`?

File: ldap/servers/slapd/defbackend.c [hunk 3]
```diff
@@ -49,22 +50,23 @@ static int defbackend_next_search_entry(Slapi_PBlock *pb);
...
 {
     int rc;
     char *errmsg;
     Slapi_PBlock *pb = slapi_pblock_new();
+    Slapi_Backend *be = NULL;
 
     slapi_log_err(SLAPI_LOG_TRACE, "defbackend_init", "<==\n");
```
Comment (droideck) [inline ldap/servers/slapd/defbackend.c:61]: Stale log message function name

File: ldap/servers/slapd/defbackend.c [hunk 4]
```diff
@@ -74,15 +76,15 @@ defbackend_init(void)
      * slapi_pblock_set()/slapi_pblock_get() functions assume there is one.
      */
     defbackend_plugin.plg_type = SLAPI_PLUGIN_DATABASE;
-    defbackend_backend->be_database = &defbackend_plugin;
+    be->be_database = &defbackend_plugin;
```
Comment (droideck) [inline ldap/servers/slapd/defbackend.c]: Do I understand correctly that `defbackend_plugin` struct is shared between two backends? And one overwrites another

File: ldap/servers/slapd/defbackend.c [hunk 5]
```diff
@@ -118,6 +120,17 @@ defbackend_init(void)
...
+}
+
+/*
+ * defbackend_init:  instantiate the default backend and referral backend
+ */
+void
+defbackend_init(void)
+{
+    defbackend_backend = new_default_backend(DEFBACKEND_NAME);
+    refbackend_backend = new_default_backend(REFBACKEND_NAME);
```
Comment (droideck) [inline ldap/servers/slapd/defbackend.c]: I think we also need to add the new `REFBACKEND_NAME` to https://github.com/389ds/389-ds-base/blob/main/ldap/servers/slapd/daemon.c#L610 so it's handled too on low-disk-space event.

**Review by droideck — CHANGES_REQUESTED** [review]

File: ldap/servers/slapd/defbackend.c (hunk 4 above)
Comment (progier389) [reply ldap/servers/slapd/defbackend.c]: Good catch! something is amiss here ...

File: ldap/servers/plugins/acl/acl.c [hunk 6]
```diff
@@ -1521,11 +1521,6 @@ acl_check_mods(
 
         case LDAP_MOD_REPLACE:
             if (!lastmod) {
-                if (be == NULL) {
-                    if (slapi_pblock_get(pb, SLAPI_BACKEND, &be)) {
-                        be = NULL;
-                    }
-                }
                 if (be != NULL)
                     slapi_pblock_get(pb, SLAPI_BE_LASTMOD, &lastmod);
```
Comment (droideck) [inline ldap/servers/plugins/acl/acl.c:1530]: IIUC, we never get `lastmod` here because `be` is NULL now.
And because lastmod is always 0, the slapi_attr_is_last_mod() check is never reached -> so we don't skip pseudo attrs.
Possible the ACI tests fail because of that.

Comment (progier389) [reply ldap/servers/plugins/acl/acl.c:1530]: I see! I was tricked.  I thought this code was doing nothing (setting be to NULL if it was NULL) 
 but you are right   slapi_pblock_get(pb, SLAPI_BACKEND, &be)) is false when the be is set

Guess I can try again with a single defbackend 😉

File: ldap/servers/slapd/mapping_tree.c [hunk 7]
```diff
@@ -228,13 +228,56 @@ slapi_mtn_get_dn(mapping_tree_node *node)
...
+    /* Build 'ref' and rdn attributes list */
+    slapi_ch_array_add_ext(&attrs, slapi_ch_strdup("ref"));
+    while (index != -1) {
+        if (!charray_inlist(attrs, theType)) {
+            slapi_ch_array_add_ext(&attrs, slapi_ch_strdup(theType));
+        }
+        index = slapi_rdn_get_next(rdn, index, &theType, &value);
+    }
+    slapi_rdn_done(rdn);
```
Comment (droideck) [inline ldap/servers/slapd/mapping_tree.c]: I think the RDN processing loop and slapi_rdn_done might be a dead code, as we never populate RDN in `referral2entry`.  Or do I miss something?

File: ldap/servers/slapd/mapping_tree.c [hunk 8]
```diff
@@ -2667,6 +2713,7 @@ mtn_get_be(mapping_tree_node *target_node, Slapi_PBlock *pb, Slapi_Backend **be,
                 *be = NULL;
                 if (referral) {
                     *referral = (target_node->mtn_referral_entry ? slapi_entry_dup(target_node->mtn_referral_entry) : NULL);
+                    *be = defbackend_get_backend();
```
Comment (droideck) [inline ldap/servers/slapd/mapping_tree.c]: I wonder if this won't have any consequences later... If we assign it here, then later in the end of this function we call `slapi_be_Rlock` and, IIUC, later in slapi_mapping_tree_select_all it's added to `be_list` alongside the `referral_list`
And that feels wrong, unless I miss something.

**Review by droideck — APPROVED** [review]
Overall, looks great!

I have a couple of concerns/questions, but I'm not sure if there's more to it I don't see.

File: ldap/servers/slapd/mapping_tree.c (hunk 7 above)
Comment (progier389) [reply ldap/servers/slapd/mapping_tree.c]: Test shows that you are right. 
And the fact that the referral works means that we do not even need to bother about the acl when dealing with referral in mapping tree.
In fact changing the acl code is enough
==> Reverting to the main branch mapping tree
Modifying test_basic_referrals to verify that referrals are returned with anonymous connection

File: dirsrvtests/tests/suites/basic/basic_test.py [hunk 9]
```diff
@@ -1178,9 +1178,17 @@ def test_basic_referrals(topology_st, import_example_ldif):
...
     topology_st.standalone.set_option(ldap.OPT_REFERRALS, 0)  # Do not follow referral
     with pytest.raises(ldap.REFERRAL):
         topology_st.standalone.search_s(DEFAULT_SUFFIX, ldap.SCOPE_SUBTREE, 'objectclass=top')
+    log.info('When anonymous')
+    ldc = ldap.initialize(f'ldap://localhost:{topology_st.standalone.port}')
+    ldc.set_option(ldap.OPT_TIMEOUT, 5)
+    ldc.set_option(ldap.OPT_REFERRALS, 0)  # Do not follow referral
+    with pytest.raises(ldap.REFERRAL):
+        ldc.search_s(DEFAULT_SUFFIX, ldap.SCOPE_SUBTREE, 'objectclass=top')
+    ldc.unbind
```
Comment (droideck) [inline dirsrvtests/tests/suites/basic/basic_test.py]:
```suggestion
    ldc.unbind()
```

**Review by droideck — APPROVED** [review]
LGTM
