### PR TITLE
Issue 6494 - Various errors when using extended matching rule on vlv sort filter

### LINKED ISSUE #6494: Various errors when using extended matching rule on vlv sort filter
**Issue Description**
libasan reports several issues when trying to configre a vlv whose sort filter contains an extended matching rule.
While fixing the test I saw crashes SIGSEGV, use-after-free, double-free, read overflow and memory leaks.

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: At least main branch.

**Steps to Reproduce**
1. Install ds version with libasan
2. Run following script:
```
find $PREFIX | grep asan | xargs /bin/rm -f
INSTANCE=i
SUFFIX='dc=com,dc=example'
S1=$PREFIX/var/run/slapd-$INSTANCE.socket
Socket=$(echo $S1 | sed 's,/,%2f,g')

echo "
[general]
[slapd]
instance_name=i

[backend-userroot]
create_suffix_entry=yes
sample_entries=yes
suffix= $SUFFIX
" >/tmp/temp.ldap

set -x
dsctl $INSTANCE remove --do-it
dscreate from-file /tmp/temp.ldap

echo "TEST 1 ==> ds should crash"
dsconf $INSTANCE backend vlv-index add-search --name "VLV People" --search-base "ou=People,$SUFFIX" --search-filter "cn=*" --search-scope 2 userRoot
dsconf $INSTANCE backend vlv-index add-index --index-name "SORT_UID_emr" --sort "uid:2.5.13.2" --parent-name "VLV People" --index-it "$SUFFIX"

echo "TEST 2 ==> ds should hang + merror after restart"
dsconf $INSTANCE backend vlv-index add-index --index-name "SORT_UID" --sort "uid" --parent-name "VLV People" --index-it "dc=$SUFFIX"
echo quit | ldapsearch -Q -LLL -Y EXTERNAL -H ldapi://$Socket -b "ou=People,$SUFFIX" "cn=*" "distinguishedName" -E 'sss=uid:2.5.13.2' -E 'vlv=0/999999/0/0'
dsconf $INSTANCE backend vlv-index add-index --index-name "SORT_UID" --sort "uid" --parent-name "VLV People" --index-it "$SUFFIX"
echo quit | ldapsearch -Q -LLL -Y EXTERNAL -H ldapi://$Socket -b "ou=People,$SUFFIX" "cn=*" "distinguishedName" -E 'sss=uid:2.5.13.2' -E 'vlv=0/999999/0/0'
dsconf $INSTANCE backend vlv-index add-index --index-name "SORT_UID_emr2" --sort "uid:2.5.13.2" --parent-name "VLV People" --index-it "$SUFFIX"
echo quit | ldapsearch -Q -LLL -Y EXTERNAL -H ldapi://$Socket -b "ou=People,$SUFFIX" "cn=*" "distinguishedName" -E 'sss=uid:2.5.13.2' -E 'vlv=0/999999/0/0'
echo "END OF TEST 2"
```
3. See error:  Server crashs: 
```
++ dsconf i backend vlv-index add-index --index-name SORT_UID --sort uid --parent-name 'VLV People' --index-it dc=dc=com,dc=example
Error: -1 - Can't contact LDAP server - 104 - [] - Connection reset by peer
```

**Expected results**
Server should not crash, there should be no memory leaks after the server initialization 

**Additional context**
Problem was found while investigating 
https://issues.redhat.com/browse/RHEL-67020 / https://issues.redhat.com/browse/IDMDS-4867

I suspect that at least all version >= 2.1 are impacted / I need to double check for 1.4.3

### PR DESCRIPTION
**Pull request by progier389**
Various issues when configuring and using extended matching rule within a vlv sort filter:
1. Race condition about the keys storage while indexing leading to various heap and data corruption.  (lmdb only)
2. Crash while indexing if vlv are misconfigured because NULL key is not checked.
3. Read after block because of data type mismatch between SlapiValue and berval
4. Memory leaks

Solution:
1. Serialize the vlv index key generation if vlv filter has an extended matching rule.
2. Check null keys
3. Always provides SlapiValue even ifg we want to get keys as bervals
4. Free properly the resources

Issue: #6494 

Reviewed by: @mreynolds389 (Thanks!)

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c [hunk 1]
```diff
@@ -3181,6 +3184,23 @@ is_reindexed_attr(const char *attrname, const ImportCtx_t *ctx, char **list)
     return (list && attr_in_list(attrname, list));
 }
 
+/*
+ * Determine if vlv require extended matching rule evaluation
+ */
+static int
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c]: shoul use C11 bool

File: ldap/servers/slapd/back-ldbm/dblayer.c [hunk 2]
```diff
@@ -1414,6 +1421,14 @@ dblayer_pop_pvt_txn(void)
     return;
 }
 
+void
+dblayer_destroy_txn_stack(void)
+{
+    /* Cleanup for the main thread to avoid false/positive leaks from libasan */
+    void *txn_stack = PR_GetThreadPrivate(thread_private_txn_stack);
```
Comment (mreynolds389) [inline ldap/servers/slapd/back-ldbm/dblayer.c]: Unused variable, but why "get" it if you just "set" it to NULL on the next line?

**Review by mreynolds389 — APPROVED** [review]
Did a covscan run as well, and didn't see any regressions. Ack!

File: ldap/servers/slapd/back-ldbm/dblayer.c (hunk 2 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/dblayer.c]: Indeed, something looks broken.
either the slapi_ch_free(&txn_stack); line is missing, or the  PR_GetThreadPrivate should be deleted.  (depending whether PR_SetThreadPrivate calls the cleanup callback or not)  I will double check
|

Comment (progier389) [reply ldap/servers/slapd/back-ldbm/dblayer.c]: Clearly the dblayer_cleanup_txn_stack is called when using PR_SetThreadPrivate ==> No need to get the data to release it
```
    #1 0x7f00d94601eb in slapi_ch_free /home/progier/sb/r67020/tst/source/389-ds-base/ldap/servers/slapd/ch_malloc.c:286
    #2 0x7f00d22a6876 in dblayer_cleanup_txn_stack /home/progier/sb/r67020/tst/source/389-ds-base/ldap/servers/slapd/back-ldbm/dblayer.c:1373
    #3 0x7f00d8b04920 in PR_SetThreadPrivate (/lib64/libnspr4.so+0x13920) (BuildId: e6dfe24882ade9ec65f7f1591a3e9e249e5a5780)
    #4 0x7f00d22aac9f in dblayer_destroy_txn_stack /home/progier/sb/r67020/tst/source/389-ds-base/ldap/servers/slapd/back-ldbm/dblayer.c:1429
    #5 0x7f00d22aad5d in dblayer_close /home/progier/sb/r67020/tst/source/389-ds-base/ldap/servers/slapd/back-ldbm/dblayer.c:500
```

**Comment by mreynolds389** [comment]
Thanks for fixing those issues - re-ack!
