### PR TITLE
Issue 4644 - Large updates can reset the CLcache to the beginning of …

### LINKED ISSUE #4492: Changelog cache can upload updates from a wrong starting point (CSN)
**Issue Description**
Changelog cache is the mechanism that uploads a bulk of updates from the changelog.
The updates are consecutive (CSN order) updates from a given starting point.
The problem is that the bulk of updates can start from the beginning of the changelog even if the starting point CSN exists in the changelog.

The consequence is that the changelog cache will iterate through the all changelog to retrieve the next update to send. If the changelog is large it will delay the sent updates and create replication lag

**Package Version and Platform:**
Likely since 1.2.12

**Steps to Reproduce**
Hammering a large topology with small updates.
Accelerators are
	  Replica:
	 	nsds5ReplicaReleaseTimeout:30
	  RA: 		
		nsds5replicaBusyWaitTime: 3
		nsds5replicaSessionPauseTime: 5

**Expected results**
Replication session should start before the initial starting point

### PR DESCRIPTION
**Pull request by tbordaz**
…the changelog

Bug description:
	The replication agreements are using bulk load to load updates.
	For bulk load it uses a cursor with DB_MULTIPLE_KEY and DB_NEXT.
	Before using the cursor, it must be initialized with DB_SET.

	If during the cursor/DB_SET the CSN refers to an update that is larger than
	the size of the provided buffer, then the cursor remains not initialized and
	c_get returns DB_BUFFER_SMALL.

	The consequence is that the next c_get(DB_MULTIPLE_KEY and DB_NEXT) will return the
	first record in the changelog DB. This break CLcache.

Fix description:
	The fix is to harden cursor initialization so that if DB_SET fails
	because of DB_BUFFER_SMALL. It reallocates buf_data and retries a DB_SET.
	If DB_SET can not be initialized it logs a warning.

	The patch also changes the behaviour of the fix #4492.
	#4492 detected a massive (1day) jump prior the starting csn and ended the
	replication session. If the jump was systematic, for example
	if the CLcache got broken because of a too large updates, then
	replication was systematically stopped.
	This patch suppress the systematically stop, letting RA doing a big jump.
	From #4492 only remains the warning.

relates: https://github.com/389ds/389-ds-base/issues/4644

Reviewed by:

Platforms tested: F31

### CODE REVIEW

File: ldap/servers/plugins/replication/cl5_clcache.c [hunk 1]
```diff
@@ -467,17 +498,24 @@ clcache_load_buffer_bulk(CLC_Buffer *buf, int flag)
...
-                               &buf->buf_data,
-                               DB_SET);
+            rc = clcache_cursor_set(cursor, buf);
         }
 
-        /*
-         * Continue if the error is no-mem since we don't need to
-         * load in the key record anyway with DB_SET.
-         */
         if (0 == rc || DB_BUFFER_SMALL == rc) {
```
Comment (progier389) [inline ldap/servers/plugins/replication/cl5_clcache.c:504]: Should rather be: if (00 == rc) {
  and let the function fails if rc == DB_BUFFER_SMALL (that will stop the replication with an error message about the fact that we failed to get next csn) 
Note: that is IMHO a minor issue because I do not think that c_get could return DB_BUFFER_SMALL after the realloc (because changelog records size does never change)

File: ldap/servers/plugins/replication/cl5_clcache.c [hunk 2]
```diff
@@ -467,17 +498,24 @@ clcache_load_buffer_bulk(CLC_Buffer *buf, int flag)
...
+            * that the cursor will be reset to the beginning of the changelog.
+            * Returning an error at this point will stop replication that is
+            * a risk. So just accept the risk of a reset to the beginning of the CL
+            * and log an alarming message.
+            */
+           if (rc == DB_BUFFER_SMALL) {
+               slapi_log_err(SLAPI_LOG_WARNING, buf->buf_agmt_name,
+                             "clcache_load_buffer_bulk - Fail to position on csn=%s from the changelog (too large update ?). Risk of full CL evaluation.\n",
+                             (char *)buf->buf_key.data);
+           }
```
Comment (progier389) [inline ldap/servers/plugins/replication/cl5_clcache.c:518]: should be removed if  above test is 0 == rc

**Review by progier389 — APPROVED** [review]
I would have tested the double DB_BUFFER_SMALL error differently (aborting the replication rather that looping back on start of changelog)  (as described in my comments) 
but as i doubt this case could really happen, the current fix is ok for me.

File: ldap/servers/plugins/replication/cl5_clcache.c (hunk 1 above)
Comment (tbordaz) [reply ldap/servers/plugins/replication/cl5_clcache.c:504]: I made a previous hotfix #4492 that stop replication session when detecting a big jump backward. The hotfix was failing because replication got broken with constant big jumps session after session. Without that hotfix replication kept going on even if restarted from the beginning of the CL.

So I prefer to get a permissive code that let replication going on even at a cost of a big jump.
In case of DB_BUFFER_SMALL during DB_SET (that I hope will no long happen) we just log a warning to help diagnose

Comment (progier389) [reply ldap/servers/plugins/replication/cl5_clcache.c:504]: Fine. Anyway as I do not think that we could hit the double DB_BUFFER_SMALL, I have no strong feeling about the way we handle it ! -;)
