### PR TITLE
Issue 6417 - (2nd) If an entry RDN is identical to the suffix, then E…

### LINKED ISSUE #6417: If an entry RDN is identical to the suffix, then Entryrdn gets broken during a reindex
**Issue Description**
At the end of a reindex, entryrdn is rebuilt taking into account each entry under the suffix. The suffix is the first entry to be added. If a later entry has the same rdn than the suffix then entryrdn gets broken.

The bug impacts bdb as well as mdb. It does not impact import but only indexing.

Under mdb entryrdn gets broken silently, but contains invalid data
Under bdb entryrdn gets broken with message like 
`entryrdn_insert_key - Same DN (dn: <ENTRY_DN>) is already in the entryrdn file with different ID`

**Package Version and Platform:**
 - all versions (IIUC)

**Steps to Reproduce**
will provide a CI testcase

**Expected results**
after a reindex entryrdn should not be corrupted

### PR DESCRIPTION
**Pull request by tbordaz**
…ntryrdn gets broken during a reindex

Bug description:
	The primary fix has a flaw as it assumes that the
	suffix ID is '1'.
	If the RUV entry is the first entry of the database
	the server loops indefinitely

Fix description:
	Read the suffix ID from the entryrdn index

fixes: #6417

Reviewed by: Pierre Rogier (reviewed the first fix)

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c [hunk 1]
```diff
@@ -992,6 +992,7 @@ entryrdn_lookup_dn(backend *be,
     ID workid = id; /* starting from the given id */
     rdn_elem *elem = NULL;
     int maybesuffix = 0;
+    ID suffix_id;
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c]: Style: We usually initialize the variable at declaration time. 
 ID suffix_id = 1;

File: ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c [hunk 2]
```diff
@@ -1032,6 +1033,20 @@ entryrdn_lookup_dn(backend *be,
...
+    if (rc) {
+        slapi_log_err(SLAPI_LOG_WARNING, "entryrdn_lookup_dn",
+                  "Fails to retrieve the ID of suffix %s - Assume it is '1'\n", slapi_sdn_get_ndn(be->be_suffix));
+        suffix_id = 1;
+    } else {
+        elem = (rdn_elem *)data.data;
+        suffix_id = id_stored_to_internal(elem->rdn_elem_id);
+        dblayer_value_free(be, &data);
+    }
+
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c:1051]: Memory leak: I think that both
```
dblayer_value_free(be, &data);
dblayer_value_free(be, &key);
```
are needed (whether rc==0 or not)

**Review by progier389 — CHANGES_REQUESTED** [review]

File: ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c (hunk 2 above)
Comment (tbordaz) [reply ldap/servers/slapd/back-ldbm/ldbm_entryrdn.c:1051]: Nice catch. Thanks.
I updated the fix

**Review by progier389 — APPROVED** [review]
LGTM
