### PR TITLE
Issue 7096 - During replication online total init the function

### LINKED ISSUE #7096: During replication online total init the function idl_id_is_in_idlist is not scaling with large database
**Issue Description**
Since https://github.com/389ds/389-ds-base/issues/1815 the oneline init creates the candidate list with a range search '(parentid>=1)'. Before adding an entry to the candidate list it checks that the parent entry is already added, so that total init will send parents before children.
The checking is done with idl_id_is_in_idlist that does not scale. Looking like the total init never start.

**Package Version and Platform:**
 - 1.3 and after

**Steps to Reproduce**
will be described later

**Expected results**
Total init should not take too long to create the candidate list

### PR DESCRIPTION
**Pull request by tbordaz**
idl_id_is_in_idlist is not scaling with large database

Bug description:
	During a online total initialization, the supplier sorts
	the candidate list of entries so that the parents are sent before
	children entries.
	With large DB the ID array used for the sorting is not
	scaling. It takes so long to build the candidate list that
	the connection gets closed

Fix description:
        Instead of using an ID array, uses a list of ID ranges

fixes: #7096

Reviewed by:

## Summary by Sourcery

Optimize replication candidate list handling during online total initialization by tracking included entry IDs as ranges instead of individual IDs to improve scalability on large databases.

Bug Fixes:
- Prevent timeouts during online total initialization by replacing per-ID membership checks with range-based tracking of candidate entry IDs.

Enhancements:
- Introduce an ID range data structure and helper routines to manage and query ID membership efficiently, and integrate them into range-based IDL fetching logic.

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/idl_common.c [hunk 1]
```diff
@@ -172,6 +172,152 @@ idl_min(IDList *a, IDList *b)
...
+
+        if (id == curr->last + 1) {
+            /* Extend this range upwards */
+            curr->last = id;
+
+            /* Check for possible merge with next range */
+            IdRange_t *next = curr->next;
+            if (next && curr->last + 1 >= next->first) {
+               slapi_log_err(SLAPI_LOG_REPL, "idrange_add_id",
+                                      "(id=%d) merge current  with next range [%d..%d]\n", id, curr->first, curr->last);
```
Comment (mreynolds389) [inline ldap/servers/slapd/back-ldbm/idl_common.c]: indentation, and should this be repl logging in the backend?

File: ldap/servers/slapd/back-ldbm/idl_common.c [hunk 2]
```diff
@@ -172,6 +172,152 @@ idl_min(IDList *a, IDList *b)
...
+            if (prev && prev->last + 1 >= curr->first) {
+                prev->last = curr->last;
+                prev->next = curr->next;
+                slapi_ch_free((void *) &curr);
+                slapi_log_err(SLAPI_LOG_REPL, "idrange_add_id",
+                                      "(id=%d) merge current with previous range [%d..%d]\n", id, prev->first, prev->last);
+                return prev;
+            } else {
+                slapi_log_err(SLAPI_LOG_REPL, "idrange_add_id",
+                                      "(id=%d) extend backward current range [%d..%d]\n", id, curr->first, curr->last);
```
Comment (mreynolds389) [inline ldap/servers/slapd/back-ldbm/idl_common.c]: Same here, indentation and logging level?

File: ldap/servers/slapd/back-ldbm/idl_common.c [hunk 3]
```diff
@@ -172,6 +172,152 @@ idl_min(IDList *a, IDList *b)
...
+    }
+    if (sav) {
+        slapi_ch_free((void *) &sav);
+    }
+    *head = NULL;
+}
+
+IdRange_t *idrange_add_id(IdRange_t **head, ID id)
+{
+    if (!head) {
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/idl_common.c]: Should not it be if (!*head)  (or even better: if (*head == NULL) { ) ?

File: ldap/servers/slapd/back-ldbm/idl_common.c (hunk 1 above)
Comment (progier389) [reply ldap/servers/slapd/back-ldbm/idl_common.c]: SLAPI_LOG_REPL seems pertinent but you should probably add a comment explaining that these functions are handling replication total init

File: ldap/servers/slapd/back-ldbm/idl_new.c [hunk 4]
```diff
@@ -695,13 +698,15 @@ idl_new_range_fetch(
 
         while(remaining > 0) {
             for (size_t i = 0; i < leftovercnt; i++) {
-                if (leftover[i].key > 0 && idl_id_is_in_idlist(idl, leftover[i].key) != 0) {
+                if (leftover[i].key > 0 && idl_id_is_in_idlist_ranges(idl, idrange_list, leftover[i].key) != 0) {
                     /* if the leftover key has its parent in the idl */
                     idl_rc = idl_append_extend(&idl, leftover[i].id);
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/idl_new.c]: testing idl_rc looks like an overhead:
    idl_append_extend can only return 0 
        ( slapi_ch_realloc cannot return NULL  so idl_append_extend cannot return ENOMEM ,,, )

**Review by progier389 — CHANGES_REQUESTED** [review]
NPE in idrange_add_id should be fixed

File: ldap/servers/slapd/back-ldbm/idl_common.c [hunk 5]
```diff
@@ -172,6 +172,173 @@ idl_min(IDList *a, IDList *b)
...
+    if (head == NULL) {
+        slapi_log_err(SLAPI_LOG_ERR, "idrange_add_id",
+                      "Can not add ID %d in non defined list\n", id);
+        return NULL;
+    }
+
+    if (*head == NULL) {
+        /* This is the first range */
+        IdRange_t *new_range = (IdRange_t *)slapi_ch_malloc(sizeof(IdRange_t));
+        if (!new_range) return NULL;
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/idl_common.c]: Please dont test slapi_ch_malloc result.
   slapi-plugin.h:char *slapi_ch_malloc(unsigned long size) __ATTRIBUTE__((returns_nonnull));
Tells explicitly that the return code cannot be NULL
( and testing it triggers  covscan errors )

File: ldap/servers/slapd/back-ldbm/idl_common.c [hunk 6]
```diff
@@ -172,6 +172,173 @@ idl_min(IDList *a, IDList *b)
...
+        if (id < curr->first) {
+            break;
+        }
+
+        prev = curr;
+        curr = curr->next;
+    }
+    /* Need to insert a new standalone IdRange */
+    IdRange_t *new_range = (IdRange_t *)slapi_ch_malloc(sizeof(IdRange_t));
+    if (!new_range) {
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/idl_common.c]: same remark: do not test new_range

**Review by progier389 — APPROVED** [review]
Looks good expect two minor issues (should not test slapi_ch_malloc result)
