### PR TITLE
Issue 7121 - LeakSanitizer: various leaks during replication

### LINKED ISSUE #7121: LeakSanitizer: various leaks during replication
**Issue Description**
```
=================================================================
==59571==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 98944 byte(s) in 6184 object(s) allocated from:
    #0 0x7f7ed6eb4db8 in __interceptor_realloc (/usr/lib64/libasan.so.6+0xb4db8)
    #1 0x7f7ed7917d9c in ber_memrealloc_x (/lib64/liblber.so.2+0x7d9c)
    #2 0x7f7ed7939294 in ldap_pvt_get_controls (/lib64/libldap.so.2+0x17294)
    #3 0x7f7ed79417be in ldap_parse_result (/lib64/libldap.so.2+0x1f7be)
    #4 0x7f7ecf9169d7 in conn_read_result_ex (/usr/lib64/dirsrv/plugins/libreplication-plugin.so+0x419d7)
    #5 0x7f7ecf91fa3f in repl5_inc_result_threadmain (/usr/lib64/dirsrv/plugins/libreplication-plugin.so+0x4aa3f)
    #6 0x7f7ed7881bd3 in _pt_root pthreads/../../../../nspr/pr/src/pthreads/ptthread.c:191

Direct leak of 7104 byte(s) in 222 object(s) allocated from:
    #0 0x7f7ed6eb4a07 in __interceptor_malloc (/usr/lib64/libasan.so.6+0xb4a07)
    #1 0x7f7ed6adc048 in write_auditfail_log_entry ldap/servers/slapd/auditlog.c:261
    #2 0x7f7ed6ae5ea6 in csnset_add_csn (/usr/lib64/dirsrv/libslapd.so.0+0xe5ea6)
    #3 0x7f7ed6ae5fc6 in csnset_dup (/usr/lib64/dirsrv/libslapd.so.0+0xe5fc6)
    #4 0x7f7ed6b820e5 in valuearray_add_valuearray_fast ldap/servers/slapd/valueset.c:82
    #5 0x7f7ed6b8fe40 in extractKeysAndSubject ldap/servers/slapd/ssl.c:2731
    #6 0x7f7ed6b8fe40 in slapd_extract_key.constprop.0.isra.0 ldap/servers/slapd/ssl.c:2914
    #7 0x7f7ed6afb2c6 in str2entry_fast ldap/servers/slapd/entry.c:296
    #8 0x7f7ed6afb405 in str2entry_fast ldap/servers/slapd/entry.c:388
    #9 0x7f7ecfbcba8e in modify_apply_check_expand (/usr/lib64/dirsrv/plugins/libback-ldbm.so+0x7ca8e)
    #10 0x7f7ecfbcf524 in ldbm_back_modify (/usr/lib64/dirsrv/plugins/libback-ldbm.so+0x80524)
    #11 0x7f7ed6b33cc0 in op_shared_modify ldap/servers/slapd/modify.c:1129
    #12 0x7f7ed6b34a4c in op_shared_modify ldap/servers/slapd/modify.c:984
    #13 0x5576dcfd13bc in connection_threadmain (/usr/sbin/ns-slapd+0x303bc)
    #14 0x7f7ed7881bd3 in _pt_root pthreads/../../../../nspr/pr/src/pthreads/ptthread.c:191

Indirect leak of 197792 byte(s) in 6181 object(s) allocated from:
    #0 0x7f7ed6eb4bd7 in calloc (/usr/lib64/libasan.so.6+0xb4bd7)
    #1 0x7f7ed7917bc4 in ber_memcalloc_x (/lib64/liblber.so.2+0x7bc4)
    #2 0x7f7ed7939276 in ldap_pvt_get_controls (/lib64/libldap.so.2+0x17276)
    #3 0x7f7ed79417be in ldap_parse_result (/lib64/libldap.so.2+0x1f7be)
    #4 0x7f7ecf9169d7 in conn_read_result_ex (/usr/lib64/dirsrv/plugins/libreplication-plugin.so+0x419d7)
    #5 0x7f7ecf91fa3f in repl5_inc_result_threadmain (/usr/lib64/dirsrv/plugins/libreplication-plugin.so+0x4aa3f)
    #6 0x7f7ed7881bd3 in _pt_root pthreads/../../../../nspr/pr/src/pthreads/ptthread.c:191

Indirect leak of 148272 byte(s) in 6178 object(s) allocated from:
    #0 0x7f7ed6eb4a07 in __interceptor_malloc (/usr/lib64/libasan.so.6+0xb4a07)
    #1 0x7f7ed7917014 in ber_memalloc_x (/lib64/liblber.so.2+0x7014)
    #2 0x7f7ed79170f7 in ber_get_stringbv (/lib64/liblber.so.2+0x70f7)
    #3 0x7f7ed7917541 in ber_get_stringa (/lib64/liblber.so.2+0x7541)
    #4 0x7f7ed7919cd9 in ber_scanf (/lib64/liblber.so.2+0x9cd9)
    #5 0x7f7ed79392cc in ldap_pvt_get_controls (/lib64/libldap.so.2+0x172cc)
    #6 0x7f7ed79417be in ldap_parse_result (/lib64/libldap.so.2+0x1f7be)
    #7 0x7f7ecf9169d7 in conn_read_result_ex (/usr/lib64/dirsrv/plugins/libreplication-plugin.so+0x419d7)
    #8 0x7f7ecf91fa3f in repl5_inc_result_threadmain (/usr/lib64/dirsrv/plugins/libreplication-plugin.so+0x4aa3f)
    #9 0x7f7ed7881bd3 in _pt_root pthreads/../../../../nspr/pr/src/pthreads/ptthread.c:191

Indirect leak of 18537 byte(s) in 6179 object(s) allocated from:
    #0 0x7f7ed6eb4a07 in __interceptor_malloc (/usr/lib64/libasan.so.6+0xb4a07)
    #1 0x7f7ed7917014 in ber_memalloc_x (/lib64/liblber.so.2+0x7014)
    #2 0x7f7ed79170f7 in ber_get_stringbv (/lib64/liblber.so.2+0x70f7)
    #3 0x7f7ed7919d63 in ber_scanf (/lib64/liblber.so.2+0x9d63)
    #4 0x7f7ed7939334 in ldap_pvt_get_controls (/lib64/libldap.so.2+0x17334)
    #5 0x7f7ed79417be in ldap_parse_result (/lib64/libldap.so.2+0x1f7be)
    #6 0x7f7ecf9169d7 in conn_read_result_ex (/usr/lib64/dirsrv/plugins/libreplication-plugin.so+0x419d7)
    #7 0x7f7ecf91fa3f in repl5_inc_result_threadmain (/usr/lib64/dirsrv/plugins/libreplication-plugin.so+0x4aa3f)
    #8 0x7f7ed7881bd3 in _pt_root pthreads/../../../../nspr/pr/src/pthreads/ptthread.c:191

Indirect leak of 6528 byte(s) in 204 object(s) allocated from:
    #0 0x7f7ed6eb4a07 in __interceptor_malloc (/usr/lib64/libasan.so.6+0xb4a07)
    #1 0x7f7ed6adc048 in write_auditfail_log_entry ldap/servers/slapd/auditlog.c:261
    #2 0x7f7ed6ae5ea6 in csnset_add_csn (/usr/lib64/dirsrv/libslapd.so.0+0xe5ea6)
    #3 0x7f7ed6ae5fc6 in csnset_dup (/usr/lib64/dirsrv/libslapd.so.0+0xe5fc6)
    #4 0x7f7ed6b820e5 in valuearray_add_valuearray_fast ldap/servers/slapd/valueset.c:82
    #5 0x7f7ed6b8fe40 in extractKeysAndSubject ldap/servers/slapd/ssl.c:2731
    #6 0x7f7ed6b8fe40 in slapd_extract_key.constprop.0.isra.0 ldap/servers/slapd/ssl.c:2914
    #7 0x7f7ed6afb2c6 in str2entry_fast ldap/servers/slapd/entry.c:296
    #8 0x7f7ed6afb405 in str2entry_fast ldap/servers/slapd/entry.c:388
    #9 0x7f7ecfbcba8e in modify_apply_check_expand (/usr/lib64/dirsrv/plugins/libback-ldbm.so+0x7ca8e)
    #10 0x7f7ecfbcf524 in ldbm_back_modify (/usr/lib64/dirsrv/plugins/libback-ldbm.so+0x80524)
    #11 0x7f7ed6b33cc0 in op_shared_modify ldap/servers/slapd/modify.c:1129
    #12 0x7f7ed6b34a4c in op_shared_modify ldap/servers/slapd/modify.c:984
    #13 0x5576dcfd13bc in connection_threadmain (/usr/sbin/ns-slapd+0x303bc)
    #14 0x7f7ed7881bd3 in _pt_root pthreads/../../../../nspr/pr/src/pthreads/ptthread.c:191

SUMMARY: AddressSanitizer: 477177 byte(s) leaked in 25148 allocation(s).
```

### PR DESCRIPTION
**Pull request by vashirov**
1. CSN Leaks

In `resolve_attribute_state_deleted_to_present()` we set CSN set pointer to NULL without freeing the allocated memory.
In `valueset_remove_valuearray()` we overwrite `csnset` pointer without freeing the existing `csnset`.

2. Leak in `replica_add_session_abort_control()`

Control's OID and value are allocated but never freed after `slapi_pblock_set`, which duplicates the control. Added cleanup to free `ctrl.ldctl_oid` and `ctrl.ldctl_value.bv_val` after `slapi_pblock_set`.

3. LDAP controls leak

`ldap_parse_result` allocates controls that are not being freed when not transferred to caller or on error paths.  Free `loc_returned_controls` in cleanup section and NULL the pointer after the transfer.

`returned_controls` allocated in `conn_read_result_ex` are used to check for abort session control, but never freed before the next loop iteration.

Fixes: https://github.com/389ds/389-ds-base/issues/7121

## Summary by Sourcery

Fix memory leaks in replication CSN handling and LDAP control processing.

Bug Fixes:
- Free CSN sets instead of nulling or overwriting their pointers when resolving deleted-to-present attribute state and when removing values from value sets.
- Ensure LDAP controls returned from result processing threads are freed after use, including local and transferred control arrays.
- Release the OID and value memory for the session abort control after adding it to the operation pblock, since the control is duplicated there.

### CODE REVIEW

**Review by progier389 — APPROVED** [review]
LGTM
FYI: For the write_audit_file_json leak, IMHO you had better redo the test after having removed the 'static' keyword from write_audit_file_json
so we will know more precisely where the leak is within write_audit_file_json

File: ldap/servers/slapd/entrywsi.c [hunk 1]
```diff
@@ -1186,7 +1186,7 @@ resolve_attribute_state_deleted_to_present(Slapi_Entry *e, Slapi_Attr *a, Slapi_
                 value_distinguished_at_csn(e, a, valuestoupdate[i], deletedcsn)) {
                 entry_deleted_value_to_present_value(a, valuestoupdate[i]);
             }
-            valuestoupdate[i]->v_csnset = NULL;
+            csnset_free(&valuestoupdate[i]->v_csnset);
```
Comment (tbordaz) [inline ldap/servers/slapd/entrywsi.c]: I agree we need to free the csnset when resetting it. 

Now I have a doubt about the reset. This algo moves the value (to present values) only if the value was updated (vucsn) after the the value was deleted (vdcsn) or attribute deleted (adcsn). I would expect the v_csnset to be reset ONLY if the value is moved back to present values but not systematically.
Else the value remains on deleted values but with a cleared history of csn.

File: ldap/servers/slapd/valueset.c [hunk 2]
```diff
@@ -1324,6 +1324,7 @@ valueset_remove_valuearray(Slapi_ValueSet *vs, const Slapi_Attr *a, Slapi_Value
                     if (found->v_csnset &&
                         (flags & (SLAPI_VALUE_FLAG_PRESERVECSNSET |
                                   SLAPI_VALUE_FLAG_USENEWVALUE))) {
+                        csnset_free(&valuestodelete[i]->v_csnset);
```
Comment (tbordaz) [inline ldap/servers/slapd/valueset.c:1327]: This line is correct. 
I think we also need to csnset_free the v_csnset a few line below when it is directly overwrite with found->v_csnset

**Review by tbordaz — COMMENTED** [review]
Fix looks good to me.
Few questions

File: ldap/servers/slapd/entrywsi.c (hunk 1 above)
Comment (vashirov) [reply ldap/servers/slapd/entrywsi.c]: I agree, moved it to the `if` block.

File: ldap/servers/slapd/valueset.c (hunk 2 above)
Comment (vashirov) [reply ldap/servers/slapd/valueset.c:1327]: Right, added another free to prevent a leak.

**Review by tbordaz — APPROVED** [review]
LGTM as well

File: ldap/servers/slapd/entrywsi.c (hunk 1 above)
Comment (vashirov) [reply ldap/servers/slapd/entrywsi.c]: I was running test for NDN crash and hit another crash that I traced back to this change.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  ber_bvcpy (bvs=0x7f1d00000000, bvd=0x7f1da2cd73c0) at ldap/servers/slapd/value.c:47
47          len = bvs->bv_len;
[Current thread is 1 (Thread 0x7f1db47fe640 (LWP 36576))]
(gdb) bt
#0  ber_bvcpy (bvs=0x7f1d00000000, bvd=0x7f1da2cd73c0) at ldap/servers/slapd/value.c:47
#1  ber_bvcpy (bvs=0x7f1d00000000, bvd=0x7f1da2cd73c0) at ldap/servers/slapd/value.c:40
#2  slapi_value_set_berval (bval=0x7f1d00000000, value=0x7f1da2cd73c0) at ldap/servers/slapd/value.c:322
#3  slapi_value_set_berval (value=value@entry=0x7f1da2cd73c0, bval=bval@entry=0x7f1d00000000) at ldap/servers/slapd/value.c:317
#4  0x00007f1e48b7d787 in value_init (v=v@entry=0x7f1da2cd73c0, bval=bval@entry=0x7f1d00000000, t=t@entry=0 '\000', csn=csn@entry=0x0)
    at ldap/servers/slapd/value.c:179
#5  0x00007f1e48b7d884 in value_new (bval=bval@entry=0x7f1d00000000, t=t@entry=0 '\000', csn=csn@entry=0x0) at ldap/servers/slapd/value.c:158
#6  0x00007f1e48b7ddb7 in slapi_value_dup (v=0x7f1d00000000) at ldap/servers/slapd/value.c:147
#7  0x00007f1e48b7e262 in valueset_set_valueset (vs2=0x7f1d502b5218, vs1=0x7f1da2c5b358) at ldap/servers/slapd/valueset.c:1244
#8  valueset_set_valueset (vs1=0x7f1da2c5b358, vs2=0x7f1d502b5218) at ldap/servers/slapd/valueset.c:1220
#9  0x00007f1e48add4af in slapi_attr_dup (attr=0x7f1d502b51e0) at ldap/servers/slapd/attr.c:396
#10 0x00007f1e48af0f60 in slapi_entry_dup (e=0x7f1da2c19000) at ldap/servers/slapd/entry.c:2036
#11 0x00007f1e442c734e in ldbm_back_modify (pb=0x7f1da2c00000) at ldap/servers/slapd/back-ldbm/ldbm_modify.c:741
#12 0x00007f1e48b30076 in op_shared_modify (pb=pb@entry=0x7f1da2c00000, pw_change=pw_change@entry=0, old_pw=0x0)
    at ldap/servers/slapd/modify.c:1079
#13 0x00007f1e48b30ced in do_modify (pb=pb@entry=0x7f1da2c00000) at ldap/servers/slapd/modify.c:377
#14 0x000055e990e2fd1c in connection_dispatch_operation (pb=0x7f1da2c00000, op=<optimized out>, conn=<optimized out>)
    at ldap/servers/slapd/connection.c:672
#15 connection_threadmain (arg=<optimized out>) at ldap/servers/slapd/connection.c:1955
#16 0x00007f1e48839bd4 in _pt_root (arg=0x7f1e439d9500) at pthreads/../../../../nspr/pr/src/pthreads/ptthread.c:191
#17 0x00007f1e4868a19a in start_thread (arg=<optimized out>) at pthread_create.c:443
#18 0x00007f1e4870f100 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

Now I think the code was correct and my change to move `csnset_free()` inside the `if` block introduced a regression. I'm running more tests with `csnset_free()` back outside the `if` block to see if it prevents the crash.
