### PR TITLE
Issue 4517 - BUG: Multiple systemd pin warnings

### LINKED ISSUE #4517: systemd pin warning appears multiple times
During startup we show a systemd-ask-pass warning for each entry that is a child of `cn=encryption,cn=config`. This can create a lot of log noise that may not be relevant.

The log message should be outside of this loop and only emitted once.

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: When multiple entries exist under
cn=encryption,cn=config then we log a warning for each
entry that systemd ask pass may be needed. This creates noise
when the warning is needed once.

Fix Description: Move the warning to outside the loop.

fixes: https://github.com/389ds/389-ds-base/issues/4517

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

File: ldap/servers/slapd/ssl.c [hunk 1]
```diff
@@ -1251,6 +1251,11 @@ slapd_ssl_init()
         slapd_extract_cert(entry, PR_TRUE);
     }
 
+#ifdef WITH_SYSTEMD
+    slapd_SSL_warn("Sending pin request to SVRCore. You may need to run"
+        " systemd-tty-ask-password-agent to provide the password if pin.txt does not exist.");
+#endif
+
```
Comment (mreynolds389) [inline ldap/servers/slapd/ssl.c:1258]: Perhaps this should be moved under this condition (before the for loop):

    if ((family_list = getChildren(configDN))) {

Because now it might get logged if SSL is not enabled?

**Review by mreynolds389 — APPROVED** [review]
Looks like my concern is invalid, security must be enabled to hit this code.

**Review by rohitpc363 — APPROVED** [review]

File: ldap/servers/slapd/ssl.c [hunk 2]
```diff
@@ -1305,11 +1310,7 @@ slapd_ssl_init()
...
             }
-/* authenticate */
-#ifdef WITH_SYSTEMD
-            slapd_SSL_warn("Sending pin request to SVRCore. You may need to run"
-                           " systemd-tty-ask-password-agent to provide the password.");
-#endif
+            /* authenticate */
             if (slapd_pk11_authenticate(slot, PR_TRUE, NULL) != SECSuccess) {
                 errorCode = PR_GetError();
                 slapi_log_err(SLAPI_LOG_ERR, "Security Initialization",
```
Comment (rohitpc363) [inline ldap/servers/slapd/ssl.c:1316]: Hi

**Review by rohitpc363 — APPROVED** [review]

**Review by rohitpc363 — APPROVED** [review]

**Review by droideck — APPROVED** [review]
Looks good to me too.

P.S. some weird spammer - rohitpc363 - got here... I've removed the message but I am not sure how to remove the 'approved' flood...

**Comment by Firstyear** [comment]
> Looks good to me too.
> 
> P.S. some weird spammer - rohitpc363 - got here... I've removed the message but I am not sure how to remove the 'approved' flood...

Maybe we should check the project settings about "who" can approve commits?

**Comment by Firstyear** [comment]
Updated the patch to remove the warning as we also called this during client-init which mean if you use tls client certs for replication authentication, it would log this message frequently.

**Review by mreynolds389 — APPROVED** [review]
LGTM
