### PR TITLE
Issue 4588 - BUG - unable to compile without xcrypt

### LINKED ISSUE #4588: Gost yescrypt may fail to build on some older versions of glibc.
**Issue Description**
```
/home/william/development/389ds/ds/ldap/servers/plugins/pwdstorage/gost_yescrypt.c:23:12: warning: implicit declaration of function 'crypt_rn' is invalid in C99 [-Wimplicit-function-declaration]
    hash = crypt_rn(userpwd, dbpwd, &output, (int) sizeof(output));
           ^
/home/william/development/389ds/ds/ldap/servers/plugins/pwdstorage/gost_yescrypt.c:23:10: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
    hash = crypt_rn(userpwd, dbpwd, &output, (int) sizeof(output));
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/william/development/389ds/ds/ldap/servers/plugins/pwdstorage/gost_yescrypt.c:41:15: error: use of undeclared identifier 'CRYPT_GENSALT_OUTPUT_SIZE'
    char salt[CRYPT_GENSALT_OUTPUT_SIZE];
              ^
/home/william/development/389ds/ds/ldap/servers/plugins/pwdstorage/gost_yescrypt.c:47:10: warning: implicit declaration of function 'crypt_gensalt_rn' is invalid in C99 [-Wimplicit-function-declaration]
    if (!crypt_gensalt_rn(prefix, 0, ((void*)0), 0, salt, (int) sizeof(salt))) {
         ^
/home/william/development/389ds/ds/ldap/servers/plugins/pwdstorage/gost_yescrypt.c:53:12: warning: implicit declaration of function 'crypt_rn' is invalid in C99 [-Wimplicit-function-declaration]
    hash = crypt_rn(pwd, salt, &output, (int) sizeof(output));
           ^
4 warnings and 1 error generated.
```

This appears to be due to missing defines in crypt.h on older glibc. 

**Package Version and Platform:**
SLE 15.2 glibc-2.26-13.51.1.x86_64

does not affect SUSE TW glibc-2.32-4.1.x86_64

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: If xcrypt is not available, especially on some
distros with older libraries, 389 was unable to build.

Fix Description: Detect if we have xcrypt, and if not, add
stubs that always error instead.

fixes: https://github.com/389ds/389-ds-base/issues/4588

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

**Review by progier389 — APPROVED** [review]
LGTM

**Comment by jchapma** [comment]
Me too

File: ldap/servers/plugins/pwdstorage/gost_yescrypt.c [hunk 1]
```diff
@@ -62,3 +63,25 @@ gost_yescrypt_pw_enc(const char *pwd)
...
+#else
+
+/*
+ * We do not have xcrypt, so always fail all checks.
+ */
+int
+gost_yescrypt_pw_cmp(const char *userpwd __attribute__((unused)), const char *dbpwd __attribute__((unused)))
+{
+    slapi_log_err(SLAPI_LOG_ERR, GOST_YESCRYPT_SCHEME_NAME,
+                  "Unable to use GOST_YESCRYPT, xcrypt is not available.\n");
```
Comment (droideck) [inline ldap/servers/plugins/pwdstorage/gost_yescrypt.c]: It's really more of a nitpick, - it looks to me that the error message will look like 

```
"ERR - GOST_YESCRYPT - Unable to use GOST_YESCRYPT, xcrypt is not available."
```

As a thought, may be it makes sense to use the function name `'gost_yescrypt_pw_cmp'` instead of `GOST_YESCRYPT_SCHEME_NAME` so we can avoid redundancy?

**Review by droideck — APPROVED** [review]
The rest looks good!
And feel free to push like this if you don't agree with my proposal :)

File: ldap/servers/plugins/pwdstorage/gost_yescrypt.c (hunk 1 above)
Comment (Firstyear) [reply ldap/servers/plugins/pwdstorage/gost_yescrypt.c]: Yes, this is a good point.
