### PR TITLE
UI - migrate the remaining components to PF4

### LINKED ISSUE #4149: PR - Issue 51095 - Check the return code from the time functions
Cloned from Pagure Pull-Request: https://pagure.io/389-ds-base/pull-request/51096
- Created at 2020-05-18 22:19:24 by [mreynolds](https://pagure.io/user/mreynolds) (@mreynolds389)
- Merged at 2020-05-22 16:57:58

---

Bug Description:  

On some cloud platforms we see issues with replication time skew.  It's not clear if the time functions are failing or just returning the wrong value.  We do not check the result code from any of the time functions.

Fix Description:  

Add a wrapper function for clock_gettime() that will check for errors, log a message, and retry a few times.  We retry because getting the time is so critical to things like replication and logging.

Also added a check for large jump in CSN generation times, and we log a message if detected.

relates: Resolves: #4148

### PR DESCRIPTION
**Pull request by mreynolds389**
Description:  This completes the initial migration to PF4
    
fixes: https://github.com/389ds/389-ds-base/issues/4149

### CODE REVIEW

File: src/cockpit/389-console/src/dsModals.jsx [hunk 1]
```diff
@@ -493,33 +400,14 @@ export class CreateInstanceModal extends React.Component {
...
-            // No errors, but to keep the modal nice and stable during input
-            // field validation we need "invisible" text to keep the modal form
-            // from jumping up and down.
-            errMsgClass = "ds-clear-text";
-            errMsg = "no errors";
-        } else {
-            // We have error text to report
-            errMsgClass = "ds-modal-error";
-            errMsg = modalMsg;
+        let saveBtnName = "Create Instance";
```
Comment (droideck) [inline src/cockpit/389-console/src/dsModals.jsx:406]: When I create an instance, I've got a browser crush with the next error:

```
CMD: setServerId: Test if instance is running  ==> dsctl -j localhost status
cockpit.js:1 {
    "desc": "'NoneType' object has no attribute 'get'"
}
```

But when I reload the page, the instance is installed (but not started)
And when I try to start it in the UI, it hangs...

When I try to start the instance through CLI, it waits for input. So it may be a part of the problem, as UI doesn't like interactive input usually (but you can provide the input if you want. I've used it for inputing credentials - https://github.com/389ds/389-ds-base/blob/master/src/cockpit/389-console/src/lib/monitor/replMonitor.jsx#L1071 )

**Review by droideck — CHANGES_REQUESTED** [review]
The issue actually blocks further review as I can't enter the instance...

File: src/cockpit/389-console/src/dsModals.jsx (hunk 1 above)
Comment (mreynolds389) [reply src/cockpit/389-console/src/dsModals.jsx:406]: I don't get a browser crash but I hit the NSS issue with lib389.  The UI also does not use the interactive installer but it creates a INF file (dscreate from-file).   I think a change in lib389 got pulled in on the rebase.  I will investigate...

Comment (mreynolds389) [reply src/cockpit/389-console/src/dsModals.jsx:406]: Ok, it was a cockpit issue with a shell command that was being passed in.  This created a corrupted instance that caused all the weird behavior.  This is fixed now, please review...

File: src/cockpit/389-console/src/dsModals.jsx [hunk 2]
```diff
@@ -1217,14 +1114,13 @@ export class ManageBackupsModal extends React.Component {
...
                 >
-                    <div className="ds-margin-top-xlg">
-                        <BackupTable
-                            rows={backups}
-                            key={backups}
-                            confirmRestore={this.showConfirmRestore}
-                            confirmDelete={this.showConfirmBackupDelete}
-                        />
-                    </div>
+                    <BackupTable
```
Comment (droideck) [inline src/cockpit/389-console/src/dsModals.jsx:1110]: Backup creation fails:

```
CMD: doBackup: Add backup task online ==> dsconf -j ldapi://%2fvar%2frun%2fslapd-ldapi://%2fvar%2frun%2fslapd-localhost.socket.socket backup create 123123
cockpit.js:1 {
    "result": -1,
    "desc": "Can't contact LDAP server",
    "errno": 2,
    "ctrls": [],
    "info": "No such file or directory"
}
```

Looks like an invalid filename (path.socket.socket)

P.S. but database tab backups work fine...

File: src/cockpit/389-console/src/ds.jsx [hunk 3]
```diff
@@ -527,7 +542,11 @@ export class DSInstance extends React.Component {
             mainContent = (
                 <div id="loading-instances" className="all-pages ds-center">
                     <div id="loading-page" className="ds-center ds-loading">
-                        <h4 id="loading-msg">Loading Directory Server Configuration ...</h4>
+                        <TextContent>
+                            <Text id="loading-msg" component={TextVariants.h3}>
+                                Loading Directory Server Configuration ...
```
Comment (droideck) [inline src/cockpit/389-console/src/ds.jsx:547]: When I have two instances and both of them are stoped, and if I try two switch between them, then I get a strange error which probably will be a bit confusing for the user:

```
Failed to get attributes - Can't contact LDAP server
```

File: src/cockpit/389-console/src/lib/database/attrEncryption.jsx [hunk 4]
```diff
@@ -180,20 +222,30 @@ export class AttrEncryption extends React.Component {
...
+                            spinnerAriaValueText={this.state.saving ? "Saving" : undefined}
+                            {...extraPrimaryProps}
                         >
-                            Add Attribute
+                            {saveBtnName}
                         </Button>
                     </GridItem>
                 </Grid>
-                <ConfirmPopup
+                <DoubleConfirmModal
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/database/attrEncryption.jsx:235]: This modal is not auto-closed after the attribute is deleted.

File: src/cockpit/389-console/src/lib/database/attrEncryption.jsx [hunk 5]
```diff
@@ -81,9 +96,9 @@ export class AttrEncryption extends React.Component {
     }
 
     addEncryptedAttr () {
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/database/attrEncryption.jsx:98]: It is possible to add comma-separated attributes which also have duplicated across each other.

image

Also, the multi-select works strangely... (it looks like single-select but acts like multi-select)

File: src/cockpit/389-console/src/lib/database/chaining.jsx [hunk 6]
```diff
@@ -847,6 +862,7 @@ export class ChainingDatabaseConfig extends React.Component {
                             >
                                 {saveBtnName}
                             </Button>
+                            <hr />
                         </div>
                     </Tab>
                     <Tab eventKey={1} title={<TabTitleText><b>Controls & Components</b></TabTitleText>}>
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/database/chaining.jsx:868]: The tab doesn't have any space at the bottom so it looks a bit weird (I have it on 125% zoom which I get used to. 110% looks fine though) 

image

File: src/cockpit/389-console/src/lib/database/indexes.jsx [hunk 7]
```diff
@@ -951,7 +955,11 @@ class AddIndexModal extends React.Component {
                 ]}
             >
                 <Form isHorizontal autoComplete="off">
-                    <h5 title="Select an attribute to index">Select An Attribute</h5>
+                    <TextContent title="Select an attribute to index">
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/database/indexes.jsx:954]: If I try to delete an index, it fails for me with the next error:

```
CMD: deleteIndex: deleteEdit index ==> dsconf -j ldapi://%2fvar%2frun%2fslapd-localhost.socket backend index delete --attr=[object Object] dc=example,dc=com
cockpit.js:1 {
    "desc": "Can not delete index because it does not exist"
}
```

By some reason, '--attr=[object Object]'...

File: src/cockpit/389-console/src/lib/database/vlvIndexes.jsx [hunk 8]
```diff
@@ -560,7 +563,7 @@ class AddVLVIndexModal extends React.Component {
                 aria-labelledby="ds-modal"
                 title="Create VLV Sort Index"
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/database/vlvIndexes.jsx:564]: I try to create the Sort Index with 'reindexing' -> Success but the table is not updated

After that, I try to create it once again without reindexing and it hangs (I add one more attribute to the multi-select though). If you can't reproduce the hang like that - I may broke the instance by setting a lot of weird database settings. :D

File: src/cockpit/389-console/src/lib/monitor/accesslog.jsx [hunk 9]
```diff
@@ -88,70 +98,72 @@ export class AccessLogMonitor extends React.Component {
...
-                    <Col sm={6}>
-                        {selectLines}
-                    </Col>
-                    <Col sm={6}>
+                    </GridItem>
+                </Grid>
+                <Grid className="ds-margin-top-lg ds-indent">
+                    <GridItem span={2}>
+                        <FormSelect
+                            id="accessLines"
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/monitor/accesslog.jsx:129]: I can't change the lines value from '50' to anything else

File: src/cockpit/389-console/src/lib/plugins/attributeUniqueness.jsx [hunk 10]
```diff
@@ -656,236 +597,189 @@ class AttributeUniqueness extends React.Component {
...
+                                <FormSelect
+                                    id="topEntryOc"
+                                    value={topEntryOc}
+                                    onChange={(value, event) => {
+                                        this.handleFieldChange(event);
+                                    }}
+                                    aria-label="FormSelect Input"
+                                >
+                                    <FormSelectOption key="no-setting" value="" label="-" />
+                                    {this.props.objectClasses.map((attr, index) => (
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/plugins/attributeUniqueness.jsx:732]: For some reason, both - Top Entry OC and Subtree Entry's OC - selects are empty and it's not possible to select something there.

File: src/cockpit/389-console/src/lib/plugins/memberOf.jsx [hunk 11]
```diff
@@ -790,316 +1123,322 @@ class MemberOf extends React.Component {
...
                             </Form>
-                        </Col>
-                    </Row>
+                        </GridItem>
+                    </Grid>
                 </Modal>
                 <Modal
                     variant={ModalVariant.medium}
                     aria-labelledby="ds-modal"
                     title="Manage MemberOf Plugin Shared Config Entry"
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/plugins/memberOf.jsx:1259]: In the shared config creation modal for MemberOf plugin, if I click on 'Subtree Scope' left cross - it crushes the browser.

image

File: src/cockpit/389-console/src/lib/plugins/pluginTables.jsx [hunk 12]
```diff
@@ -158,26 +159,43 @@ class PluginTable extends React.Component {
...
+                <GridItem span={4}><b>Plugin Version:</b></GridItem>
+                <GridItem span={8}><i>{rowData["nsslapd-pluginVersion"][0]}</i></GridItem>
+                <GridItem span={4}><b>Plugin Depends On Named:</b></GridItem>
+                <GridItem span={8}><i>{dependsNamed}</i></GridItem>
+                <GridItem span={4}><b>Plugin Depends On Type:</b></GridItem>
+                <GridItem span={8}><i>{dependsType}</i></GridItem>
+                <GridItem span={4}><b>Plugin Precedence:</b></GridItem>
+                <GridItem span={8}><i>{precedence}</i></GridItem>
+                <GridItem span={12} className="ds-margin-top-lg">
+                    <Switch
```
Comment (droideck) [inline src/cockpit/389-console/src/lib/plugins/pluginTables.jsx:190]: If I switch it 'on/off' it shows a notification but it's a "green" notification. I think it makes sense to keep it consistent with other places where we post it as a 'warning' type.

image

image

But it's minor and it's fully up to you :)

**Review by droideck — CHANGES_REQUESTED** [review]
Oh, it's big.
I found a couple of small issues but otherwise - looks very good.
Also, a very nice feature with 'enabled/disabled' icon on Plugins tab! Looks much more intuitive than before.

File: src/cockpit/389-console/src/lib/database/chaining.jsx (hunk 6 above)
Comment (mreynolds389) [reply src/cockpit/389-console/src/lib/database/chaining.jsx:868]: I like using 90% zoom actually, but yeah easy fix.  I had to do that alot after moving to PF4 (I just missed this one)

File: src/cockpit/389-console/src/lib/database/attrEncryption.jsx (hunk 5 above)
Comment (mreynolds389) [reply src/cockpit/389-console/src/lib/database/attrEncryption.jsx:98]: I can not reproduce this.  I can only select one attribute (as intended).  Nor can I get it to use commas.  What are you doing exactly?

File: src/cockpit/389-console/src/lib/plugins/memberOf.jsx (hunk 11 above)
Comment (mreynolds389) [reply src/cockpit/389-console/src/lib/plugins/memberOf.jsx:1259]: Hmmm can not reproduce this.

File: src/cockpit/389-console/src/lib/database/attrEncryption.jsx (hunk 5 above)
Comment (mreynolds389) [reply src/cockpit/389-console/src/lib/database/attrEncryption.jsx:98]: I can reproduce it, and fixed

File: src/cockpit/389-console/src/lib/plugins/memberOf.jsx (hunk 11 above)
Comment (mreynolds389) [reply src/cockpit/389-console/src/lib/plugins/memberOf.jsx:1259]: Reproduced and fixed

File: src/cockpit/389-console/src/lib/database/vlvIndexes.jsx (hunk 8 above)
Comment (mreynolds389) [reply src/cockpit/389-console/src/lib/database/vlvIndexes.jsx:564]: This is a regression in the core VLV code in the server (bdb vs lmdb).  It is unrelated to this work.

File: src/cockpit/389-console/src/lib/database/indexes.jsx (hunk 7 above)
Comment (droideck) [reply src/cockpit/389-console/src/lib/database/indexes.jsx:954]: I still experience the error...

```
CMD: deleteIndex: deleteEdit index ==> dsconf -j ldapi://%2fvar%2frun%2fslapd-supplier1.socket backend index delete --attr=[object Object] dc=example,dc=com
cockpit.js:1 {
    "desc": "Can not delete index because it does not exist"
}
```

It happens in 'Database' -> 'Suffixes' -> 'dc=example,dc=com' -> 'Indexes' -> 'Database Indexes (20)'

**Review by droideck — APPROVED** [review]
Looks good to me! Ack
