### PR TITLE
Issue 7124 - BDB cursor race condition with transaction isolation

### LINKED ISSUE #7124: BDB cursor race condition
**Issue Description**
ASAN reported crashes in `__db_ditem_nolog()` with negative-size-param errors:

```
=================================================================
==109094==ERROR: AddressSanitizer: negative-size-param: (size=-8)
    #0 0x7fadfdce4329 in memmove (/usr/lib64/libasan.so.8+0xe4329) (BuildId: 0adabddcb77130fc2ea3840d060eb4e8a9ae0c85)
    #1 0x7badf6dcb1e8 in __db_ditem_nolog (/lib64/libdb-5.3.so+0xe51e8) (BuildId: 8d20c7e9865bc743660a55af97fad4f11e754da6)
    #2 0x7badf6dcc3db in __db_ditem (/lib64/libdb-5.3.so+0xe63db) (BuildId: 8d20c7e9865bc743660a55af97fad4f11e754da6)
    #3 0x7badf6d020f7 in __bamc_physdel.lto_priv.0 (/lib64/libdb-5.3.so+0x1c0f7) (BuildId: 8d20c7e9865bc743660a55af97fad4f11e754da6)
    #4 0x7badf6cfc654 in __bamc_close (/lib64/libdb-5.3.so+0x16654) (BuildId: 8d20c7e9865bc743660a55af97fad4f11e754da6)
    #5 0x7badf6dc063c in __dbc_close (/lib64/libdb-5.3.so+0xda63c) (BuildId: 8d20c7e9865bc743660a55af97fad4f11e754da6)
    #6 0x7badf6dd6c7e in __dbc_close_pp (/lib64/libdb-5.3.so+0xf0c7e) (BuildId: 8d20c7e9865bc743660a55af97fad4f11e754da6)
    #7 0x7badf6f69979 in bdb_public_cursor_op ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c:6883
    #8 0x7badf6ec70b1 in dblayer_cursor_op (/usr/lib64/dirsrv/plugins/libback-ldbm.so+0xf0b1) (BuildId: d6d3dd3b3eb64308d950b7f200a3e0c0af52c064)
    #9 0x7badf6ed59c4 in idl_new_fetch ldap/servers/slapd/back-ldbm/idl_new.c:316
    #10 0x7badf6ed8955 in index_read_ext_allids ldap/servers/slapd/back-ldbm/index.c:1074
    #11 0x7badf6ecd8d6 in keys2idl ldap/servers/slapd/back-ldbm/filterindex.c:1113
    #12 0x7badf6ece374 in ava_candidates ldap/servers/slapd/back-ldbm/filterindex.c:315
    #13 0x7badf6ecf327 in filter_candidates_ext ldap/servers/slapd/back-ldbm/filterindex.c:99
    #14 0x7badf6ece91c in list_candidates ldap/servers/slapd/back-ldbm/filterindex.c:902
    #15 0x7badf6ecf06f in filter_candidates_ext ldap/servers/slapd/back-ldbm/filterindex.c:132
    #16 0x7badf6ece91c in list_candidates ldap/servers/slapd/back-ldbm/filterindex.c:902
    #17 0x7badf6ecf06f in filter_candidates_ext ldap/servers/slapd/back-ldbm/filterindex.c:132
    #18 0x7badf6ecffb1 in filter_candidates ldap/servers/slapd/back-ldbm/filterindex.c:162
    #19 0x7badf6f02d83 in onelevel_candidates ldap/servers/slapd/back-ldbm/ldbm_search.c:1226
    #20 0x7badf6f02d83 in build_candidate_list ldap/servers/slapd/back-ldbm/ldbm_search.c:1083
    #21 0x7badf6f02d83 in ldbm_back_search ldap/servers/slapd/back-ldbm/ldbm_search.c:665
    #22 0x7fadfd8807a1 in op_shared_search (/usr/lib64/dirsrv/libslapd.so.0+0x807a1) (BuildId: a14622b2d8d9edb0bdaeaf935d826d6afed08fb1)
    #23 0x55b06d9cd9b2 in do_search ldap/servers/slapd/search.c:411
    #24 0x55b06d9cd9b2 in connection_dispatch_operation ldap/servers/slapd/connection.c:760
    #25 0x55b06d9d00b2 in connection_threadmain ldap/servers/slapd/connection.c:2058
    #26 0x7fadfdbe0e02 in _pt_root (/lib64/libnspr4.so+0x22e02) (BuildId: 2874c2e4a121e04f5d61efad2b30ed6a1a014792)
    #27 0x7fadfdc28ee5 in asan_thread_start(void*) (/usr/lib64/libasan.so.8+0x28ee5) (BuildId: 0adabddcb77130fc2ea3840d060eb4e8a9ae0c85)
    #28 0x7fadfd67ff53 in start_thread (/lib64/libc.so.6+0x71f53) (BuildId: 48c4b9b1efb1df15da8e787f489128bf31893317)
    #29 0x7fadfd70332b in __clone3 (/lib64/libc.so.6+0xf532b) (BuildId: 48c4b9b1efb1df15da8e787f489128bf31893317)

Address 0x7badad6e9768 is a wild pointer inside of access range of size 0x000000000001.
SUMMARY: AddressSanitizer: negative-size-param (/lib64/libdb-5.3.so+0xe51e8) (BuildId: 8d20c7e9865bc743660a55af97fad4f11e754da6) in __db_ditem_nolog
Thread T15 created by T0 here:
    #0 0x7fadfdcde492 in pthread_create (/usr/lib64/libasan.so.8+0xde492) (BuildId: 0adabddcb77130fc2ea3840d060eb4e8a9ae0c85)
    #1 0x7fadfdbe0b0a in _PR_CreateThread (/lib64/libnspr4.so+0x22b0a) (BuildId: 2874c2e4a121e04f5d61efad2b30ed6a1a014792)
    #2 0x7fadfdbe11c2 in PR_CreateThread (/lib64/libnspr4.so+0x231c2) (BuildId: 2874c2e4a121e04f5d61efad2b30ed6a1a014792)
    #3 0x55b06d9d2975 in init_op_threads ldap/servers/slapd/connection.c:501
    #4 0x55b06d9d2975 in slapd_daemon ldap/servers/slapd/daemon.c:1209
    #5 0x55b06d9c2dda in main (/usr/bin/ns-slapd+0x4dda) (BuildId: 8b68deaa20208d17014b9e0bcb53b7342a9185eb)
    #6 0x7fadfd611574 in __libc_start_call_main (/lib64/libc.so.6+0x3574) (BuildId: 48c4b9b1efb1df15da8e787f489128bf31893317)
    #7 0x7fadfd611627 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x3627) (BuildId: 48c4b9b1efb1df15da8e787f489128bf31893317)
    #8 0x55b06d9c42f4 in _start (/usr/bin/ns-slapd+0x62f4) (BuildId: 8b68deaa20208d17014b9e0bcb53b7342a9185eb)

==109094==ABORTING
```

Cursor operations without transaction isolation allowed concurrent page modifications to corrupt cursor state, leading to invalid memory access.
The race condition occurs when:
1. T1 opens a cursor without transaction protection
2. T2 modifies the same index page
3. T1 cursor operates on stale page metadata
4. `__db_ditem_nolog()` calculates negative size for `memmove()`
5. Crash: `AddressSanitizer: negative-size-param: (size=-8)`

**Package Version and Platform:**
 - Platform: RHEL, Fedora (with BDB backend)
 - Package and version: all versions

**Steps to Reproduce**
1. Load the server with multiple search/modify/del operations that target indexes with multivalued attributes (objectClass, description, telephoneNumber). CI test will be attached to PR.

**Expected results**
No crash

### PR DESCRIPTION
**Pull request by vashirov**
Bug Description:
ASAN reported crashes in `__db_ditem_nolog()` with negative-size-param errors. Cursor operations without transaction isolation allowed concurrent page modifications to corrupt cursor state, leading to invalid memory access.

The race condition occurs when:
1. T1 opens a cursor without transaction protection
2. T2 modifies the same index page
3. T1 cursor operates on stale page metadata
4. `__db_ditem_nolog()` calculates negative size for `memmove()`
5. Crash: `AddressSanitizer: negative-size-param: (size=-8)`

Reproducer: dirsrvtests/tests/stress/backend/bdb_cursor_race_test.py Crash under ASAN usually happens within 10-30 minutes, but sometimes it can run for hours without any crash.

Fix Description:
Implement transaction isolation for cursors in `idl_new_fetch()` and
`idl_new_range_fetch()` by always calling `dblayer_read_txn_begin()`.

In `bdb_txn_begin()` verify if the environment supports transactions
(has DB_INIT_TXN flag) before attempting to begin a transaction.
This prevents errors during offline import which uses a private
environment without transaction support.

In `bdb_public_new_cursor()` skip transaction usage when the database's
environment doesn't support transactions.

Fixes: https://github.com/389ds/389-ds-base/issues/7124

## Summary by Sourcery

Ensure BDB cursor operations run under transaction isolation to prevent race conditions and crashes, and add a stress test that exercises high-contention search/modify/delete workloads.

Bug Fixes:
- Guard BDB cursor-based index fetch operations with a dedicated or caller-provided read transaction to avoid cursor state corruption and negative-size memory operations.

Enhancements:
- Adjust transaction-begin logic to respect explicitly zeroed transaction structures so callers can force isolated, non-nested transactions for cursor operations.

Tests:
- Introduce a long-running stress test that drives concurrent searches, modifications, deletions, and add/delete churn to reproduce and guard against BDB cursor race conditions.

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/idl_new.c [hunk 1]
```diff
@@ -199,13 +199,26 @@ idl_new_fetch(
     dblayer_bulk_set_buffer(be, &bulkdata, buffer, sizeof(buffer), DBI_VF_BULK_DATA);
     memset(&dataret, 0, sizeof(dataret));
 
-    dblayer_txn_init(li, &s_txn);
-    if (txn) {
-        dblayer_read_txn_begin(be, txn, &s_txn);
+    /*
```
Comment (progier389) [inline ldap/servers/slapd/back-ldbm/idl_new.c:202]: This  change looks wrong as it remove the sub txn s_txn if the txn is present.
IMHO the only needed change should be 
```
- if (txn) {
-      dblayer_read_txn_begin(be, txn, &s_txn);
- }
+ dblayer_read_txn_begin(be, txn, &s_txn);
```
so there is always a txn or sub txn
then you should keep the old code unchanged

Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/idl_new.c:202]: Hmm, with this change it fails to create ancestorid index during initial instance creation:

```
[02/Dec/2025:16:24:37.207604281 +0000] - INFO - bdb_ancestorid_new_idl_create_index - import userRoot: Creating ancestorid index (new idl)...
[02/Dec/2025:16:24:37.209578591 +0000] - ERR - libdb - BDB0103 DB environment not configured for transactions
[02/Dec/2025:16:24:37.211562534 +0000] - ERR - bdb_map_error - bdb_public_new_cursor failed with db error 22 : Invalid argument
[02/Dec/2025:16:24:37.213404972 +0000] - ERR - idl_new_fetch - idl_new.c - parentid BAD 1, err=-12793 Database operation error:  Unhandled Database operation error. See details in previous error messages.
[02/Dec/2025:16:24:37.215335773 +0000] - ERR - bdb_ancestorid_new_idl_create_index - bdb_import.c BAD 13070, err=-12793 Database operation error:  Unhandled Database operation error. See details in previous error messages.
[02/Dec/2025:16:24:37.217213151 +0000] - ERR - bdb_ancestorid_new_idl_create_index - Failed to create ancestorid index
[02/Dec/2025:16:24:37.219659080 +0000] - ERR - bdb_public_bdb_import_main - import userRoot: Failed to create ancestorid index
[02/Dec/2025:16:24:37.221902999 +0000] - INFO - bdb_public_bdb_import_main - import userRoot: Closing files...
[02/Dec/2025:16:24:37.254879703 +0000] - ERR - bdb_public_bdb_import_main - import userRoot: Import failed.
```

Comment (progier389) [reply ldap/servers/slapd/back-ldbm/idl_new.c:202]: OK. I think that we should tweak bdb_txn_begin to check if
  DB_ENV->get_open_flags()  & DB_INIT_TXN == 0
  and if yes just return success without doing anything.

File: ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c [hunk 2]
```diff
@@ -2841,8 +2841,13 @@ bdb_txn_begin(struct ldbminfo *li, back_txnid parent_txn, back_txn *txn, PRBool
         bdb_db_env *pEnv = (bdb_db_env *)priv->dblayer_env;
         if (use_lock)
             slapi_rwlock_rdlock(pEnv->bdb_env_lock);
-        if (!parent_txn) {
-            /* see if we have a stored parent txn */
+        if (!parent_txn && txn && txn->back_txn_txn) {
+            /*
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c]: Few lines above if (txn) then txn->back_txn_txn was reset. So this block becomes a dead block.

File: ldap/servers/slapd/back-ldbm/idl_new.c [hunk 3]
```diff
@@ -469,13 +485,26 @@ idl_new_range_fetch(
...
+     * Use the provided transaction if available, otherwise create one.
+     * This prevents race conditions where concurrent page modifications
+     * corrupt cursor state, leading to crashes in __db_ditem_nolog().
+     */
+    dbi_txn_t *cursor_txn = txn;
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/idl_new.c]: This looks good. Another implementation is to create the transaction (txn=NULL) directly in index_read_ext_allids before the IDL_FETCH_RETRY_COUNT loop. Under pression, the txn is created once instead of on each try.

File: ldap/servers/slapd/back-ldbm/idl_new.c (hunk 1 above)
Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/idl_new.c:202]: Thanks for the pointer! I've updated `bdb_txn_begin()` to verify if the environment supports transactions. And in `bdb_public_new_cursor()` skip transaction usage when the environment doesn't support them.
Now the tests don't fail during offline import.

File: ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c (hunk 2 above)
Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c]: I removed this change.

File: dirsrvtests/tests/suites/import/regression_test.py [hunk 4]
```diff
@@ -849,6 +850,9 @@ def fin():
                     fout.write(line)
 
         os.chmod(e.ldif, 0o644)
+        # Make sure dirsrv user can read the file for offline import
+        dirsrv_user = pwd.getpwnam('dirsrv')
```
Comment (progier389) [inline dirsrvtests/tests/suites/import/regression_test.py]: To avoid breaking test for people like me that tend to run the test in the user environment
this change should better be in 
if os.getuid() == 0:

**Review by progier389 — COMMENTED** [review]
Looks good for the C code,
regression_test.py needs a quick change

**Review by tbordaz — APPROVED** [review]
LGTM
My understanding is that read operations that were done without txn will now be blocked by others updates. correct ?

**Review by progier389 — APPROVED** [review]
LGTM
