### PR TITLE
Issue 6110 - Typo in Account Policy plugin message

### LINKED ISSUE #6110: Typo in Account Policy plugin message
**Issue Description**
When saving configuration for Account Policy Plugin, the confirming message says "Config entry cn=config,cn=Account Policy Plugin,cn=plugins,cn=config was successfully seted". It should be 'set'

**Package Version and Platform:**
389-ds-base-2.0.14-7.module+el9dsrv+14845+69b2f526.x86_64
cockpit-389-ds-2.0.14-7.module+el9dsrv+14845+69b2f526.noarch

**Steps to Reproduce**
1. Go to Plugins tab -> Click Account Policy
2. Enable plugin -> restart
3. Create Config
4. Check "Always Record Login"
5. Click Add config

### PR DESCRIPTION
**Pull request by bsimonova**
Description:
Remove the additional letters after success message

Fixes: https://github.com/389ds/389-ds-base/issues/6110

Reviewed by: ???

### CODE REVIEW

File: src/cockpit/389-console/src/lib/plugins/accountPolicy.jsx [hunk 1]
```diff
@@ -490,7 +490,7 @@ class AccountPolicy extends React.Component {
                     console.info("accountPolicyOperation", "Result", content);
                     this.props.addNotification(
                         "success",
-                        cockpit.format(_("Config entry $0 was successfully $1ed"), configDN, action)
+                        cockpit.format(_("Config entry $0 was successfully $1"), configDN, action)
```
Comment (progier389) [inline src/cockpit/389-console/src/lib/plugins/accountPolicy.jsx]: The code seems generic 
  I suspect that action may be "add" and in this case it should display "added"
  IMHO you had better test explicitly for action == set

**Review by progier389 — CHANGES_REQUESTED** [review]

File: src/cockpit/389-console/src/lib/plugins/accountPolicy.jsx (hunk 1 above)
Comment (bsimonova) [reply src/cockpit/389-console/src/lib/plugins/accountPolicy.jsx]: Yes, it is generic. 
In my steps working around the config entry always produced 'set' currently for all outcomes.
So I went for the generic modification as well.
But I see it might cause issue for 'add' and 'delete' option :( 
I am open to other approaches as I took this as a learning opportunity around cockpit code.

Comment (progier389) [reply src/cockpit/389-console/src/lib/plugins/accountPolicy.jsx]: FYI: I was thinking about something like:
 if (action === "set") {
      cockpit.format(_("Config entry $0 was successfully set"), configDN, action)
 } else {
      cockpit.format(_("Config entry $0 was successfully $1ed"), configDN, action)
   }
But if the function is called with "set" in all cases, then your code is fine !

**Review by progier389 — APPROVED** [review]
LGTM

File: src/cockpit/389-console/src/lib/plugins/accountPolicy.jsx (hunk 1 above)
Comment (droideck) [reply src/cockpit/389-console/src/lib/plugins/accountPolicy.jsx]: I think you can just do something like this:

```
cockpit.format(_("Config entry $0 was successfully $1"), configDN, action === "add" ? "added" : "set")
```

or assign it to a const prior somewhere along the line:

```
  const actionPastTense = action === "add" ? "added" : "set";
  this.props.addNotification(
                        "success",
                        cockpit.format(_("Config entry $0 was successfully $1"), configDN, actionPastTense)
                        );
 ```

**Review by droideck — CHANGES_REQUESTED** [review]

File: src/cockpit/389-console/src/lib/plugins/accountPolicy.jsx (hunk 1 above)
Comment (bsimonova) [reply src/cockpit/389-console/src/lib/plugins/accountPolicy.jsx]: Thank you both.
I will apply these.

**Review by droideck — APPROVED** [review]
