### PR TITLE
Issue 7440 - Substring index produces empty results and can crash whe…

### LINKED ISSUE #7440: Substring index produces empty results and can crash when non-default nsSubStrBegin/nsSubStrEnd lengths are configured
**Issue Description**
Configured non-default substring index lengths (nsSubStrBegin, nsSubStrEnd) on the `uid` attribute index, reindexed and searched for entries using a substring filter `(uid=a*)`. The search returned 0 results despite matching entries existing in the database.

And when setting values `(begin + end) > middle*2)`, for example begin=2, end=3, middle=2, then triggering a reindex,  server crashes with SEGV:

```
(gdb) bt
#0  prepare_key
    (be=be@entry=0x7f56e121eac0, a=a@entry=0x7f56e3e9dce0, buf=buf@entry=0x7f51b5ff1a40, buflen=buflen@entry=0x7f51b5ff1a48, flags=flags@entry=17, prefix=<optimized out>, prefix@entry=0x7f56e10fd030 <prefix_SUB> "*", bvp=0x1, key=0x7f51b5ff1a60)
    at ldap/servers/slapd/back-ldbm/index.c:893
#1  0x00007f56e0fd5263 in addordel_values_sv
    (be=be@entry=0x7f56e121eac0, db=db@entry=0x7f56e12d37a0, indextype=<optimized out>, vals=<optimized out>, id=id@entry=7, flags=flags@entry=17, txn=0x7f51b5ff3dd0, a=0x7f56e3e9dce0, idl_disposition=0x0, buffer_handle=0x0, type=0x7f51b5ff3bc0 "uid")
    at ldap/servers/slapd/back-ldbm/index.c:1955
#2  0x00007f56e0fd5f19 in index_addordel_values_ext_sv
    (be=0x7f56e121eac0, type=<optimized out>, vals=0x7f51bd01f920, evals=<optimized out>, id=7, flags=17, txn=0x7f51b5ff3dd0, idl_disposition=0x0, buffer_handle=0x0) at ldap/servers/slapd/back-ldbm/index.c:2162
#3  0x00007f56e0fd6498 in index_addordel_values_sv
    (be=<optimized out>, type=<optimized out>, vals=<optimized out>, evals=<optimized out>, id=<optimized out>, flags=<optimized out>, txn=0x7f51b5ff3dd0) at ldap/servers/slapd/back-ldbm/index.c:2032
#4  0x00007f56e105520f in process_regular_index (ep=0x7f51bd006580, info=<optimized out>)
    at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:3156
#5  dbmdb_import_worker (param=<optimized out>) at ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c:3352
#6  0x00007f56e6167e63 in _pt_root (arg=0x7f51c04678c0) at ../../../../nspr/pr/src/pthreads/ptthread.c:191
#7  0x00007f56e587f464 in start_thread () at /lib64/libc.so.6
#8  0x00007f56e59025ec in __clone3 () at /lib64/libc.so.6
```

**Package Version and Platform:**
 - Platform: RHEL/Fedora
 - Package and version: 389-ds-base-3.2.0-6.el10.x86_64

**Steps to Reproduce**
1. Modify `uid` index entry to enable substring indexing with `nsSubStrBegin: 1`
2. db2index
3. Add user entry with `uid: auser`
4. Search with the filter `(uid=a*)`

**Expected results**
Search returns the matching entry.

### PR DESCRIPTION
**Pull request by vashirov**
…n non-default nsSubStrBegin/nsSubStrEnd lengths are configured

Bug Description:
1. With begin=1, middle=3, end=3, search doesn't return results for matching entries.
2. With begin=2, middle=2, end=3, server crashes with SEGV

Fix Description:
1. Fix signed/unsigned comparision by casting `bvp->bv_len` and `slapi_value_get_length()` results to `(int)`.
2. Avoid underallocation when (begin + end) > middle*2.

Also port ticket48109_test.py to DSLdapObject.

Fixes: https://github.com/389ds/389-ds-base/issues/7440

## Summary by Sourcery

Fix substring index generation for custom begin/middle/end lengths and add regression coverage for various substring indexing configurations.

Bug Fixes:
- Correct substring key count calculation to prevent under-allocation when begin+end exceeds twice the middle length.
- Fix signed/unsigned length comparisons in substring processing to avoid missed matches and potential crashes.

Enhancements:
- Add a new test suite for substring index behavior across multiple nsSubStr* and nsMatchingRule configurations, replacing the previous ticket-specific test.

### CODE REVIEW

File: ldap/servers/plugins/syntaxes/string.c [hunk 1]
```diff
@@ -551,9 +551,14 @@ string_values2keys(Slapi_PBlock *pb, Slapi_Value **bvals, Slapi_Value ***ivals,
              * NULL terminated, the only downside is that we
              * allocate more space than we really need.
              */
-            nsubs += slapi_value_get_length(*bvlp) - substrlens[INDEX_SUBSTRMIDDLE] + 3;
+            nsubs += (int)slapi_value_get_length(*bvlp) - substrlens[INDEX_SUBSTRMIDDLE] + 3;
+        }
```
Comment (progier389) [inline ldap/servers/plugins/syntaxes/string.c:555]: Looks good but I would have rather writed it:
if (substrlens[INDEX_SUBSTRMIDDLE] * 2 > substrlens[INDEX_SUBSTRBEGIN] + substrlens[INDEX_SUBSTREND]) {
     nsubs += substrlens[INDEX_SUBSTRMIDDLE] * 2 - substrlens[INDEX_SUBSTRBEGIN] - substrlens[INDEX_SUBSTREND];
}

**Review by progier389 — APPROVED** [review]
LGTM
