### PR TITLE
Issue 4506 - Temporary fix for io issues

### LINKED ISSUE #4506: SASL GSSAPI & GSS-SPNEGO performance issue
**Issue Description**

Today I noticed again that LDAP SASL bind with GSSAPI and GSS-SPNEGO are sometimes slow. The issue is similar to https://pagure.io/freeipa/issue/6656. In about half the cases SASL bind is faster. In other cases the operation is more than a magnitude slower. I'm seeing the same performance spikes with GSS-SPNEGO. In fast case GSS-SPNEGO is a bit faster than GSSAPI. In slow cases it degrades like GSSAPI.

**Package Version and Platform:**
 - Platform: Fedora 32
 - Package and version: 389-ds-base-2.0.1-20201215gitae2da1018.fc32.x86_64 and 1.4.3.16-1.fc32, cyrus-sasl-2.1.27-4.fc32.x86_64, krb5-workstation-1.18.2-29.fc32.x86_64

**Steps to Reproduce**
* Install FreeIPA server
* ``kinit -kt /etc/named.keytab DNS/$(hostname)``
* run ``time ldapwhoami -H ldapi://%2Frun%2Fslapd-IPA-TEST.socket -Y GSSAPI`` multiple times

**Expected results**
Command finishes in around 20ms consistently.

**Actual result**

Wall clock time for the command is all over the board. Sometimes the command finishes in less than 20ms, sometimes it's around 250 and every know and then it takes more than 500ms.

```
real    0m0,030s
real    0m0,018s
real    0m0,017s
real    0m0,266s
real    0m0,267s
real    0m0,265s
real    0m0,017s
real    0m0,266s
real    0m0,264s
real    0m0,513s
real    0m0,266s
real    0m0,267s
real    0m0,017s
real    0m0,264s
real    0m0,266s
real    0m0,017s
real    0m0,266s
real    0m0,018s
real    0m0,264s
real    0m0,265s
real    0m0,016s
real    0m0,265s
real    0m0,266s
real    0m0,267s
real    0m0,267s
real    0m0,516s
real    0m0,018s
real    0m0,017s
real    0m0,266s
```

**Additional context**

For testing I have stop all IPA services except DS, disabled and removed all IPA plugins that may affect 389-DS performance, and restarted 389-DS. It did not affect performance.

fast bind
```
    [17/Dec/2020:12:18:24.059835167 +0100] conn=286 fd=109 slot=109 connection from local to /var/run/slapd-IPA-TEST.socket
    [17/Dec/2020:12:18:24.061934129 +0100] conn=286 op=0 BIND dn="" method=sasl version=3 mech=GSSAPI
    [17/Dec/2020:12:18:24.064890914 +0100] conn=286 op=0 RESULT err=14 tag=97 nentries=0 wtime=0.000350396 optime=0.002962757 etime=0.003311237, SASL bind in progress
    [17/Dec/2020:12:18:24.065255570 +0100] conn=286 op=1 BIND dn="" method=sasl version=3 mech=GSSAPI
    [17/Dec/2020:12:18:24.066715112 +0100] conn=286 op=1 RESULT err=14 tag=97 nentries=0 wtime=0.000065520 optime=0.001463546 etime=0.001527052, SASL bind in progress
    [17/Dec/2020:12:18:24.067034922 +0100] conn=286 op=2 BIND dn="" method=sasl version=3 mech=GSSAPI
    [17/Dec/2020:12:18:24.068130645 +0100] conn=286 op=2 RESULT err=0 tag=97 nentries=0 wtime=0.000079306 optime=0.001160701 etime=0.001237869 dn="krbprincipalname=dns/server.ipa.test@ipa.test,cn=services,cn=accounts,dc=ipa,dc=test"
    [17/Dec/2020:12:18:24.068538087 +0100] conn=286 op=3 EXT oid="1.3.6.1.4.1.4203.1.11.3" name="whoami-plugin"
    [17/Dec/2020:12:18:24.068629931 +0100] conn=286 op=3 RESULT err=0 tag=120 nentries=0 wtime=0.000232724 optime=0.000098566 etime=0.000328895
    [17/Dec/2020:12:18:24.069395429 +0100] conn=286 op=4 UNBIND
    [17/Dec/2020:12:18:24.069450050 +0100] conn=286 op=4 fd=109 closed error - U1
```

slow bind (delay between ``op=1`` and ``op=2``)
```
    [17/Dec/2020:12:18:36.625205796 +0100] conn=292 fd=109 slot=109 connection from local to /var/run/slapd-IPA-TEST.socket
    [17/Dec/2020:12:18:36.627115266 +0100] conn=292 op=0 BIND dn="" method=sasl version=3 mech=GSSAPI
    [17/Dec/2020:12:18:36.630209431 +0100] conn=292 op=0 RESULT err=14 tag=97 nentries=0 wtime=0.000370102 optime=0.003100261 etime=0.003468232, SASL bind in progress
    [17/Dec/2020:12:18:36.630610597 +0100] conn=292 op=1 BIND dn="" method=sasl version=3 mech=GSSAPI
    [17/Dec/2020:12:18:36.632120068 +0100] conn=292 op=1 RESULT err=14 tag=97 nentries=0 wtime=0.000076306 optime=0.001513595 etime=0.001587760, SASL bind in progress
    [17/Dec/2020:12:18:36.881177050 +0100] conn=292 op=2 BIND dn="" method=sasl version=3 mech=GSSAPI
    [17/Dec/2020:12:18:36.882648579 +0100] conn=292 op=2 RESULT err=0 tag=97 nentries=0 wtime=0.000174524 optime=0.001485382 etime=0.001657851 dn="krbprincipalname=dns/server.ipa.test@ipa.test,cn=services,cn=accounts,dc=ipa,dc=test"
    [17/Dec/2020:12:18:36.883102483 +0100] conn=292 op=3 EXT oid="1.3.6.1.4.1.4203.1.11.3" name="whoami-plugin"
    [17/Dec/2020:12:18:36.883221013 +0100] conn=292 op=3 RESULT err=0 tag=120 nentries=0 wtime=0.000229879 optime=0.000150909 etime=0.000378423
    [17/Dec/2020:12:18:36.884186770 +0100] conn=292 op=4 UNBIND
    [17/Dec/2020:12:18:36.884207276 +0100] conn=292 op=4 fd=109 closed error - U1
```

At one point I also enabled tracing to trace function calls into SASL stack. There is a long delay between the first and second ``ids_sasl_listmech`` call. You can find a full log at https://cheimes.fedorapeople.org/sasl.log

```
[17/Dec/2020:12:58:38.133255294 +0100] - DEBUG - ids_sasl_server_new - => (vm-171-075.abc.idm.lab.eng.brq.redhat.com)
[17/Dec/2020:12:58:38.145986011 +0100] - DEBUG - ids_sasl_getopt - plugin= option=log_level
[17/Dec/2020:12:58:38.147450940 +0100] - DEBUG - ids_sasl_getopt - plugin= option=auto_transition
[17/Dec/2020:12:58:38.149436807 +0100] - DEBUG - ids_sasl_getopt - plugin= option=mech_list
[17/Dec/2020:12:58:38.157977606 +0100] - DEBUG - ids_sasl_server_new - <=
[17/Dec/2020:12:58:39.043715851 +0100] - DEBUG - ids_sasl_listmech - =>
[17/Dec/2020:12:58:39.045289486 +0100] - DEBUG - ids_sasl_listmech - <=
[17/Dec/2020:12:58:39.841690920 +0100] - DEBUG - ids_sasl_listmech - =>
[17/Dec/2020:12:58:39.843231866 +0100] - DEBUG - ids_sasl_listmech - <=
```

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: Due to how we polled accept and connections
we would interleave these causing possible delays to new
accepts, or delays to connections awaiting work.

Fix Description: Split accept into it's own thread.

fixes: https://github.com/389ds/389-ds-base/issues/4506

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

**Comment by Firstyear** [comment]
@tiran here is a hacky-test fix where I split accept to a seperate thread. Can you test it with your SASL test? I've already run the basic tests and confirmed it works.

**Comment by tiran** [comment]
The patch does not help. It also slows down 389-DS a lot. My test script takes 7 times (16s -> 107s) more time to complete 200 connections.

``389-ds-base-2.0.1-20210104git0f38410ae.fc32.x86_64`` without patch:

```
6ms     3
7ms     3
8ms     74
9ms     48
10ms    7
11ms    4
12ms    2
13ms    2
51ms    1
69ms    1
109ms   2
116ms   1
132ms   1
255ms   7
256ms   7
257ms   21
258ms   10
259ms   4
504ms   1
508ms   1
Total: 16s
```

``389-ds-base-2.0.1-20210104git0f38410ae.fc32.x86_64`` with #4516 patch

```
7ms     5
8ms     45
9ms     77
10ms    21
11ms    1
12ms    4
15ms    1
255ms   2
256ms   5
257ms   20
258ms   13
259ms   1
260ms   1
261ms   1
505ms   2
507ms   1
Total: 107s
```

**Comment by Firstyear** [comment]
@tiran and @tbordaz can you check this again? This makes the accept thread in a seperate thread, and I can see an approx 10% speed up with ldclt -e bindeach (new connections each search). Hopefully this also allows us to identify which half of the socket parts are a problem (or it will just resolve it :) ) 

@progier389 cc because you probably will be interested as it relates a bit to the connection bound check,

Passes with asan, having issues with latest suse to run lsan so I'll need to check that later.

**Comment by tiran** [comment]
My unscientific test script takes roughly 5% more time to finish with your PR. I also noticed that the distribution looks different with 2.0.1. There is another peak at multiple of 100ms.

## latest PR 389-ds-base-2.0.1-20210108gitad13f0ded

```
6ms     7
7ms     14
8ms     835
9ms     390
10ms    50
11ms    10
12ms    1
13ms    3
15ms    2
16ms    3
17ms    1
25ms    1
37ms    1
62ms    1
105ms   1
106ms   8
107ms   67
108ms   98
109ms   20
110ms   3
112ms   1
114ms   2
115ms   1
159ms   1
164ms   1
174ms   1
184ms   1
187ms   1
206ms   1
207ms   4
254ms   8
255ms   72
256ms   18
257ms   174
258ms   119
259ms   16
260ms   5
261ms   2
355ms   4
356ms   12
357ms   8
358ms   5
359ms   1
409ms   1
503ms   8
504ms   8
507ms   4
508ms   2
604ms   2
605ms   1
Total: 168s
```

## nightly build 389-ds-base-2.0.1-20210108git65678bb3b

```
6ms     9
7ms     18
8ms     916
9ms     322
10ms    44
11ms    10
13ms    3
15ms    2
16ms    1
18ms    1
25ms    1
88ms    1
105ms   3
106ms   9
107ms   95
108ms   111
109ms   35
110ms   1
113ms   1
206ms   1
207ms   2
208ms   4
209ms   1
254ms   10
255ms   50
256ms   22
257ms   148
258ms   95
259ms   17
260ms   4
262ms   1
264ms   1
265ms   2
354ms   1
355ms   1
356ms   10
357ms   11
358ms   7
359ms   3
360ms   2
503ms   2
504ms   12
505ms   2
507ms   2
508ms   1
607ms   2
753ms   2
754ms   1
Total: 159s
```

**Comment by progier389** [comment]
Several comments here:
   [1] About the changes:
      If you split the polling threads you need to be careful with the signal_pipe handling. 
      It should be polled in the original thread (to interrupt the poll when polled fds must be added/removed) 
      I am not sure whether a second signal_pipe is needed for the accept poll (depends if the listen fd list may
         dynamically change or not)
    [2] About the issue itself.
           I can think about two possible reasons that could explain that the timout change helps:
           [a]:  That PR_Accept spent long time ( why ? tcpip tuning issue ? ) 
           [b]:   That somewhere in the code a call to signal_listner has been forgotten and some change
                    is taken in account only after the poll timeout expiration
                     (b is nor very plausible because it is a stress test and the poll always get triggered in less than a few ms anyway)
           [c]:   I am not really surprised that splitting the poll thread leads to better performance, 
                       (even without splitting the accept/versus read event)

**Comment by Firstyear** [comment]
> My unscientific test script takes roughly 5% more time to finish with your PR. I also noticed that the distribution looks different with 2.0.1. There is another peak at multiple of 100ms.

That's fine - but now if you want, you can adjust:

```
64 #define SLAPD_WAKEUP_TIMER 250
65 #define SLAPD_ACCEPT_WAKEUP_TIMER 250
```

Because these are now independent, you can adjust this to help bisect which poll we are delaying on. I'd suggest turning ACCEPT_WAKEUP higher, maybe 1000 and WAKEUP down to say 25. That way you can tell if it gets faster, we know it's in the WAKEUP poll, if it gets MUCH slower, then we know it's in the ACCEPT part. 

> Several comments here:
> [1] About the changes:
> If you split the polling threads you need to be careful with the signal_pipe handling.
> It should be polled in the original thread (to interrupt the poll when polled fds must be added/removed)
> I am not sure whether a second signal_pipe is needed for the accept poll (depends if the listen fd list may
> dynamically change or not)

Yep, I was pretty careful about this. I checked all the locations where the signal pipe is woken from, and it's all about existing connections, not accept, which is why I have left the signal pipe as fd[0] in the ct->fd array, so that it still correctly wakes the main event loop when required. I also added a called to wake the signal pipe from the accept thread so that the connection can immediately be read from. 

> [2] About the issue itself.
> I can think about two possible reasons that could explain that the timout change helps:
> [a]: That PR_Accept spent long time ( why ? tcpip tuning issue ? )
> [b]: That somewhere in the code a call to signal_listner has been forgotten and some change
> is taken in account only after the poll timeout expiration

Yep these are all valid possibilities! Additional possibilities:

* We only add a connection fd to be polled if we can successfully lock (we use try lock), so the conn may be locked causing it's initial read to be skipped.
* It could be a subsequent read/partial read where we time out won't re-poll again because trylock
* Because this test is effectively single threaded client, we don't see this in normal conditions as we rarely hit poll timeout as "other events" are waking us and masking the delay.

So this is another benefit to the split, is as mentioned earlier in my reply, we can now tune the poll timeouts separately to see which half has the problem (accept or connection). From there, the next step becomes additional logging of the connection state I think once we know which side it's on. 

> (b is nor very plausible because it is a stress test and the poll always get triggered in less than a few ms anyway)
> [c]: I am not really surprised that splitting the poll thread leads to better performance,
> (even without splitting the accept/versus read event)

Yes, but it's better multi thread / multiple connection performance :) it's been on our TODO for a long time to split accept from connection events. So I think even if this doesn't solve the problem directly, it's going to make it easier to isolate the problem *AND* it causes better performance in the general case :) 

Thanks for your review!

**Comment by progier389** [comment]
> > Several comments here:
> > [1] About the changes:
> > If you split the polling threads you need to be careful with the signal_pipe handling.
> > It should be polled in the original thread (to interrupt the poll when polled fds must be added/removed)
> > I am not sure whether a second signal_pipe is needed for the accept poll (depends if the listen fd list may
> > dynamically change or not)
> 
> Yep, I was pretty careful about this. I checked all the locations where the signal pipe is woken from, and it's all about existing connections, not accept, which is why I have left the signal pipe as fd[0] in the ct->fd array, so that it still correctly wakes the main event loop when required. I also added a called to wake the signal pipe from the accept thread so that the connection can immediately be read from.
OK: My mistake, I reacted because I did not saw the signal pipe initialization in setup_pr_accept_pds as I expected but I did not realized it is now initilazed in setup_pr_ct_firsttime_pds (which is fine) 
> 
> > [2] About the issue itself.
> > I can think about two possible reasons that could explain that the timeout change helps:
> > [a]: That PR_Accept spent long time ( why ? tcpip tuning issue ? )
> > [b]: That somewhere in the code a call to signal_listner has been forgotten and some change
> > is taken in account only after the poll timeout expiration
> 
> Yep these are all valid possibilities! Additional possibilities:
> 
> * We only add a connection fd to be polled if we can successfully lock (we use try lock), so the conn may be locked causing it's initial read to be skipped.
> * It could be a subsequent read/partial read where we time out won't re-poll again because trylock
Interesting remark! 
If one of these two points is causing the problem, that would mean that a call to signal_listner is missing when the connection lock is released. 
   I wonder if we should not then call signal_listner whenever releasing the connection lock ...
   But if we do that we should improve signal_listner (should probably use a variable and atomic operation) to insure 
      that the pipe is written only once per poll loop (otherwise we may get in trouble with the pipe flow control)
> * Because this test is effectively single threaded client, we don't see this in normal conditions as we rarely hit poll timeout as "other events" are waking us and masking the delay.
> 
> So this is another benefit to the split, is as mentioned earlier in my reply, we can now tune the poll timeouts separately to see which half has the problem (accept or connection). From there, the next step becomes additional logging of the connection state I think once we know which side it's on.
> 
> > (b is nor very plausible because it is a stress test and the poll always get triggered in less than a few ms anyway)
> > [c]: I am not really surprised that splitting the poll thread leads to better performance,
> > (even without splitting the accept/versus read event)
> 
> Yes, but it's better multi thread / multiple connection performance :) it's been on our TODO for a long time to split accept from connection events. So I think even if this doesn't solve the problem directly, it's going to make it easier to isolate the problem _AND_ it causes better performance in the general case :)
I fully agree that your patch moves things in the right direction. ([c] is just meaning that having several listening threads should 
  increase the performance (whether splitting the accept from the read events or not). That said, having a dedicated thread
    for accept events has the merit of making the code easier to understand. So although I believe that the root cause of this
     problem is not related to the mix of listening and read events, IMHO we should keep and commit your patch. )
> 
> Thanks for your review!

**Comment by progier389** [comment]
About signal_pipe fd handling:
OK, that is my mistake! I reacted because I did not saw the signal pipe initialization in setup_pr_accept_pds as I expected but I did not realized it is now initilazed in setup_pr_ct_firsttime_pds (which is fine)

About the additional possibilities:
Interesting remark!
The fact that fd are skiped if try lock fails means that a call to signal_listner is missing when the connection lock is released.
But if we fix that we should improve signal_listner (should probably use a variable and atomic operation) to insure
that the pipe is written only once per poll loop (otherwise we may fill up the pipe and get in trouble with the pipe flow control)

About
`Yes, but it's better multi thread / multiple connection performance :) it's been on our TODO for a long time to split accept from connection events. So I think even if this doesn't solve the problem directly, it's going to make it easier to isolate the problem _AND_ it causes better performance in the general case :)`
I fully agree that your patch moves things in the right direction. ([c] is just meaning that having several listening threads should
increase the performance (whether splitting the accept from the read events or not). That said, having a dedicated thread
for accept events has the merit of making the code easier to understand. So although I believe that the root cause of this
problem is not related to the mix of listening and read events, IMHO we should keep and commit your patch. )

**Comment by Firstyear** [comment]
> About signal_pipe fd handling:
> OK, that is my mistake! I reacted because I did not saw the signal pipe initialization in setup_pr_accept_pds as I expected but I did not realized it is now initilazed in setup_pr_ct_firsttime_pds (which is fine)

I've improved the comment in setup_pr_read_pds to highlight how the signal pipe fd is setup.

> 
> About the additional possibilities:
> Interesting remark!
> The fact that fd are skiped if try lock fails means that a call to signal_listner is missing when the connection lock is released.
> But if we fix that we should improve signal_listner (should probably use a variable and atomic operation) to insure
> that the pipe is written only once per poll loop (otherwise we may fill up the pipe and get in trouble with the pipe flow control)

It took me a while to think about this one. In some ways I completely agree, in some I don't. I think that if we were to call the signal_listener after each connection unlock, there are 95 locations in the code base we would need to adjust for this to occur correctly. We could target specific unlock calls, especially focussed around IO paths so that we call the listener on the unlock. connection_threadmain would probably be the primary focus for this, I think. That way when we have an incomplete PDU we prepare the connection immediately to be re-polled if not in turbo mode (though this could make turbo mode un-needed?). I suspect this would be from ret == CONN_TIMEOUT around line 1617 in connection.c. But I'd need to check more thoroughly to be sure. Saying that, even with this change, it doesn't guarantee that when the main event loop checks the connection, that it will be unlocked because another worker may have then taken the lock to do a write. 

Saying this, this also does bring a "risk" that we would be continually waking and rebuilding the fd table as connections complete their reads, so we would then potentially add excess load into the event loop thread. It's a tricky balance ... and that's where my thought to disagree comes in, that perhaps the "simpler" solution is just to reduce the main event loop timeout from 250ms down to 25 (?) since that would have the "same effect" as the event-driven solution you are proposing. 

If I had infinite time I would rewrite connection handling from scratch, but I do not have infinite time :) 

> I fully agree that your patch moves things in the right direction. ([c] is just meaning that having several listening threads should
> increase the performance (whether splitting the accept from the read events or not). That said, having a dedicated thread
> for accept events has the merit of making the code easier to understand. So although I believe that the root cause of this
> problem is not related to the mix of listening and read events, IMHO we should keep and commit your patch. )

Thanks, I appreciate the vote of confidence! I think it would be good to get some feedback from @tiran once he has some time to retest with adjusted wakeup times so we can help narrow down this search, and to give a bit of time for @tbordaz and @mreynolds389 to check this since connection handling is a very important area of the code. The more eyes the better :)

**Comment by Firstyear** [comment]
@mreynolds389 @progier389 Can you please review this - Talking with @progier389 we think this change is valuable regardless of the possible benefit to @tiran, and it does give them more options for testing to isolate the problematic wait timer. It's now in a state I think we can merge it. Thanks!

File: ldap/servers/slapd/daemon.c [hunk 1]
```diff
@@ -1202,133 +1292,117 @@ clear_signal(struct POLL_STRUCT *fds)
...
+        for (fdesc = s_tcps; fdesc && *fdesc; fdesc++, count++) { }
+    }
+#if defined(ENABLE_LDAPI)
+    if (i_unix != NULL) {
+        PRFileDesc **fdesc = NULL;
+        for (fdesc = i_unix; fdesc && *fdesc; fdesc++, count++) { }
+    }
+#endif
 
+    struct POLL_STRUCT *myfds = (struct POLL_STRUCT *)slapi_ch_calloc(1, (count + 1) * sizeof(struct POLL_STRUCT));
```
Comment (progier389) [inline ldap/servers/slapd/daemon.c]: A minor point: Could you move myfds declaration to the top of the function (its scope covers the whole function)

**Review by progier389 — APPROVED** [review]
ACK for me once the minor point get fixed.

**Comment by mreynolds389** [comment]
please remove java style comments ;-)

**Comment by Firstyear** [comment]
> please remove java style comments ;-)

I was *literally* writing the cleanup of the comments as you sent that msg mate. On the other hand ... almost snuck them past you :P

File: ldap/servers/slapd/daemon.c [hunk 2]
```diff
@@ -993,9 +1071,25 @@ slapd_daemon(daemon_ports_t *ports)
...
 
+    /* Prepare the CT for first use */
+    setup_pr_ct_firsttime_pds(the_connection_table);
+
     /* The server is ready and listening for connections. Logging "slapd started" message. */
     unfurl_banners(the_connection_table, ports, n_tcps, s_tcps, i_unix);
 
+    /* Create a thread to accept new connections */
+    accept_thread_p = PR_CreateThread(PR_SYSTEM_THREAD,
+                                    (VFP)(void *)accept_thread, (void*)ports,
```
Comment (mreynolds389) [inline ldap/servers/slapd/daemon.c]: sorry, indentation

File: ldap/servers/slapd/daemon.c [hunk 3]
```diff
@@ -1202,133 +1294,119 @@ clear_signal(struct POLL_STRUCT *fds)
...
-                slapi_log_err(SLAPI_LOG_HOUSE,
-                              "setup_pr_read_pds", "Listening for LDAPI connections on %d\n", socketdesc);
-            }
-        } else {
-            ct->fd[count].fd = NULL;
-            count++;
+    if (i_unix != NULL) {
+        PRFileDesc **fdesc = NULL;
+        for (fdesc = i_unix; fdesc && *fdesc; fdesc++, count++) {
+            myfds[count].fd = *fdesc;
```
Comment (mreynolds389) [inline ldap/servers/slapd/daemon.c:1366]: indentation here

File: ldap/servers/slapd/daemon.c (hunk 2 above)
Comment (mreynolds389) [reply ldap/servers/slapd/daemon.c]: besides that, ack!
