### PR TITLE
Issue 7302 - dblib bdb2mdb fails on F43 -> F43 upgrade

### LINKED ISSUE #7302: dblib bdb2mdb fails on F43 -> F43 upgrade
**Issue Description**
On F42 install IPA, then upgrade 389-ds-base from F43:

```
# NSSLAPD_DB_LIB=bdb ipa-server-install --domain=ipa.test --realm=IPA.TEST --ds-password=password --admin-password=password --forwarder 8.8.8.8 --auto-reverse --domain-level=1 --setup-dns -U
...
dnf update --releasever=43 389-ds-base -y
```

Then try to migrate to mdb:
```
# dsctl IPA-TEST dblib bdb2mdb
cleanup dbmapdir=/var/lib/dirsrv/slapd-IPA-TEST/db dbhome=/dev/shm/slapd-IPA-TEST dblib=bdb
Required space for LDIF files is about 2.5 MB
Required space for DBMAP files is about 6.8 MB
Required number of dbi is 512
Backends exportation 0.000000% (changelog)
Error: Failed to export backend changelog into /var/lib/dirsrv/slapd-IPA-TEST/ldif/__dblib-changelog.ldif.
# coredumpctl
TIME                          PID UID GID SIG     COREFILE EXE               SIZE
Wed 2026-03-04 12:24:06 EST 12702 389 389 SIGSEGV present  /usr/bin/ns-slapd 1.3M
```

Backtrace shows:
```
(gdb) bt
#0  0x00007fdeaff36f66 in bdb_get_page_count (db=<optimized out>, count=count@entry=0x55fe4a792308) at ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c:1795
#1  0x00007fdeaff3736d in bdb_get_inst_page_count (li=<optimized out>, inst=0x55fe4a792110) at ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c:1876
#2  0x00007fdeaff3eac3 in bdb_start_autotune (li=0x55fe4a66be00) at ldap/servers/slapd/back-ldbm/db-bdb/bdb_misc.c:241
#3  0x00007fdeafee3113 in ldbm_back_start (pb=0x55fe4a7a7bd0) at ldap/servers/slapd/back-ldbm/start.c:109
#4  0x00007fdeb208b2f4 in plugin_call_func (list=0x55fe4a84b370, operation=operation@entry=212, pb=0x55fe4a7a7bd0, call_one=call_one@entry=1) at ldap/servers/slapd/plugin.c:1996
#5  0x00007fdeb208bd03 in plugin_call_one (list=<optimized out>, operation=212, pb=<optimized out>) at ldap/servers/slapd/plugin.c:1945
#6  plugin_dependency_startall (errmsg=<synthetic pointer>, operation=212, argc=<optimized out>, argv=<optimized out>, plugin_list=<optimized out>) at ldap/servers/slapd/plugin.c:1700
#7  plugin_startall (argc=argc@entry=9, argv=argv@entry=0x7fff77ad0378, plugin_list=<optimized out>) at ldap/servers/slapd/plugin.c:1917
#8  0x000055fe1f63956d in slapd_exemode_db2ldif (argc=9, argv=0x7fff77ad0378, mcfg=0x7fff77ad0160) at ldap/servers/slapd/main.c:2216
#9  main (argc=9, argv=0x7fff77ad0378) at ldap/servers/slapd/main.c:826
```

`db->stat` is stubbed with `nothing()` which returns DB_SUCCESS without populating the stats output parameter. Both `bdb_get_page_count()` and `bdb_get_entries_count()` then dereference the NULL stats pointer, causing a segfault.

### PR DESCRIPTION
**Pull request by vashirov**
Bug Description:
`db->stat` is stubbed with `nothing()` which returns DB_SUCCESS without populating the stats output parameter. Both `bdb_get_page_count()` and `bdb_get_entries_count()` then dereference the NULL stats pointer, causing a segfault.

Fix Descrption:
Add NULL checks for the stats pointer after `db->stat()` calls in both `bdb_get_page_count()` and `bdb_get_entries_count()`.

Fixes: https://github.com/389ds/389-ds-base/issues/7302

## Summary by Sourcery

Bug Fixes:
- Prevent segmentation faults in BDB page and entry count helpers by handling NULL statistics returned from db->stat() and defaulting counts to zero.

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c [hunk 1]
```diff
@@ -7081,7 +7085,11 @@ bdb_get_entries_count(dbi_db_t *db, dbi_txn_t *txn, int *count)
                       rc, db_strerror(rc));
         rc = DBI_RC_OTHER;
     }
-    *count = rc ? 0 : stats->bt_ndata;
+    if (rc || stats == NULL) {
```
Comment (tbordaz) [inline ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c]: The fix looks good to me but bdb_get_entries_count is a callback used for example in vlvIndex_get_indexlength.
The vlv code looks robust to vlv_indexlength being 0 but it is difficult to be sure. Should we log a info that we failed to retrieve the stat so that if it crash later in VLV we will have a tips ?

**Review by tbordaz — APPROVED** [review]
LGTM

File: ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c (hunk 1 above)
Comment (vashirov) [reply ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c]: Yes, we should. I've added a message, fixed a small typo and moved the logic a bit. Please review.

**Review by progier389 — APPROVED** [review]
LGTM
