### PR TITLE
Issue 7346 - DS does not handle escape char in bind user

### LINKED ISSUE #4383: group rdn with leading space char and add fails error 21 invalid syntax and delete fails error 32
Ticket was cloned from Red Hat Bugzilla (product _Red Hat Enterprise Linux 8_): [Bug 1888863](https://bugzilla.redhat.com/show_bug.cgi?id=1888863)

```
Description of problem:

deleting the DN of a group fails if there is a leading space char in the RDN
fails with error 32

user entries have a valid DN syntax with

dn: uid=\ leadingspaceuser1,cn=users,dc=example,dc=test
dn: uid=\20leadingspaceuser1,cn=users,dc=example,dc=test

dn: cn=\ leadingspaceuser1,cn=users,dc=example,dc=test
dn: cn=\20leadingspaceuser1,cn=users,dc=example,dc=test


but group DNs have a different behavior:

dn: cn=\ specialgroupname1,cn=groups,dc=example,dc=test
dn: cn=\20specialgroupname1,cn=groups,dc=example,dc=test

then, if such a group is in the database, it cannot be deleted, there is an
error 32

why do the special chars cannot be escaped for groups?


Version-Release number of selected component (if applicable):
RHEL-8.2
389-ds-base-1.4.x

but same on any versions of 389-ds-base


How reproducible:
on demand

Steps to Reproduce:
1. have some data

echo \ specialgroupname1 | base64
IHNwZWNpYWxncm91cG5hbWUxCg==

echo IHNwZWNpYWxncm91cG5hbWUxCg== | base64 -d
 specialgroupname1

cat << EOF > ~/dn.group.cn.with.leading.space.cn.users.ldif
dn: cn=users,dc=example,dc=test
objectClass: top
objectClass: nsContainer
cn: users

dn: uid=user1,cn=users,dc=example,dc=test
givenName: Test
sn: User1
uid: user1
cn: Test User1
displayName: Test User1
initials: TU
gecos: Test User1
homeDirectory: /home/user1
uidNumber: 969400001
gidNumber: 969400001
objectClass: person
objectClass: organizationalperson
objectClass: posixaccount
objectClass: inetorgperson
objectClass: inetuser

dn: uid=user2,cn=users,dc=example,dc=test
givenName: Test
sn: User2
uid: user2
cn: Test User2
displayName: Test User2
initials: TU
gecos: Test User2
homeDirectory: /home/user2
uidNumber: 969400002
gidNumber: 969400002
objectClass: person
objectClass: organizationalperson
objectClass: posixaccount
objectClass: inetorgperson
objectClass: inetuser

dn: cn=groups,dc=example,dc=test
objectClass: top
objectClass: nsContainer
cn: groups

dn: cn=\ specialgroupname1,cn=groups,dc=example,dc=test
objectClass: groupofnames
cn:: IHNwZWNpYWxncm91cG5hbWUxCg==
description:  cn with a space header char in string
member: uid=user1,cn=users,dc=example,dc=test
member: uid=user2,cn=users,dc=example,dc=test
EOF

sed -i 's/[[:space:]]*$//' ~/cn.with.a.spacegroupname.cn.groupss.ldif


2. attempt to create the goupr DN with a leading char in RDN

ldapmodify -xD "cn=directory manager" -w password -caf
~/dn.group.cn.with.leading.space.cn.users.ldif



Actual results:

adding new entry "cn=\ specialgroupname1,cn=groups,dc=example,dc=test"
ldap_add: Invalid syntax (21)

adding new entry "cn=\20specialgroupname1,cn=groups,dc=example,dc=test"
ldap_add: Invalid DN syntax (34)
        additional info: DN value invalid per syntax


Expected results:
yes


Additional info:
was reported on RHEL-6 / RHDS-9 by a customer.
```

### LINKED ISSUE #7346: DS  does not handle escape char in bind user
**Issue Description**
When normalizing a DN, the server keeps the escaped spaces in the assertion values.
This was introduced with [389-ds-base/issues/4383](https://github.com/389ds/389-ds-base/issues/4383)
 [rfc4514](https://datatracker.ietf.org/doc/html/rfc4514#section-3) requires to keep them only for the heading/leading spaces. Spaces in the middle of the assertion should be normalized as SPACE.

**Package Version and Platform:**
 since 1.4.3

**Steps to Reproduce**
Create an entry like 'uid=my uid,dc=com' then bind with 'uid=my\\20uid,dc=com'

**Expected results**
escaped spaces in the middle  assertion values of RDNs should be normalize as ' '

### PR DESCRIPTION
**Pull request by tbordaz**
Bug description:
	When normalization assertion value in a DN, the fix #4383
        keeps the escaped spaces (i.e '\20') whatever their position
	in the value.
	The RFC requires this for heading spaces but not for the others.
	This prevent to authenticate with a DN containing escaped spaces
	in the middle of assertion value
Fix description:
	Apply the fix #4383 only for the 1rst value of the assertion.

fixes: #7346

Reviewed by:

## Summary by Sourcery

Handle escaped spaces in DNs correctly during normalization to allow binds with non-leading escaped spaces.

Bug Fixes:
- Fix DN normalization so that escaped spaces (\20) are only preserved for the first attribute value, allowing authentication with DNs containing escaped spaces in the middle of the value.

Tests:
- Add a regression test that creates a user with a space in the RDN and verifies binding and searching using both escaped and unescaped spaces in the DN and search filter.

### CODE REVIEW

File: ldap/servers/slapd/dn.c [hunk 1]
```diff
@@ -872,7 +872,8 @@ slapi_dn_normalize_ext(char *src, size_t src_len, char **dest, size_t *dest_len)
                     if (n == 0) { /* don't change \00 */
                         *d++ = *++s;
                         *d++ = *++s;
-                    } else if (n == 32) { /* leave \20 (space) intact */
+                    } else if ((state == INVALUE1ST) && (n == 32)) {
+			/* leave \20 (space) intact for heading space */
```
Comment (mreynolds389) [inline ldap/servers/slapd/dn.c]: Indentation is off :-)

Also what about other approved escaped characters like quotes, and equal signs?

Comment (tbordaz) [reply ldap/servers/slapd/dn.c]: The RFC says regarding the attributeValue
<pre>
; The following characters are to be escaped when they appear
; in the value to be encoded: ESC, one of <escaped>, leading
; SHARP or SPACE, trailing SPACE, and NULL.
</pre>
So IIUC for this specific leading character we should preserve leading SHARP and SPACE.
I will had it

**Review by mreynolds389 — APPROVED** [review]
