### PR TITLE
Issue 4373 - BUG - calloc of size 0 in MT build

### LINKED ISSUE #4373: dsconf chaining may create invalid config when parent suffix does not exist
It is possible that someone wishes to create a chaining config, where no parent suffix already exists. Consider chaining say for dc=example,dc=com and the existing DB is for dc=example,dc=org. In this case, dsconf creates the mapping tree entry with a parent suffix of dc=com, even though no mapping tree entry for dc=com exists.

When the chaining entry is created, the mapping tree must be examined to determine if a parent *does* exist and what it is along the DN path.

### PR DESCRIPTION
**Pull request by Firstyear**
Bug Description: In some cases it's possible for there to be
no mapping trees which causes a warning of a calloc of size
0.

Fix Description: In these cases, we can skip the attempt to calloc
and build.

fixes: https://github.com/389ds/389-ds-base/issues/4373

Author: William Brown <william@blackhats.net.au>

Review by: ???

### CODE REVIEW

**Comment by mreynolds389** [comment]
LGTM

**Comment by Firstyear** [comment]
```
   5a80dd90b..18184e5e8  389-ds-base-1.4.4 -> 389-ds-base-1.4.4
   ccc33ecf9..305b75e56  389-ds-base-1.4.3 -> 389-ds-base-1.4.3
```

File: ldap/servers/slapd/mapping_tree.c [hunk 1]
```diff
@@ -918,6 +918,14 @@ mapping_tree_node_build_tree()
      */
     int ent_count = 0;
     slapi_pblock_get(pb, SLAPI_NENTRIES, (void *)&ent_count);
+    if (ent_count == 0) {
```
Comment (tbordaz) [inline ldap/servers/slapd/mapping_tree.c:921]: Just for curiosity, at the point "_Slapi_Entry **entries_" is not NULL, in which case ent_count could it be 0 ?

Comment (Firstyear) [reply ldap/servers/slapd/mapping_tree.c:921]: @tbordaz Good catch, looking at search_internal_pb then entries is always set to entries size + 1, but ent_count could be 0 so I think I need to do a change like:

```
diff --git a/ldap/servers/slapd/mapping_tree.c b/ldap/servers/slapd/mapping_tree.c
index 2cc4bf82c..6df27163f 100644
--- a/ldap/servers/slapd/mapping_tree.c
+++ b/ldap/servers/slapd/mapping_tree.c
@@ -936,8 +936,8 @@ mapping_tree_node_build_tree()
     }
     slapi_ch_free((void **)&ordered_suffixes);

-    slapi_free_search_results_internal(pb);
 build_tree_done:
+    slapi_free_search_results_internal(pb);
     slapi_pblock_destroy(pb);
     slapi_ch_free((void **)&filter);
     return result;
```

Comment (Firstyear) [reply ldap/servers/slapd/mapping_tree.c:921]: See #4502 @tbordaz
