### PR TITLE
Issue 7012 - improve dscrl dbverify result when backend does not exists

### LINKED ISSUE #7012: improve dscrl dbverify result when backend does not exists
**Issue Description**
When bename does not exists, dsctl instance dbverify bename 
  fails with exit code 1 and no explicit error message with bdb
  success with lmdb
The idea is to add:
  an error message telling that bename is not found in bdb case
  a warning message telling that dbverify is useless and always succeed with lmdb

Note that lmdb does not need any database recovery mechanism
   (that is why dbverify function has no more sense)

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: main branch but all versions are impacted 

**Steps to Reproduce**
1. Install an instance with default sample data
2. Stop the instance
3. Run: dsctl instance dbverify BadBackend
4. See error (no explicit error messages)

**Expected results**
Should have a clear message explaining the failure in bdb case
 and the success in lmdb case

**Additional context**
https://issues.redhat.com/browse/RHEL-107003

### PR DESCRIPTION
**Pull request by progier389**
Improve error message when running dsctl instance dbverify wrongBeName
To tell explicitly that the backend does not exists in bdb case
To tell explicitly that dbverify is useless and always successfull in lmdb case

Issue: #7012 

Reviewed by: @mreynolds389 and @tbordaz  (Thanks!)

## Summary by Sourcery

Improve the dbverify command to explicitly report missing BDB backends and warn for LMDB always-successful checks, and add a test covering both cases

Enhancements:
- Log an explicit error when dbverify is invoked on a non-existent BDB backend
- Emit a warning in the LMDB verify implementation that the feature is always successful and effectively meaningless
- Ensure the test teardown removes its file handler to prevent log handler leaks

Tests:
- Add a run_dbverify helper to invoke dsctl dbverify and validate its exit code and output
- Introduce test_dbverify_bad_bename to verify correct exit codes and messages for missing backends in both BDB and LMDB scenarios

### CODE REVIEW

File: ldap/servers/slapd/back-ldbm/db-mdb/mdb_verify.c [hunk 1]
```diff
@@ -17,5 +17,6 @@
 int
 dbmdb_verify(Slapi_PBlock *pb)
 {
+    slapi_log_err(SLAPI_LOG_WARNING, "dbmdb_verify", "With lmdb, db_verify feature is meaningless and always successful.\n");
```
Comment (mreynolds389) [inline ldap/servers/slapd/back-ldbm/db-mdb/mdb_verify.c]: Very minor issue with grammar:

    With lmdb, db_verify feature is meaningless and is always successful

**Review by mreynolds389 — APPROVED** [review]

**Review by tbordaz — APPROVED** [review]
LGTM
