### PR TITLE
Issue 5120 - ns-slapd doesn't start in referral mode

### LINKED ISSUE #5120: ns-slapd doesn't start in referral mode
**Issue Description**
I have 2 instances: instance1 and instance2. I'm trying to start `ns-slapd` in referral mode, but it crashes:
```
(gdb) bt
#0  0x00007ffff7d95616 in mtn_get_be
    (target_node=0x0, pb=0x55555577be20, be=0x7fffffff9450, index=0x7fffffff943c, referral=0x7fffffff9448, errorbuf=0x7fffffff9610 "", ebuflen=512) at ldap/servers/slapd/mapping_tree.c:2523
#1  0x00007ffff7d938b9 in slapi_mapping_tree_select_all
    (pb=0x55555577be20, be_list=0x7fffffffbb60, referral_list=0x7fffffff9c10, errorbuf=0x7fffffff9610 "", ebuflen=512)
    at ldap/servers/slapd/mapping_tree.c:2231
#2  0x00007ffff7da5038 in op_shared_search (pb=0x55555577be20, send_result=1) at ldap/servers/slapd/opshared.c:472
#3  0x00007ffff7dafadd in search_internal_callback_pb
    (pb=pb@entry=0x55555577be20, callback_data=callback_data@entry=0x7fffffffdbb0, prc=prc@entry=0x7ffff7da6ce0 <internal_plugin_result_callback>, psec=psec@entry=0x7ffff7da9060 <internal_plugin_search_entry_callback>, prec=prec@entry=0x7ffff7da7db0 <internal_plugin_search_referral_callback>) at ldap/servers/slapd/plugin_internal_op.c:730
#4  0x00007ffff7dafdaf in search_internal_pb (pb=0x55555577be20) at ldap/servers/slapd/plugin_internal_op.c:594
#5  0x00007ffff7d76bb9 in initialize_ldapi_auth_dn_mappings (reload=LDAPI_STARTUP) at ldap/servers/slapd/ldapi.c:61
#6  0x000055555557161c in slapd_daemon (ports=0x7fffffffde80) at ldap/servers/slapd/daemon.c:1065
#7  0x00005555555665c1 in main (argc=6, argv=<optimized out>) at ldap/servers/slapd/main.c:1121
```

It also ignores port set in `dse.ldif` and tries to bind to the default port 389, unless option `-p` is passed.

```
# grep nsslapd-port /etc/dirsrv/slapd-instance2/dse.ldif
nsslapd-port: 38902
...

646             mcfg.n_port = config_get_port();
(gdb) p config_get_port()
$1 = 389
```

**Package Version and Platform:**
 - Platform: Fedora
 - Package and version: 389-ds-base-2.0.12-1.fc35.x86_64

**Steps to Reproduce**
1. Create 2 instances
2. Run `ns-slapd` in referral mode:
```
ns-slapd refer -D /etc/dirsrv/slapd-instance2 -r ldap://localhost:38901 -d16384
```

Finally, I wanted to modify systemd unit to allow `ns-slapd` to run in referral mode, but apparently it doesn't support option `-i` needed to specify PID file.

### PR DESCRIPTION
**Pull request by jchapma**
Bug description: Trying to start ns-slapd in referral mode results in a crash.

Fix description: This feature has been broken for a while now, removing it. If there is an attempt to start ns-slapd in referral mode, we issue a message saying its not supported and exit.

Fixes: https://github.com/389ds/389-ds-base/issues/5120

Reviewed by:

### CODE REVIEW

**Comment by jchapma** [comment]
This commit needs to be cherry picked to all branches back to 1.4.3.

File: ldap/servers/slapd/main.c [hunk 1]
```diff
@@ -651,108 +651,87 @@ main(int argc, char **argv)
...
-        /*
-         * Process the config files.
-         */
-        if (0 == slapd_bootstrap_config(slapdFrontendConfig->configdir)) {
-            slapi_log_err(SLAPI_LOG_EMERG, "main",
-                          "The configuration files in directory %s could not be read or were not found.  Please refer to the error log or output for more information.\n",
-                          slapdFrontendConfig->configdir);
-            exit(1);
-        }
+    /*
```
Comment (progier389) [inline ldap/servers/slapd/main.c:699]: comment alignment looks weird  (maybe tab versus spaces issue ...)

**Review by progier389 — APPROVED** [review]
looks good except a minor issue

File: ldap/servers/slapd/slap.h [hunk 2]
```diff
@@ -40,12 +40,11 @@ static char ptokPBE[34] = "Internal (Software) Token        ";
...
-#define SLAPD_EXEMODE_SUFFIX2INSTANCE  9
-#define SLAPD_EXEMODE_PRINTVERSION    10
-#define SLAPD_EXEMODE_UPGRADEDB       11
-#define SLAPD_EXEMODE_DBVERIFY        12
-#define SLAPD_EXEMODE_UPGRADEDNFORMAT 13
+#define SLAPD_EXEMODE_SUFFIX2INSTANCE  8
+#define SLAPD_EXEMODE_PRINTVERSION     9
+#define SLAPD_EXEMODE_UPGRADEDB       10
+#define SLAPD_EXEMODE_DBVERIFY        11
+#define SLAPD_EXEMODE_UPGRADEDNFORMAT 12
```
Comment (droideck) [inline ldap/servers/slapd/slap.h]: I worry a bit here that we may break binary compatibility because of the reordering

**Review by droideck — CHANGES_REQUESTED** [review]

File: ldap/servers/slapd/slap.h (hunk 2 above)
Comment (jchapma) [reply ldap/servers/slapd/slap.h]: Yes I understand your concern, let me revert the reordering and mark it as deprecated.

Comment (tbordaz) [reply ldap/servers/slapd/slap.h]: I had similar concern but IIUC it is only used internally in the server (no CLI). I would also vote to keep the current ordering (deprecating the flag with a comment for example).

**Review by droideck — APPROVED** [review]
LGTM!
